### ISSUE TITLE
logEvent requires parameters, but it isn't marked as such

### ISSUE THREAD

**Issue by mikebcurtis** [oddbit/flutter_facebook_app_events#1]
When I call FacebookLogEvents logEvent with no parameters it throws an exception.

`facebookAppEvents?.logEvent(name: name);`

...throws the following exception in SwiftFacebookAppEventsPlugin handleLogEvent:

`Could not cast value of type 'NSNull' (0x10c65fe48) to 'NSDictionary' (0x10c65f880).
2019-10-18 14:17:47.286252-0600 Runner[38866:693847] Could not cast value of type 'NSNull' (0x10c65fe48) to 'NSDictionary' (0x10c65f880).`

If I add parameters, however, there is no exception.

`facebookAppEvents?.logEvent(name: name, parameters: {}, valueToSum: 1,);`

I recommend either making parameters required when calling FacebookLogEvents.logEvent, or handling NSNull in SwiftFacebookAppEventsPlugin.handleLogEvent.

**Comment by DennisAlund** [comment]
Sorry for the inconvenience and for catching the issue. Can you confirm that it is working in version 0.2.2 or higher?

**Comment by DennisAlund** [comment]
I'll close this issue for now and feel free to open it if you consider the issue to still be a thing.
