### ISSUE TITLE
Plugin breaks an app if it uses shared_preferences

### ISSUE THREAD

**Issue by caseyryan** [oddbit/flutter_facebook_app_events#100]
If you add shared_preferences: 0.5.12+4 (or other version) along with this plugin, you wont be able to use shared preferences. Shared preferences plugin will throw MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences it flutter_facebook_app_events is added to project. 
If it's not, shared preferences work just fine

Most probably it's related to Facebook SDK and not to the plugin itself but if you could check it out, it would be great

**Comment by Altroo** [comment]
Same error here, any fix happening soon ?

**Comment by caseyryan** [comment]
p.s. facebook breaks not only shared preferences. I can surely safe flutter_secure_storage also throw missing plugin exception after that and maybe some other plugins too

**Comment by Altroo** [comment]
Yes i can confirm camera, device_info, crashlytics also breaks.

**Comment by DennisAlund** [comment]
Thanks for the report @caseyryan ... two things
1. Use the issue template for bug reports so that it's possible to troubleshoot with full context
2. Question: have you searched existing issues for "" and tried any of the configuration mistakes that caused similar issues in the past? Such as https://github.com/oddbit/flutter_facebook_app_events/issues/84#issuecomment-784369421 ? 

If you did point no. 2 and confirmed it's not a project configuration issue on your side. Then please do point no. 1

**Comment by caseyryan** [comment]
Hi @DennisAlund, thanks for your reply
1) I've intentionally removed the template because there is no need for such a huge context. It's enough to simply add shared_preferences to the project along with facebook_app_events and try to use shared prefs, e.g. write or read some data with it. The plugin will throw MissingPluginException. Without facebook_app_events it will work as expected. 
2) Of course. I understand anyone can make such a simple mistake but I'm experienced enough to find it. I can assure you this is not the case, my project is set correctly, I've checked everything. 
And another point. I think the plugin should just print some error to console in case of an incorrect configuration but not break the whole app
p.s. I'll try to reproduce it with your example project today

**Comment by caseyryan** [comment]
Ok, I've checked it with your example project. Added shared_preferences, flutter_secure_storage and some other plugins. And.. it works just fine. Then I've checked my AndroidManifest again and haven't found anything wrong. 
The only thing I've noticed is that the project was initially created with an older version of flutter and it also has older gradle version. I've updated all gradle and kotlin versions to the ones I use and it still works. 
Now I'm completely stuck. 
The only idea I have at the moment is that there is some difference in other generated configs or maybe some other plugins cause this behavior. 
Anyway, I'll close this issue right now since it's really not directly related to the plugin. 
If I find the reason why it happens, I'll let you know

**Comment by caseyryan** [comment]
Pinned it. Actually the reason was indeed in my configuration (but not so obvious). Your config is using strings/facebook_app_id but I couldn't use it like this because I take these values from flavor configurations
and write them like so:
```
<meta-data
          android:name="com.facebook.sdk.ApplicationId"
          android:value="${facebookAppId}" />
```

To check if everything works I added facebook ID here directly (hardcoded) 
```
<meta-data
          android:name="com.facebook.sdk.ApplicationId"
          android:value="1234567890123" />
```
But I forgot I must add a leading slash in this case. So the one above won't work 
and this one will

```
<meta-data
          android:name="com.facebook.sdk.ApplicationId"
          android:value="/1234567890123" />
```
In case someone bumps into it, check if you don't make the same mistake 

@DennisAlund nice plugin, thank you for your great work :)

**Comment by Altroo** [comment]
@caseyryan Thank's alot this really helps i did the same passing the facebook ID directly on the meta-data but didn't notice to add the -> /

**Comment by Altroo** [comment]
Question : 
Do i need to also add this : 

implementation 'com.facebook.android:facebook-android-sdk:[5,6)'

Because i don't see it added.

**Comment by caseyryan** [comment]
@Altroo you don't need to add this implementation because the plugin already adds facebook sdk in its gradle.build

**Comment by Altroo** [comment]
@caseyryan Thank's alot 👍  then this mean my setup is correct & no errors found 😄
