### ISSUE TITLE
Migration to null safety.

### ISSUE THREAD

**Issue by mrdemqn** [oddbit/flutter_facebook_app_events#101]
Hi!

I ran into a problem with the migration of my project to Null Safety Sound. Since the plugin does not support zero security.

Please tell me if plans for the migration of the plugin?

**Comment by dospringer** [comment]
Duplicate issue: [https://github.com/oddbit/flutter_facebook_app_events/issues/92](https://github.com/oddbit/flutter_facebook_app_events/issues/92)

**Comment by DennisAlund** [comment]
Resolved in #90
