### ISSUE TITLE
Not working with flutter_facebook_login

### ISSUE THREAD

**Issue by msayedhasan** [oddbit/flutter_facebook_app_events#104]
I was trying to use facebook_app_events  from https://pub.dev/packages/facebook_app_events I got my app crashes in android when I try to login with facebook. And when I try to run pod install in iOS I got an error about using two different FBSDK.

## Current Behavior
The app crashes in android 
in iOS => pod install can't be done

## Possible Solution
Change the used FBSDK to be compitable with flutter facebook login

**Comment by msayedhasan** [comment]
Worked with flutter_facebook_auth

**Comment by sukhkmr19** [comment]
Not working with flutter_facebook_auth same issue again 

The app crashes in android
in iOS => pod install can't be done

**Comment by hazem1262** [comment]
I have this problem now facebook_app_events and flutter_login_facebook not working together, any fix?
