### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

### ISSUE THREAD

**Issue by mrdishant** [oddbit/flutter_facebook_app_events#105]
Getting the following error on log event

E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): Failed to handle method call
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.createBundleFromMap(FacebookAppEventsPlugin.kt:196)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleLogEvent(FacebookAppEventsPlugin.kt:100)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:48)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(29822): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

**Comment by AndrewSheetMetal** [comment]
I am getting the same error using the Version: 0.11.2

But `logActivatedApp` seems to work.

**Comment by knvpk** [comment]
Im also getting the same error for `logViewContent`, but if i give the empty string for optional params also it is submitting successfully.

**Comment by knvpk** [comment]
@AndrewSheetMetal did you solve the problem.

**Comment by LangRizkie** [comment]
just add empty Content parameter
`content: {}`

**Comment by solikhver** [comment]
Seems that Kotlin part of plugin do not handle null values for tracking methods arguments (during constructing Bundle).
Workaround is to avoid nullable arguments (skipping arguments) when log call performed.

Call that avoids error:
`facebook.logInitiatedCheckout(totalPrice: totalPrice, currency: 'EUR', contentType: 'cart', contentId: '0', numItems: itemCount);`
Instead of call that could lead to error:
`facebook.logInitiatedCheckout(totalPrice: totalPrice, currency: 'EUR');`
