### ISSUE TITLE
Login with facebook Getting Crushed After added Flutter_facebook_app_events

### ISSUE THREAD

**Issue by ski96277** [oddbit/flutter_facebook_app_events#110]
## Current Behavior
I/ViewRootImpl@9439279[MainActivity](31093): ViewPostIme pointer 0
I/ViewRootImpl@9439279[MainActivity](31093): ViewPostIme pointer 1
I/ViewRootImpl@9439279[MainActivity](31093): ViewPostIme pointer 0
I/ViewRootImpl@9439279[MainActivity](31093): ViewPostIme pointer 1
D/SensorManager(31093): unregisterListener :: com.facebook.appevents.codeless.ViewIndexingTrigger@2cfe33c
I/DecorView(31093): [INFO] isPopOver=false, config=true
I/DecorView(31093): updateCaptionType >> DecorView@9c7d213[], isFloating=false, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=true
D/DecorView(31093): setCaptionType = 0, this = DecorView@9c7d213[]
D/SensorManager(31093): registerListener :: 11, lsm6dsm Accelerometer Non-wakeup, 66667, 0, com.facebook.appevents.codeless.ViewIndexingTrigger@2cfe33c
D/AndroidRuntime(31093): Shutting down VM
E/AndroidRuntime(31093): FATAL EXCEPTION: main
E/AndroidRuntime(31093): Process: com.riseuplabs.gameplan, PID: 31093
E/AndroidRuntime(31093): java.lang.NoSuchMethodError: No static method createProxyAuthIntent(Landroid/content/Context;Ljava/lang/String;Ljava/util/Collection;Ljava/lang/String;ZZLcom/facebook/login/DefaultAudience;Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent; in class Lcom/facebook/internal/NativeProtocol; or its super classes (declaration of 'com.facebook.internal.NativeProtocol' appears in /data/app/~~Lh_B8g06bJCnDC_8cK7_fA==/com.riseuplabs.gameplan-pgnti1K_8Z70NfdILFAEfA==/base.apk)
E/AndroidRuntime(31093): 	at com.facebook.login.KatanaProxyLoginMethodHandler.tryAuthorize(KatanaProxyLoginMethodHandler.java:44)
E/AndroidRuntime(31093): 	at com.facebook.login.LoginClient.tryCurrentHandler(LoginClient.java:264)
E/AndroidRuntime(31093): 	at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:216)
E/AndroidRuntime(31093): 	at com.facebook.login.LoginClient.authorize(LoginClient.java:121)
E/AndroidRuntime(31093): 	at com.facebook.login.LoginClient.startOrContinueAuth(LoginClient.java:102)
E/AndroidRuntime(31093): 	at com.facebook.login.LoginFragment.onResume(LoginFragment.java:160)
E/AndroidRuntime(31093): 	at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
E/AndroidRuntime(31093): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
E/AndroidRuntime(31093): 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
E/AndroidRuntime(31093): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
E/AndroidRuntime(31093): 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
E/AndroidRuntime(31093): 	at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
E/AndroidRuntime(31093): 	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
E/AndroidRuntime(31093): 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
E/AndroidRuntime(31093): 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
E/AndroidRuntime(31093): 	at android.app.Activity.performResume(Activity.java:8369)
E/AndroidRuntime(31093): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4854)
E/AndroidRuntime(31093): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4901)
E/AndroidRuntime(31093): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
E/AndroidRuntime(31093): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(31093): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(31093): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/AndroidRuntime(31093): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31093): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(31093): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AndroidRuntime(31093): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31093): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(31093): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
I/Process (31093): Sending signal. PID: 31093 SIG: 9
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"63","method":"getMemoryUsage","params":{"isolateId":"isolates/1178862776677087"}}

**Comment by FetFrumos** [comment]
I have same issue, any news?

**Comment by ski96277** [comment]
> I have same issue, any news?

i Used flutter_facebook_auth  library instead of flutter_facebook_login library. Now It's working
