### ISSUE TITLE
When build and run on Android Emulator getting below error

### ISSUE THREAD

**Issue by zuzu-dev** [oddbit/flutter_facebook_app_events#112]
E/GraphResponse(11295): {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '337642317772209' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}

**Comment by DennisAlund** [comment]
Please make sure that issue requests are using the issue template as described in README: https://github.com/oddbit/flutter_facebook_app_events#reporting-bugs-and-issues

This will ensure that you provide enough information to be able to narrow the problem down to this plugin and also for us to be able to help troubleshooting. 

This looks like it might be a good discussion for stackoverflow.
