### ISSUE TITLE
Not sending events to Facebook on iOS 14+

### ISSUE THREAD

**Issue by andreshndz** [oddbit/flutter_facebook_app_events#113]
## Expected Behavior
Sending events from iOS 14 and receive them at the events tester.

## Current Behavior
No events received.

## Possible Solution
I read about upgrade Facebook SDK version at least to 8.0 (9.0 if you need login), but I think that is not the problem. Here we use 9.1

## Steps to Reproduce (for bugs)
1. Send an event
2. On IntelliJ logs, you can see everything is working well and it was sent
3. Nothing appears at the events tester.

## Context
We are working to improve our analytics for better campaigns and better KPIs.

## Your Environment
* Operating System and version: MacOS Big Sur
* flutter_facebook_app_events version:  0.11.2

**Comment by tonishiva** [comment]
I have the same problem. Please let me know if you find any solution.

**Comment by faithomotoso** [comment]
I've been having the same issue. I got it to work somehow by initializing in `AppDelegate.swift` and adding `Settings.setAdvertiserTrackingEnabled(true)` after initializing but it stopped working after a while.

**Comment by faithomotoso** [comment]
Been able to resolve this. You have to request tracking permission before logging events would work. I used this package https://pub.dev/packages/app_tracking_transparency.

**Comment by jpiabrantes** [comment]
I am having the same problem. Do I need to update to the 0.12 version? I am also using 0.11.2 to avoid the null safety..

**Comment by faithomotoso** [comment]
@jpiabrantes I don't think you need to update. You have to request a permission from the user before event tracking would work on iOS 14.5

**Comment by jpiabrantes** [comment]
@faithomotoso I am asking for permission with https://pub.dev/packages/app_tracking_transparency and it is still not working. I really don't want to update to 2.0.

**Comment by faithomotoso** [comment]
@jpiabrantes go to settings and select the app you're working on, check if there's an allow tracking button. Also it takes a while for events to be sent to facebook, about 20 minutes or so

**Comment by jpiabrantes** [comment]
@faithomotoso There's an allow tracking button, and it's on! I am testing the facebook events as it is explained [here](https://business.facebook.com/business/help/2040882565969969?id=1205376682832142) they say events should appear within 30 secs.

**Comment by faithomotoso** [comment]
@jpiabrantes Okay, that part never worked for me, probably because of SKAdAPI on iOS 14.5. But wait a while, should show up in the main events.

**Comment by jpiabrantes** [comment]
@faithomotoso One event is getting through (the View Content), however, it does not show the parameters I've sent. The other events don't even appear on the list. Any ideas?

**Comment by faithomotoso** [comment]
@jpiabrantes Confirm if the time for the events is `x minutes ago` if it is, it'll show up. SKAdAPI delays the delivery of events to Facebook.

**Comment by jpiabrantes** [comment]
@faithomotoso I've just tried the real-time events test with Android. No events are shown too.

**Comment by faithomotoso** [comment]
@jpiabrantes Do you mind sharing how you implemented it?

**Comment by AntonLT** [comment]
@faithomotoso Automatically logged events are working in your setup?

**Comment by faithomotoso** [comment]
@AntonLT yes. App installs and launch gets logged.

**Comment by AntonLT** [comment]
@faithomotoso Please, describe what you have done so it's working

**Comment by faithomotoso** [comment]
@AntonLT https://github.com/oddbit/flutter_facebook_app_events/issues/113#issuecomment-875695491

**Comment by AntonLT** [comment]
@faithomotoso Thank you! I meant what steps you have done prior to the moment of requesting tracking permission. It would help me much.

**Comment by faithomotoso** [comment]
@AntonLT I followed the docs to setup, added the required keys in `info.plist` and initialized in `AppDelegate.swift` with 
```
ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
Settings.setAdvertiserTrackingEnabled(true) // Not sure if this is required
```
remember to import `FBSDKCoreKit` in `AppDelegate.swift`

**Comment by AntonLT** [comment]
@faithomotoso Thank you! What have you entered in CLIENT-TOKEN? Did you get the token somewhere?

**Comment by faithomotoso** [comment]
@AntonLT yes I did. Forgot about that. You'll find it under advanced settings.

**Comment by jpiabrantes** [comment]
> @AntonLT yes I did. Forgot about that. You'll find it under advanced settings.

This solved my problem! YAAAAY 
Thank you!

**Comment by faithomotoso** [comment]
@jpiabrantes Good to hear! Yeah was trying a lot of things with `AppDelegate.swift`, not sure if it was needed or not.

**Comment by AntonLT** [comment]
Oh, I have done everything, but automatically logged events don't work and only for ios...

**Comment by faithomotoso** [comment]
@AntonLT Please confirm if there's an `Enable tracking` options under settings for your app in iOS

**Comment by AntonLT** [comment]
@faithomotoso, yeah, there are 😔

**Comment by faithomotoso** [comment]
@AntonLT in `info.plist` add 
```
<key>FacebookAutoLogAppEventsEnabled</key>
<true/>
```

**Comment by AntonLT** [comment]
OMG, it's working! But there are no app install logs. Interesting is it even possible to check it without app store =)
Thank you so much, @faithomotoso.

**Comment by jpiabrantes** [comment]
> @AntonLT in `info.plist` add
> 
> ```
> <key>FacebookAutoLogAppEventsEnabled</key>
> <true/>
> ```

I don't have this on my `info.plist` and I am getting the automatic logged events. There is a lot of art in getting this to work 😂

**Comment by hahai96** [comment]
@jpiabrantes @faithomotoso What version are you using? Events are not logged on IOS, even though I have fully configured.

**Comment by hahai96** [comment]
![image](https://user-images.githubusercontent.com/23280338/126465945-bec23f92-6978-40a2-8e58-433b0609800d.png)

**Comment by jpiabrantes** [comment]
I am on 0.11.2.

I don't have the LSApplicationQueriesSchemes.

**Comment by hahai96** [comment]
![image](https://user-images.githubusercontent.com/23280338/126477077-a32c10b5-ef26-4080-9f6c-3bc408ada6ef.png)

**Comment by hahai96** [comment]
@jpiabrantes Do you need any special configuration?

**Comment by faithomotoso** [comment]
@hahai96 Can you check under settings if your app has the `Enable tracking` option?

**Comment by armandojimenez** [comment]
Any of the stuff mentioned here does not work for me

**Comment by jenkliu** [comment]
I added the app_tracking_transparency library and made sure I have "Enable tracking" on in Settings. 

I am getting some Purchase events in my Facebook ads dashboard, however my analytics dashboard shows 5-6x more Purchase events than that.

Is this because a user needs to tap "Allow tracking" on the dialogue in order for any event of theirs to be logged?  

I read [here](https://commonthreadco.com/blogs/coachs-corner/facebook-ads-ios-14-changes-affect-ecommerce) that Facebook will still track the top-priority event (Purchases) for users who opt out of tracking, but am not sure if I'm missing something.

@jpiabrantes @faithomotoso @AntonLT are you tracking Purchase events? If so, can you clarify if you are receiving ALL Purchase events or only those for users who explicitly opt in to tracking? Thank you!

**Comment by faithomotoso** [comment]
@jenkliu I'm not tracking purchase events. I think users have to allow tracking before anything is sent to facebook.

**Comment by DennisAlund** [comment]
I will convert this to a discussion, as it seems to be a very relevant discussion with good information for future troubleshooting. But it doesn't seem to be an issue to be fixed in the plugin, as I understand from the thread.
