### ISSUE TITLE
not compatible with flutter_facebook_auth on iOS

### ISSUE THREAD

**Issue by FetFrumos** [oddbit/flutter_facebook_app_events#114]
I use flutter_facebook_auth and flutter_facebook_app_events in my app. I run 'pod install(update)' for iOS and get error:

         ` [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
       In Podfile:
       facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 9.1.0)

    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 2.0.0, which depends on
      FBSDKCoreKit (~> 11.0.0) `
      
      

 how to fix it?

**Comment by FetFrumos** [comment]
Any news? It is important

**Comment by DennisAlund** [comment]
Hey, thanks for getting involved.

Please provide full context with `flutter doctor --verbose` and according to issue report template as described in the RAEDME: https://github.com/oddbit/flutter_facebook_app_events#reporting-bugs-and-issues

**Comment by slorop41314** [comment]
HI @DennisAlund , do you guys plan on upgrading the ios fbsdk to 11 ?
Or merge this pull request? https://github.com/oddbit/flutter_facebook_app_events/pull/108

btw, thanks for the package

**Comment by DennisAlund** [comment]
Fixed in `0.13` (see commit 7799a4dfd9caaef4c41a87eecbb525bcce0f1249)
