### ISSUE TITLE
Upgrading Facebook SDK for iOS to 11.0.1

### ISSUE THREAD

**Issue by knightowlRaising** [oddbit/flutter_facebook_app_events#115]
Please upgrade the iOS Facebook SDK version to 11.0.1 & Android to v8.2.0

**Comment by FetFrumos** [comment]
Any news? It is important

**Comment by davidcz95** [comment]
Any news?

**Comment by Shahmirzali-Huseynov** [comment]
any progress ?

**Comment by DennisAlund** [comment]
Fixed in `0.13` (see commit 7799a4dfd9caaef4c41a87eecbb525bcce0f1249)
