### ISSUE TITLE
Upgrading Facebook SDK for iOS to 11.1.0

### ISSUE THREAD

**Issue by YuliyaKarima** [oddbit/flutter_facebook_app_events#121]
Please upgrade the iOS Facebook SDK version to 11.1.0
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
* Output from `flutter doctor`
* Operating System and version:

**Comment by DennisAlund** [comment]
Fixed in `0.13` (see commit 7799a4dfd9caaef4c41a87eecbb525bcce0f1249)
