### ISSUE TITLE
ios custom event no record

### ISSUE THREAD

**Issue by tudosxxx** [oddbit/flutter_facebook_app_events#140]
`
<key>CFBundleURLTypes</key>
<array>
  <dict>
  <key>CFBundleURLSchemes</key>
  <array>
    <string>fb[APP_ID]</string>
  </array>
  </dict>
</array>
<key>FacebookAppID</key>
<string>[APP_ID]</string>
<key>FacebookDisplayName</key>
<string>[APP_NAME]</string>`
I configured this and modified the appid. Installation and activities can be seen in the fb statistics, but there is no record of custom events.

**Comment by mdhossentanbir** [comment]
I am also having the same issue. Android working fine. but iOS is no event in facebook

**Comment by tudosxxx** [comment]
> 我也有同样的问题。安卓工作正常。但 iOS 不是 facebook 中的事件

IOS, I heard that there are 150 installations before an event can happen, and I can’t do it with Android. . . There are only default events, no custom event statistics area

**Comment by DennisAlund** [comment]
Seems to be duplicated by #145 that has more info. Will follow up there.
