### ISSUE TITLE
App events not received in iOS.

### ISSUE THREAD

**Issue by Young-Slim-Jim** [oddbit/flutter_facebook_app_events#148]
Currently, I am using this package to send custom events. On Android devices everything is working fine. I see events in the overview and in event testing tab on the Facebook event dashboard. However, I do not see anything when I am running the app on a iOS Device. In my Facebook dashboard no error are shown and it is telling me, that everything is up to date. 

## Possible Solution
I saw that a lot of people are struggling with iOS Device on sending out the events on iOS 14.5 and higher. I tried everything that these people where suggestion, but I can not try everything since some of the suggested fixes are only possible to do for people who use Swift / native development. Tracking for this iOS devices was allowed, but it did not change anything.

## Steps to Reproduce (for bugs)

1. modifie info.plist file as described on pub dev
2. activate app in Facebook 
3. place a custom app event and trigger it with user behavior. 

## Your Environment
* no errors for flutter doctor
* Operating System and version: iOS 14.5
* package version: 13.5
* flutter version: 2.5.2

**Comment by Young-Slim-Jim** [comment]
Update: I just tested the package on a iOS 13.7 simulator and it worked. I saw in the events manager that my device was detected and that all of the auto logged events where collected.

**Comment by DennisAlund** [comment]
> Update: I just tested the package on a iOS 13.7 simulator and it worked. I saw in the events manager that my device was detected and that all of the auto logged events where collected.

Would be happy to get some insights from a iOS developer who has a finger on the pulse on what happened in the jump from v13-14 for iOS and how it might have impacted the Facebook SDK.

Is it a bug on the plugin or some restrictions of the OS that prevents the Facebook SDK to work differently.

Would be happy to learn more abou this.

**Comment by DennisAlund** [comment]
Thanks @furkanvatandas that seems to be a good lead. 

@Young-Slim-Jim can you confirm if you have enabled the advertisement tracking using this method already? Or if you enable it can you confirm that the events start showing up. Would be great to know for future troubleshooting 🙏 

https://github.com/oddbit/flutter_facebook_app_events/blob/1d4af856774d8652abde7712853b20f7a75b78dd/lib/facebook_app_events.dart#L261-L269

**Comment by Young-Slim-Jim** [comment]
Thank you for that hint. That actually solved the problem for me. Before I opened the ticket, I tried setting that flag in another way, which didn't work out, which is why I did not take it into consideration.
