### ISSUE TITLE
[Bug]: SDK not compatible with flutter_facebook_auth on IOS

### ISSUE THREAD

**Issue by slorop41314** [oddbit/flutter_facebook_app_events#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
      In Podfile:
        facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
          FBSDKCoreKit (~> 12.0)
        flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 3.5.3, which depends on
          FBSDKCoreKit (~> 12.0.2)

### Expected Behavior

iOS Sdk version = 12.0.2

### Platform

iOS

### Flutter Doctor

```shell
Flutter (Channel stable, 2.5.1, on macOS 11.2.3 20D91 darwin-arm, locale
    en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
```

**Comment by DennisAlund** [comment]
What is the issue that should be fixed?

You checked the box for having searched for similar issues, but your issue doesn't state how this is different or not answered by the other 12 issues that mention `flutter_facebook_auth`

https://github.com/oddbit/flutter_facebook_app_events/search?q=flutter_facebook_auth&type=issues

Closing for low quality report of information. Please make more effort in describing what help you are seeking.

**Comment by slorop41314** [comment]
Hii, its different for the version. 
Current latest sdk used by facebook_auth are 12.0.2, but facebook_app_events use 12.0 .
Would be great if can update to 12.0.2

Thanks

**Comment by DennisAlund** [comment]
https://github.com/oddbit/flutter_facebook_app_events/blob/1d4af856774d8652abde7712853b20f7a75b78dd/ios/facebook_app_events.podspec#L15

`12.0` means `12.0.x` which includes `12.0.2`
https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions

**Comment by slorop41314** [comment]
thanks, fixed.

run 
pod install --repo-update
or
arch -x86_64 pod install --repo-update 

in ios directory.
