### ISSUE TITLE
[Bug]: iOS Compilation error with version 0.14.3

### ISSUE THREAD

**Issue by zitob9** [oddbit/flutter_facebook_app_events#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i update to 0.14.3, i clean flutter and iOS

When building the project, I'm getting the following error messages:

Cannot convert value of type '[AppEvents.ParameterName : Any]' to expected argument type '[String : Any]'

Cannot convert value of type '[AppEvents.ParameterName : Any]' to expected argument type '[String : Any]'

problem is on this code: (SwiftFacebookAppEventsPlugin)

`  private func handleLogEvent(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        let arguments = call.arguments as? [String: Any] ?? [String: Any]()
        let eventName = arguments["name"] as! String
        let parameters = arguments["parameters"] as? [AppEvents.ParameterName: Any] ?? [AppEvents.ParameterName: Any]()
        if arguments["_valueToSum"] != nil && !(arguments["_valueToSum"] is NSNull) {
            let valueToDouble = arguments["_valueToSum"] as! Double
            AppEvents.logEvent(AppEvents.Name(eventName), valueToSum: valueToDouble, parameters: parameters)
        } else {
            AppEvents.logEvent(AppEvents.Name(eventName), parameters: parameters)
        }
`

### Expected Behavior

Build should be successful.

### Steps To Reproduce

Using Xcode 13.1, flutter version 2.2.3:

### Platform

iOS

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.6 20G165 darwin-x64, locale en-FR)
    • Flutter version 2.2.3 at /Users/mac/development/flutter
    • Framework revision f4abaa0735 (4 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

**Comment by millerovv** [comment]
Hi! I encountered the same problem yesterday. This is confusing, that is the same error as mentioned in (https://github.com/oddbit/flutter_facebook_app_events/issues/156), isn't it? Although v0.14.3 supposed to fix it?

**Comment by zitob9** [comment]
> Hi! I encountered the same problem yesterday. This is confusing, that is the same error as mentioned in (#156), isn't it? Although v0.14.3 was supposed to fix it?

I use this this version but the problem is still

**Comment by tamoyal** [comment]
Yes I also have this issue. Is there any work around?

**Comment by zitob9** [comment]
i don't find nothing about that

> Yes I also have this issue. Is there any work around?

**Comment by tamoyal** [comment]
I got it to work by bumping the version of FBSDKCoreKit

Here is the PR - https://github.com/oddbit/flutter_facebook_app_events/pull/160

**Comment by zitob9** [comment]
any updates about this case?

**Comment by DennisAlund** [comment]
Yes, comments waiting in PR https://github.com/oddbit/flutter_facebook_app_events/pull/160#issuecomment-962537027

**Comment by zitob9** [comment]
you can check the error here: https://ibb.co/DKp4MXr

**Comment by zitob9** [comment]
@DennisAlund Is there a solution because I can not publish the application?

**Comment by DennisAlund** [comment]
@zitob9 you can post screenshots and logs here in Github so it's easier to review: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by deepsan98** [comment]
Hi, I had installed both versions 0.14.3 and 0.14.5, but I found exactly the same issue mentioned above.
I am using flutter version 2.2.2.

To solve the problem, I had to bump to change in my pod file from:

(the following was installing FBSDKCoreKit 12.1.0)

`
 pod 'FBSDKCoreKit'
`

(it was installing FBSDKCoreKit 12.1.0),  to this.

`
 pod 'FBSDKCoreKit', '~> 12.0.0'
`

This change made my code compile correctly.

**Comment by zitob9** [comment]
@DennisAlund its works now when I use v 0.14.5

**Comment by devibrahimkarahan** [comment]
@DennisAlund 
Im using 0.14.5, still same

Error:
Cannot convert value of type '[String : Any]' to expected argument type '[AppEvents.ParameterName : Any]'

![image](https://user-images.githubusercontent.com/7039967/142445494-4f20515a-2a80-4437-b488-65a4536892ed.png)

**Comment by kotchuprik** [comment]
the same issue for me

**Comment by zitob9** [comment]
clean your data.

you can use this command on your folder:

flutter clean \ && rm ios/Podfile.lock pubspec.lock \ && rm -rf ios/Pods ios/Runner.xcworkspace

**Comment by OneXeor** [comment]
@DennisAlund Are you kidding? :) 
This issue is pretty simple.
There were this one PR -> [#157](https://github.com/oddbit/flutter_facebook_app_events/pull/157/files)
Which fixed this issue but @yanivshaked forgot to change the `FBSDKCoreKit` version to `'~> 12.1.0'` in the `flutter_facebook_app_events.pospec`  file
Then @DennisAlund had reverted [PR#157](https://github.com/oddbit/flutter_facebook_app_events/pull/157/files) in his [PR#163](https://github.com/oddbit/flutter_facebook_app_events/pull/163/files).

So the thing is that to solve this forever we need to change the version of the `FBSDKCoreKit` to `'~> 12.1.0'` and apply changes from [PR#157](https://github.com/oddbit/flutter_facebook_app_events/pull/157/files)

In general lake a look at this PR [#170](https://github.com/oddbit/flutter_facebook_app_events/pull/170)

**Comment by DennisAlund** [comment]
@OneXeor why do you think I am kidding? What's the joke?

**Comment by OneXeor** [comment]
@DennisAlund because you could solve it 16 days ago in [PR#157](https://github.com/oddbit/flutter_facebook_app_events/pull/157/files), once and for all. But 8 days ago in [PR#163](https://github.com/oddbit/flutter_facebook_app_events/pull/163/files), to my mind, you decided to play a joke cause you reverted the fix.

**Comment by RicardoRB** [comment]
I am having "isAdvertiserIDCollectionEnabled", does this PR fix it?

**Comment by DennisAlund** [comment]
> (the following was installing FBSDKCoreKit 12.1.0)
> 
> `pod 'FBSDKCoreKit'`
> 
> (it was installing FBSDKCoreKit 12.1.0), to this.
> 
> `pod 'FBSDKCoreKit', '~> 12.0.0'`

@deepsan98 I'm interested to learn more why FBSDKCoreKit resolved to `12.0.0` when declared as 
https://github.com/oddbit/flutter_facebook_app_events/blob/901c875c0444fa7d2c83492a18767f59b1f4d2cd/ios/facebook_app_events.podspec#L16

According to [cocoapods documentation](https://guides.cocoapods.org/using/the-podfile.html) it should have resolved to `12.1` ... 

![image](https://user-images.githubusercontent.com/2051607/142958012-6179b9d7-4f1f-494f-a6a9-a2291c3dcfdf.png)

**Comment by DennisAlund** [comment]
See if [`v0.14.6`](https://pub.dev/packages/facebook_app_events/changelog#0146) is fixing problems

**Comment by zitob9** [comment]
yes its work for me, thank so much bro.

**Comment by furkanvatandas** [comment]
Still not compile for me with v0.14.6

<img width="1405" alt="Screen Shot 2021-11-23 at 10 34 17" src="https://user-images.githubusercontent.com/27723153/142985773-c0ceda00-25e8-4766-8b77-b359408aa7ca.png">

**Comment by DennisAlund** [comment]
@furkanvatandas please provide output from `flutter doctor` and all other potential information if you want to have a chance for us to help you with your setup.

**Comment by furkanvatandas** [comment]
@DennisAlund sure

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-TR)
    • Flutter version 2.5.3 at /Users/furkan.vatandas/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/furkan.vatandas/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0
```

**Comment by OneXeor** [comment]
@DennisAlund, I am guessing that my PR could fix that :) 
I do not understand why you want to use the `12.0.0` version of FBSDKCoreKit, which will not work with AppEvents.ParameterName? Or I don’t understand something sacred?

**Comment by wwnOddbit** [comment]
@OneXeor Please have a look at my comment on #160 in regard to CocoaPods optimistic operator. I'd love to figure out whether I'm missing something here.

**Comment by suryaoddbit** [comment]
Hi @furkanvatandas have you try update pod repo first?
Or please do this step first.
1. delete pubspec.lock file
2. run pod repo update
3. run pod install

**Comment by wwnOddbit** [comment]
@kotchuprik @furkanvatandas Basically, we're trying to figure out why FBSDKCoreKit is not updating to the latest version (12.1.0) while the optimistic operator `~> 12.0` in Podfile should have handled that. May I suggest the following:

1. run `pod outdated` to check whether FBSDKCoreKit is on the latest version (12.1.0). If it's already on 12.1.0, then unfortunately we're having a different problem. 😅
2. run `pod update FBSDKCoreKit` to update to the latest version.
3. run `pod outdated` again to make sure it is updated to 12.1.0. If it's not, please try to start with a clean environment as suggested by @zitob9 and continue w/ steps posted by @suryaoddbit.

https://github.com/oddbit/flutter_facebook_app_events/issues/159#issuecomment-973013310
> clean your data.
> 
> you can use this command on your folder:
> 
> flutter clean \ && rm ios/Podfile.lock pubspec.lock \ && rm -rf ios/Pods ios/Runner.xcworkspace

https://github.com/oddbit/flutter_facebook_app_events/issues/159#issuecomment-977391671
> 1. delete pubspec.lock file
> 2. run pod repo update
> 3. run pod install

I'd appreciate it if you could also provide your feedback after trying out the steps above. It will help us provide the best solution for the community on similar problems. Good luck.

**Comment by bhanuka96** [comment]
> Still not compile for me with v0.14.6
> 
> <img alt="Screen Shot 2021-11-23 at 10 34 17" width="1405" src="https://user-images.githubusercontent.com/27723153/142985773-c0ceda00-25e8-4766-8b77-b359408aa7ca.png">

same issues

**Comment by OneXeor** [comment]
Anyone checked #173 PR? Because I have some doubts how can it work, it uses `AppEvents.ParameterName.RawValue` whereas `AppEvents.ParameterName` is needed for parameters in the`AppEvents.logEvent` method :)

> @OneXeor Please have a look at my comment on #160 in regard to CocoaPods optimistic operator. I'd love to figure out whether I'm missing something here.

I saw your comment but still It makes no sense because `12.0.0` can't use `[AppEvents.ParameterName:Any]` and `12.1.0` can't use `[String:Any]`

**Comment by furkanvatandas** [comment]
> Hi @furkanvatandas have you try update pod repo first? Or please do this step first.
> 
> 1. delete pubspec.lock file
> 2. run pod repo update
> 3. run pod install

I try your all command and also this commands
```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install
```

Still not compile

**Comment by ferysyukur** [comment]
hi @furkanvatandas , do you use mac m1 ?
If yes, please try this way.
```
sudo arch -x86_64 gem install ffi
sudo arch -x86_64 pod clean
sudo arch -x86_64 pod install
```

make sure you use this command after you use `pod deintegrate` to rebuild all generated file was deleted.
```
flutter packages get
/// or
flutter build
```

Let me know if this way is not working.

**Comment by devibrahimkarahan** [comment]
0.14.7 working 👍  (M1 - mac mini)
