### ISSUE TITLE
[Bug]: Flutter app rejected by Apple due to advertising identifier in app category for kids

### ISSUE THREAD

**Issue by LugonjaAleksandar** [oddbit/flutter_facebook_app_events#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My app needs to use facebook_app_events in order to track app installs when promoting my app on Facebook and IG. The problem is, Apple is not allowing me to publish the app in the kinds category and shows a breach in the guidelines:

```
Guideline 1.3 - Safety - Kids Category

We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties. Specifically:

Your app includes third-party analytics or third-party advertising with the ability to collect, transmit or share identifiable information, including, for example, IDFA. We found that your app references the ASIdentifierManager API, which provides access to a user's IDFA, in the following location(s) in your binary:
• Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit

It would be appropriate to remove all instances of “ASIdentifierManager” from your app, even if they are not utilized in your app's functionality.

Next Steps

To resolve this issue, please remove this functionality or revise your app so that no personally identifiable information or device information is sent to third parties.
```

I need to keep track of my campaigns, so I can't avoid using the FB SDK. But I have no idea how to pass the review process if it's as strict as it is...any ideas?

### Expected Behavior

App is approved by Apple for their Kids category.

### Steps To Reproduce

1. Submit app that is using this plugin to Apple review

### Platform

iOS

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-RS)
    • Flutter version 2.5.3 at /Users/aleksandarlugonja/Desktop/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/aleksandarlugonja/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

**Comment by paulw11** [comment]
I would say you need [this](https://github.com/facebook/facebook-ios-sdk/issues/1637) to be resolved

**Comment by DennisAlund** [comment]
It seems you have issues with trying to pass an apple review against their terms of services. 

This is an independently developed, open source plugin. We are not affiliated with Facebook or Apple.

**Comment by LugonjaAleksandar** [comment]
@DennisAlund  this is not a user error. This is a Facebook plugin error that has an identifier inside that is not allowed by Apple review guidelines. Being a part of a Facebook is not relevant here, only that by using this plugin you are not allowed as a developer to post in one major App Store category of the apps and games due to this bug in the FB SDK.

**Comment by DennisAlund** [comment]
Okay, I just don't know what you are suggesting? As @paulw11 suggested, it seems to be a request to be made to the facebook team.

I'd be happy to learn more how this plugin could do a workaround. But as far as I understand the problem reported, it is related to the Facebook SDK that is being utilized by this plugin.

As I mentioned, we don't maintain the native SDKs. Any issues in the underlying SDK is inherently also an issue with this plugin.

**Comment by LugonjaAleksandar** [comment]
I've researched a bit the class inside the SDK and there are some "settings" that can be applied in order to disable this identifier. At least it seems like it inside `FBSDKAppEventsUtility` with `isAdvertiserIDCollectionEnabled` flag. If that is something that can be passed to the SDK itself from a config object command from Flutter, that might do the trick.

**Comment by DennisAlund** [comment]
Thanks for helping to clarify. I am looking into adding this as a parameter switch...

**Comment by paulw11** [comment]
You can try this flag but I don’t think it will help. It is checked at runtime. Apple checks to see if there is any reference to the advertising identifier in the compiled code, which there still will be.

**Comment by DennisAlund** [comment]
There is a flag added to set that option now. You can see if it works as you expect. But as if that flag doesn't change the app review status/acceptance, then the problem is deeper than that and would need to be fixed on SDK level.

Change this optional parameter to `false` to get what you wanted to accomplish @LugonjaAleksandar 
https://github.com/oddbit/flutter_facebook_app_events/blob/4a62f588c849ed47a679f6a50f11a8d49f5a2132/lib/facebook_app_events.dart#L265

It is changing the settings in the Facebook SDK
https://github.com/oddbit/flutter_facebook_app_events/blob/4a62f588c849ed47a679f6a50f11a8d49f5a2132/ios/Classes/SwiftFacebookAppEventsPlugin.swift#L151
