### ISSUE TITLE
[Bug]: Cannot compile for iOS due to error "Undefined symbols for architecture arm64"

### ISSUE THREAD

**Issue by jbx1** [oddbit/flutter_facebook_app_events#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding facebook_app_events to our app, we are getting these warnings and errors. 

```
ld: warning: argument missing after -rpath
    ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
    ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
    ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
    ld: warning: Could not find or use auto-linked library 'stdc++'
    ld: warning: Could not find or use auto-linked framework 'AVFAudio'
    ld: warning: Could not find or use auto-linked framework 'DataDetection'
    Undefined symbols for architecture x86_64:
      "_swift_FORCE_LOAD$_swiftDataDetection", referenced from:
          _swift_FORCE_LOAD$swiftDataDetection$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
         (maybe you meant: _swift_FORCE_LOAD$swiftDataDetection$_FBAudienceNetwork)
      "OBJC_CLASS$_SKAdImpression", referenced from:
          objc-class-ref in FBAudienceNetwork(FBAdSKAdNetworkManager.m.o)
      "_swift_FORCE_LOAD$_swiftFileProvider", referenced from:
          _swift_FORCE_LOAD$swiftFileProvider$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
         (maybe you meant: _swift_FORCE_LOAD$swiftFileProvider$_FBAudienceNetwork)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When we remove facebook_app_events from pubspec.yaml the project compiles just fine. 

### Expected Behavior

Adding the flutter facebook_app_events dependency should compile successfully for iOS.

### Steps To Reproduce

1. Add facebook_app_events: 0.14.5 to the pubspec.yaml
2. Build the project for iOS using XCode.

### Platform

iOS

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale
    en-MT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] Connected device (2 available)
```

**Comment by JohnCoppa** [comment]
I'm also seeing this error. After trying to get this package working with my full app, I created a fresh flutter app (flutter create) and added facebook_app_events as the only extra package in my pubspec file. When trying to compile with the fresh flutter app and this package, I still get this error.

Running on a Mac M1

Flutter Doctor Output:

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.2.3 20D91 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

• No issues found!`

**Comment by DennisAlund** [comment]
Thank you for all the information. It will be useful for context in troubleshooting. Me or someone else here in the office will get back shortly.

**Comment by ferysyukur** [comment]
hai @jbx1 dan @JohnCoppa, saya membuat proyek baru dan mencoba mereproduksi kesalahan ini, tetapi masih belum dapat mereproduksi kesalahan ini. Anda dapat mencoba memperbarui pod Anda menggunakan perintah ini. Regarding those of you who use mac m1.
`
sudo arch -x86_64 gem install ffi
sudo arch -x86_64 pod clean
sudo arch -x86_64 pemasangan pod
`

**Comment by codemewell** [comment]
I do have the same error using 0.14.8 :/

**Comment by hieugia3030** [comment]
So is there any solution to this, i still get this error
