### ISSUE TITLE
[Bug]: ios comple error

### ISSUE THREAD

**Issue by hatemragab** [oddbit/flutter_facebook_app_events#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Undefined symbol: __swift_FORCE_LOAD_$_swiftDataDetection

### Expected Behavior

1- Undefined symbol: __swift_FORCE_LOAD_$_swiftDataDetection
2- Undefined symbol: _OBJC_CLASS_$_SKAdImpression
3- Undefined symbol: __swift_FORCE_LOAD_$_swiftFileProvider

Ld /Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/Runner.app/Runner normal (in target 'Runner' from project 'Runner')
    cd /Users/hatem/flutter_projects/syntax_projects/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios11.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -L/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk/usr/lib/swift -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/BSImagePicker -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/DKImagePickerController -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/DKPhotoGallery -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/FMDB -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/FirebaseAuth -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/FirebaseCore -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/FirebaseCoreDiagnostics -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/FirebaseDynamicLinks -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/FirebaseInstallations -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/FirebaseMessaging -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/GoogleDataTransport -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/GoogleUtilities -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/PromisesObjC -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/Reachability -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/SDWebImage -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/SwiftyGif -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/Toast -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/audioplayers -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/connectivity -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/facebook_app_events -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/file_picker -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/firebase_auth -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/firebase_core -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/firebase_dynamic_links -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/firebase_messaging -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/flutter_local_notifications -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/flutter_native_image -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/flutter_secure_storage -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/flutter_video_info -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/fluttertoast -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/geolocator_apple -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/google_maps_flutter -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/image_picker -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/libwebp -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/location -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/multi_image_picker2 -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/nanopb -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/open_file -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/path_provider_ios -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/permission_handler -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/record -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/share_plus -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/shared_preferences_ios -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/sqflite -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/uni_links -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/url_launcher -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/video_player -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/video_thumbnail -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/wakelock -F/Users/hatem/flutter_projects/syntax_projects/ios/Pods/FBAEMKit/XCFrameworks -F/Users/hatem/flutter_projects/syntax_projects/ios/Pods/FBAudienceNetwork/Static -F/Users/hatem/flutter_projects/syntax_projects/ios/Pods/FBSDKCoreKit/XCFrameworks -F/Users/hatem/flutter_projects/syntax_projects/ios/Pods/FBSDKCoreKit_Basics/XCFrameworks -F/Users/hatem/flutter_projects/syntax_projects/ios/Pods/GoogleMaps/Base/Frameworks -F/Users/hatem/flutter_projects/syntax_projects/ios/Pods/GoogleMaps/Maps/Frameworks -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FBAEMKit -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FBAudienceNetwork -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FBSDKCoreKit -F/Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FBSDKCoreKit_Basics -filelist /Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftmodule -ObjC -lc++ -lsqlite3 -lxml2 -lz -framework AVFoundation -framework AVKit -framework Accelerate -framework AudioToolbox -framework BSImagePicker -framework CoreData -framework CoreGraphics -framework CoreImage -framework CoreLocation -framework CoreMedia -framework CoreTelephony -framework CoreText -framework DKImagePickerController -framework DKPhotoGallery -framework FBAEMKit -framework FBAudienceNetwork -framework FBLPromises -framework FBSDKCoreKit -framework FBSDKCoreKit_Basics -framework FMDB -framework FirebaseAuth -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseDynamicLinks -framework FirebaseInstallations -framework FirebaseMessaging -framework Foundation -framework GLKit -framework GTMSessionFetcher -framework GoogleDataTransport -framework GoogleMaps -framework GoogleMapsBase -framework GoogleMapsCore -framework GoogleUtilities -framework ImageIO -framework Metal -framework OpenGLES -framework Photos -framework QuartzCore -framework Reachability -framework SDWebImage -framework SafariServices -framework Security -framework StoreKit -framework SwiftyGif -framework SystemConfiguration -framework Toast -framework UIKit -framework audioplayers -framework connectivity -framework facebook_app_events -framework file_picker -framework firebase_auth -framework firebase_core -framework firebase_dynamic_links -framework firebase_messaging -framework flutter_local_notifications -framework flutter_native_image -framework flutter_secure_storage -framework flutter_video_info -framework fluttertoast -framework geolocator_apple -framework google_maps_flutter -framework image_picker -framework libwebp -framework location -framework multi_image_picker2 -framework nanopb -framework open_file -framework path_provider_ios -framework permission_handler -framework record -framework share_plus -framework shared_preferences_ios -framework sqflite -framework uni_links -framework url_launcher -framework video_player -framework video_thumbnail -framework wakelock -weak_framework AdSupport -weak_framework CFNetwork -weak_framework CoreMotion -weak_framework CoreTelephony -weak_framework LinkPresentation -weak_framework LocalAuthentication -weak_framework SafariServices -weak_framework SystemConfiguration -weak_framework UserNotifications -weak_framework VideoToolbox -weak_framework WebKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent -framework Pods_Runner -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat -o /Users/hatem/Library/Developer/Xcode/DerivedData/Runner-hkevqgwpnapwuwaixooyiqirtzpq/Build/Products/Debug-iphonesimulator/Runner.app/Runner

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.0.1 20B29 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.2)
[✓] VS Code (version 1.58.2)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by StefanosGiannakis** [comment]
@spiritinlife 💪

**Comment by dwarimaheshwari** [comment]
I am still getting the below error:

Undefined symbol: _swift_FORCE_LOAD$_swiftDataDetection

Is this issue fixed in v0.14.7 or not?

Is there any solution?

**Comment by wwnOddbit** [comment]
@dwarimaheshwari Have you tried the solution proposed by @spiritinlife above?

**Comment by ferysyukur** [comment]
> Try enabling `Always Embed Swift Standard Libraries` <img alt="screenshot" width="865" src="https://user-images.githubusercontent.com/6434983/144624023-ea7316db-3c2b-46ce-a64d-f077a813260d.png">

Hi @dwarimaheshwari , please do like @spiritinlife answer or you can create new file swift like [this link](https://stackoverflow.com/questions/68838863/xcode-build-failure-due-to-undefined-symbol-swift-force-load-swiftfileprovi).
This is issue because the project needs to "Create Bridging Header".
Please let me know if the answer solved your issue.

**Comment by khaiql** [comment]
I'm facing the same issue, tried to enable the build setting, as well as create an empty swift file but didn't work, the same error occurred. What else could I do to fix?

**Comment by pwnywiz** [comment]
> I'm facing the same issue, tried to enable the build setting, as well as create an empty swift file but didn't work, the same error occurred. What else could I do to fix?

Theres one more critical part. You need to update OSX and XCode to the latest version. I was facing the same issue with 'awlays embed swift' enabled, but after updating XCode to 13.1 it worked properly.

**Comment by khaiql** [comment]
Updating XCode indeed helped. Thank you

**Comment by iska9der** [comment]
What if i cant update to newer version of Xcode? Im stuck at 12.4 because of old Mac Mini
