### ISSUE TITLE
[Bug]: Pod install: CocoaPods could not find compatible versions for pod 

### ISSUE THREAD

**Issue by zitob9** [oddbit/flutter_facebook_app_events#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My Flutter app is not working on my iOS device, while it's working perfectly on android. I'm getting an error on pod install

[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
```
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 12.1.0)
    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 3.5.3, which depends on
      FBSDKCoreKit (~> 12.0.2)
```

### Expected Behavior

```
MacBook-Pro ios % pod install
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_analytics: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 12.1.0)

    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 3.5.3, which depends on
      FBSDKCoreKit (~> 12.0.2)
```

### Steps To Reproduce

1. cd ios
2. pod update or pod install
3. error

### Platform

iOS

### Flutter Doctor

```shell
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.6.1 20G224 darwin-x64, locale en-FR)
    • Flutter version 2.2.3 at /Users/mac/development/flutter
    • Framework revision f4abaa0735 (5 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.55
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

**Comment by pwnywiz** [comment]
If you need a temporary fix for this, you can replace the facebook_auth pub version with a direct link to the author's github project. The SDK there is at 12.1 as well

**Comment by zitob9** [comment]
> If you need a temporary fix for this, you can replace the facebook_auth pub version with a direct link to the author's github project. The SDK there is at 12.1 as well

thanks you bro, how can do that

**Comment by pwnywiz** [comment]
Instead of using
`flutter_facebook_auth: ^3.5.6`
you can use
`flutter_facebook_auth:
    git:
      url: https://github.com/darwin-morocho/flutter-facebook-auth
      ref: master
      path: facebook_auth`

However this might cause another [issue](https://github.com/oddbit/flutter_facebook_app_events/issues/176) thats currently open and im facing as well

**Comment by zitob9** [comment]
@pwnywiz thank you so much for your help.

flutter_facebook_auth solve the problem with the last update.

**Comment by ferysyukur** [comment]
> Instead of using `flutter_facebook_auth: ^3.5.6` you can use `flutter_facebook_auth: git: url: https://github.com/darwin-morocho/flutter-facebook-auth ref: master path: facebook_auth`
> 
> However this might cause another [issue](https://github.com/oddbit/flutter_facebook_app_events/issues/176) thats currently open and im facing as well

Hi @zitob9 , this issue is because version conflict FBSDKCoreKit. You can use this way or you can use facebook_app_event with this version 0.14.6. Because this version still get FBSDKCoreKit (~> 12.0.2).
If this version solve your problem. Let me know. So we can close this issue.

**Comment by ruizyi** [comment]
flutter-facebook-auth updated with proper version you better check it

**Comment by zitob9** [comment]
thanks guys

**Comment by kapil708** [comment]
> > Instead of using `flutter_facebook_auth: ^3.5.6` you can use `flutter_facebook_auth: git: url: https://github.com/darwin-morocho/flutter-facebook-auth ref: master path: facebook_auth`
> > However this might cause another [issue](https://github.com/oddbit/flutter_facebook_app_events/issues/176) thats currently open and im facing as well
> 
> Hi @zitob9 , this issue is because version conflict FBSDKCoreKit. You can use this way or you can use facebook_app_event with this version 0.14.6. Because this version still get FBSDKCoreKit (~> 12.0.2). If this version solve your problem. Let me know. So we can close this issue.

This works for me `facebook_app_events: ^0.14.6`
