### ISSUE TITLE
[Bug]: IOS compilation error with parameters

### ISSUE THREAD

**Issue by venkatgsvs** [oddbit/flutter_facebook_app_events#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While building i am facing below error

Cannot convert value of type '[AppEvents.ParameterName.RawValue : Any]' (aka 'Dictionary<String, Any>') to expected argument type '[AppEvents.ParameterName : Any]'

### Expected Behavior

should work even if adding custom parameters

### Platform

iOS

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.6 20G165 darwin-arm, locale
    en-IN)
    • Flutter version 2.2.3 
    • Framework revision f4abaa0735 (5 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK 
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build
      11.0.11+9-LTS-194)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by ferysyukur** [comment]
Hi @venkatgsvs , this issue was solved with version 0.14.7. Please use this version first. Let me know if my answer solved your issue.

**Comment by venkatasubramanyam** [comment]
I am facing this issue in 0.14.7 only., when i remove Rawvalue then started working

**Comment by ferysyukur** [comment]
Ah i see. Please do `pod update` first. because we have updated this issue.

If you use macbook m1. Please do like this.
```
sudo arch -x86_64 gem install ffi
sudo arch -x86_64 pod clean
sudo arch -x86_64 pod install
```

**Comment by ferysyukur** [comment]
hi @venkatgsvs and @venkatasubramanyam, do you have any result about this issue ? If no, I'll close this issue.

**Comment by venkatasubramanyam** [comment]
@ferysyukur I done with above steps also, but i fixed this issue by manually removed .Rawvalue from "swiftFacebookAppEventsPlugin" - "handleLogEvent" and got it fixed. This has to be fixed from plugin

**Comment by ferysyukur** [comment]
> Ah i see. Please do `pod update` first. Because we have updated this issue.
> 
> If you use macbook m1. Please do like this.
> 
> ```
> sudo arch -x86_64 gem install ffi
> sudo arch -x86_64 pod clean
> sudo arch -x86_64 pod install
> ```
> 
> Let me know if still not working for you.

please do this way in ios directory.

I close this issue because it's solved and merged in this PR https://github.com/oddbit/flutter_facebook_app_events/pull/174/files.
