### ISSUE TITLE
logAddToCart error

### ISSUE THREAD

**Issue by AbeerMagdyHanafy** [oddbit/flutter_facebook_app_events#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): Failed to handle method call
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.createBundleFromMap(FacebookAppEventsPlugin.kt:196)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleLogEvent(FacebookAppEventsPlugin.kt:100)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:48)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at android.os.MessageQueue.next(MessageQueue.java:336)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at android.os.Looper.loop(Looper.java:174)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[        ] E/MethodChannel#flutter.oddbit.id/facebook_app_events(10043): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[   +5 ms] E/flutter (10043): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
[        ] E/flutter (10043): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.createBundleFromMap(FacebookAppEventsPlugin.kt:196)
[        ] E/flutter (10043): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleLogEvent(FacebookAppEventsPlugin.kt:100)
[        ] E/flutter (10043): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:48)
[        ] E/flutter (10043): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/flutter (10043): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/flutter (10043): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
[        ] E/flutter (10043): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter (10043): 	at android.os.MessageQueue.next(MessageQueue.java:336)
[        ] E/flutter (10043): 	at android.os.Looper.loop(Looper.java:174)
[        ] E/flutter (10043): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[        ] E/flutter (10043): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (10043): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[        ] E/flutter (10043): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[        ] E/flutter (10043): )
[        ] E/flutter (10043): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
[        ] E/flutter (10043): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
[        ] E/flutter (10043): <asynchronous suspension>
[        ] E/flutter (10043): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[        ] E/flutter (10043): #3      FacebookAppEvents.logEvent (package:facebook_app_events/facebook_app_events.dart:81:21)
[        ] E/flutter (10043): #4      FacebookAppEvents.logAddToCart (package:facebook_app_events/facebook_app_events.dart:221:12)
[        ] E/flutter (10043): #5      Analytics.onCustomEvent (package:waffarha/services/analytics.dart:31:37)
[        ] E/flutter (10043): <asynchronous suspension>
[        ] E/flutter (10043): #6      _OfferDetailsPageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:waffarha/ui/home/offers/offer_details/offer_details.dart:1936:92)
[        ] E/flutter (10043): #7      DeviceAndApiSettings.handleApiResponse (package:waffarha/services/device_and_api_settings.dart:410:20)
[        ] E/flutter (10043): #8      _OfferDetailsPageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:waffarha/ui/home/offers/offer_details/offer_details.dart:1926:68)
[        ] E/flutter (10043): #9      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] E/flutter (10043): #10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter (10043): #11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] E/flutter (10043): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] E/flutter (10043): #13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] E/flutter (10043): #14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] E/flutter (10043): #15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ] E/flutter (10043): #16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ] E/flutter (10043): #17     CartBloc.addToCart (package:waffarha/blocs/cart_bloc.dart)
[        ] E/flutter (10043): <asynchronous suspension>
[        ] E/flutter (10043): #18     _OfferDetailsPageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:waffarha/ui/home/offers/offer_details/offer_details.dart:1920:66)
[        ] E/flutter (10043): #19     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] E/flutter (10043): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter (10043): #21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] E/flutter (10043): #22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] E/flutter (10043): #23     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] E/flutter (10043): #24     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] E/flutter (10043): #25     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ] E/flutter (10043): #26     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] E/flutter (10043): #27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter (10043): #28     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] E/flutter (10043): #29

### Expected Behavior

appear event standard AddToCart in facebook events but not working yet

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.1348], locale en-GB)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (10 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mzgzg\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\mzgzg\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    • Flutter plugin version 41.1.1
    • Dart plugin version 191.8593
[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mzgzg\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0
[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
! Doctor found issues in 1 category.
```

**Comment by DennisAlund** [comment]
Please provide sample code to reproduce the problem. See the provided section "Steps to Reproduce" that should contain information for us to help you.
