### ISSUE TITLE
updateUserProperties does not finish

### ISSUE THREAD

**Issue by daviidmorales** [oddbit/flutter_facebook_app_events#18]
## Expected Behavior
I'm trying to add a user propriety and when I call 
```dart
await facebookAppEvents.updateUserProperties(
        parameters: {
          "type": "driver",
        },
      );
```
The method never answer.

plugin version: ^0.5.0

**Comment by DennisAlund** [comment]
Could you troubleshoot a little to see what's going on. Because the code is minimal and basically just returning the promise from [`MethodChannel.invokeMethod()`](https://api.flutter.dev/flutter/services/MethodChannel/invokeMethod.html)


See the sourceode below: https://github.com/oddbit/flutter_facebook_app_events/blob/master/lib/facebook_app_events.dart#L125-L135
```dart
  Future<void> updateUserProperties({
    @required Map<String, dynamic> parameters,
    String applicationId,
  }) {
    final args = <String, dynamic>{
      'parameters': parameters,
      'applicationId': applicationId,
    };

    return _channel.invokeMethod<void>('updateUserProperties', args);
  }
```

**Comment by DennisAlund** [comment]
Is there any new information or progress on the troubleshooting of this issue? Or has it been resolved? Please share your learnings if it has been resolved by fixing external causes.

**Comment by daviidmorales** [comment]
I believed that the problem was the applicationId because I didn't pass that parameter before, but i tried with the param and it doesn't work(keep waiting)
```dart
 myFunction() async {
    try {
      print("start");

      await facebookAppEvents.updateUserProperties(
        applicationId: "XXX",
        parameters: {
          "type": "driver",
        },
      );
      
      print("end");
    } catch (e) {
      print("$e");
    }
  }
```
If i don't `await` the method the user property is defined on mi facebook console, but if i `await` the method never end

**Comment by DennisAlund** [comment]
Thanks for the info... yes I found an issue that we weren't returning success in the native code.

**Comment by DennisAlund** [comment]
Check version [0.5.2](https://pub.dev/packages/facebook_app_events#052)
