### ISSUE TITLE
[Bug]: Android SDK problem

### ISSUE THREAD

**Issue by gulmensedat** [oddbit/flutter_facebook_app_events#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
  flutter_facebook_auth: ^3.3.3-no-nullsafety
  facebook_app_events: ^0.14.7
```

flutter build apk --split-per-abi

[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.android:facebook-android-sdk:12.+.
     Required by:
         project :app > project :facebook_app_events
      > Failed to list versions for com.facebook.android:facebook-android-sdk.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/facebook/android/facebook-android-sdk/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/facebook/android/facebook-android-sdk/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/facebook/android/facebook-android-sdk/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 4m 15s
Running Gradle task 'assembleRelease'...                          255,7s
[!] Gradle threw an error while downloading artifact

### Expected Behavior

get apk output successfully

### Platform

Android

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale tr-TR)
    • Flutter version 2.5.3 at /Users/sedat/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/sedat/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at C:\Program Files\Android\Android Studio/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.45.1)
    • VS Code at /Users/sedat/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] VS Code (version 1.32.3)
    • VS Code at /Users/sedat/Library/Mobile Documents/com~apple~CloudDocs/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] VS Code (version 1.32.3)
    • VS Code at /Users/sedat/iCloud Drive (Arşiv)/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • SNE LX1 (mobile)             • HVYDU19308004006 • android-arm64  • Android 10 (API 29)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)              • macos            • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome

! Doctor found issues in 1 category.
```

**Comment by XMitja** [comment]
there's a pull request already that should fix this, although sdk could be 12.2.0 instead

https://github.com/oddbit/flutter_facebook_app_events/pull/189/commits/d6789787bdd377efd2e3c9adf6ad40c53a5c239e

**Comment by DennisAlund** [comment]
Please note that there is some conversation in https://github.com/oddbit/flutter_facebook_app_events/pull/189 the is waiting for input before we move forward 🙏

**Comment by DennisAlund** [comment]
Please confirm if it was solved in [`v0.14.8`](https://pub.dev/packages/facebook_app_events/changelog#0148)

**Comment by MlecznyU** [comment]
I face the same error with:
- facebook_app_events: ^0.14.7 or ^0.14.8
- flutter_facebook_auth: ^3.5.6
For IOS version 0.14.7 works fine, but 0.14.8 fails on pod install 

Android:
`Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.android:facebook-android-sdk:12.+.
     Required by:
         project :app > project :facebook_app_events
      > Failed to list versions for com.facebook.android:facebook-android-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml.
            > Could not GET 'https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml'. Received status code 502 from server: Bad Gateway`

IOS for version 0.14.8 after running pod install
`[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In snapshot (Podfile.lock):
    FBSDKCoreKit (= 12.1.0, ~> 12.1.0)

  In Podfile:
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 12.2.1)

    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 3.5.3, which depends on
      FBSDKCoreKit (~> 12.1.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `FBSDKCoreKit` inside your development pod `flutter_facebook_auth`.
   You should run `pod update FBSDKCoreKit` to apply changes you've made.
`

**Comment by squaredx** [comment]
I'm not an android developer, but it might be related to the gradle outage right now https://status.gradle.com/

**Comment by DennisAlund** [comment]
It there's any version problem with `12.+` please try to change it to `[12.0,13.0)` as it should be better cross package compatibility by allowing **any** version between 12 and 13 ((see doc for version specs)[https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402])

![image](https://user-images.githubusercontent.com/2051607/145921575-44db0e48-69c6-4d00-8522-99689ab60371.png)

**Comment by andre-paraense** [comment]
> I'm not an android developer, but it might be related to the gradle outage right now https://status.gradle.com/
> 
> **EDIT:** I also noticed that hard coding the version in `build.gradle` to a specific version fixes the issue for me.
> 
> i.e. in the package build.gradle change this `implementation 'com.facebook.android:facebook-android-sdk:12.+'` to this `implementation 'com.facebook.android:facebook-android-sdk:12.3.0'`

Yes, I think you were right, it indeed had to do with this outage. It is back working now. Thanks! :)
