### ISSUE TITLE
[Bug]:  exception when calling the logEvent method

### ISSUE THREAD

**Issue by agrawalharsh90** [oddbit/flutter_facebook_app_events#199]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

> **Flutter Facebook App Events gives the error: kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized**

I am using the latest version of FaceBook App Events plugin in Flutter with the latest version of Flutter as well. On click event, I am calling the logEvent method like this:
```
facebookAppEvents.logEvent(
    name: 'Link Clicked',
    parameters: {'url': request.url},
);
```
where the facebookAppEvents defined and initialized in the class itself:
```
static final facebookAppEvents = FacebookAppEvents();
```

### Expected Behavior

**It should properly log the event the properly without any error.**

### Platform

Android

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.8.1 at /Users/harshagrawal/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/harshagrawal/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/harshagrawal/Documents/development/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

**Comment by agrawalharsh90** [comment]
<img width="1340" alt="Screenshot 2022-01-19 at 11 08 24 AM" src="https://user-images.githubusercontent.com/42579052/150070749-febc669f-e0b4-426d-8852-309c7398fc27.png">

**Comment by agrawalharsh90** [comment]
<img width="1515" alt="Screenshot 2022-01-19 at 11 11 13 AM" src="https://user-images.githubusercontent.com/42579052/150071010-d87d3a1b-8751-4009-9f31-8e7bcbf1cf40.png">

**Comment by agrawalharsh90** [comment]
<img width="1515" alt="Screenshot 2022-01-19 at 11 11 27 AM" src="https://user-images.githubusercontent.com/42579052/150071032-1808d04f-1703-4219-b89e-797a8974be11.png">

**Comment by agrawalharsh90** [comment]
@anyone can help me in this issue as I have to solve this asap

**Comment by DennisAlund** [comment]
I find 8 results when searching issues for "sdk initialized" please search, read and see if it is already discussed and solved

https://github.com/oddbit/flutter_facebook_app_events/search?q=sdk+initialized&type=issues

**Comment by agrawalharsh90** [comment]
@DennisAlund no solution is in any of the issue, 
There is one issue that has exact same problem but no solution is present in it.
https://github.com/oddbit/flutter_facebook_app_events/issues/186


Can you please provide me the solution as to solve this?

**Comment by DennisAlund** [comment]
Seems to be a configuration error by the user since the OP of #186 closed his own issue. I don't know what the solution was since he reported problem but closed it himself. 

My assumption would be that he had misconfigured the setup. There was no explanation afterwards what he had missed. But if you find that you have a misconfiguration, I would really appreciate if you share with the community what it was and how you solved it. 

But from my side, I can't reproduce it.

Have you tried comparing your project with the `example` project in the repo?

**Comment by AbdulrazakZakieh** [comment]
I am facing the same problem and I did all the configurations as instructed. setAdvertiserTracking is working but events are not. 
I searched for similar problems but found none and all the issues you mentioned are irrelevant as I see it.

**Comment by agrawalharsh90** [comment]
@AbdulrazakZakieh 

not put id here manifest like this
```
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="xxxxxxxxxx" />
```

add like this

```
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />
```

create **strings.xml** file in **android/app/src/main/res/values/** and put id here 

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="facebook_app_id">xxxxxxxxxx</string>
</resources>
```

**Comment by furkanvatandas** [comment]
> @AbdulrazakZakieh
> 
> not put id here manifest like this
> 
> ```
>         <meta-data
>             android:name="com.facebook.sdk.ApplicationId"
>             android:value="xxxxxxxxxx" />
> ```
> 
> add like this
> 
> ```
>         <meta-data
>             android:name="com.facebook.sdk.ApplicationId"
>             android:value="@string/facebook_app_id" />
> ```
> 
> create **strings.xml** file in **android/app/src/main/res/values/** and put id here
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>     <string name="facebook_app_id">xxxxxxxxxx</string>
> </resources>
> ```

Not working for me

**Comment by furkanvatandas** [comment]
https://developers.facebook.com/docs/app-events/getting-started-app-events-android

After adding <string name="facebook_client_token"></string> it's working

**Comment by mayder** [comment]
> > @AbdulrazakZakieh
> > not put id here manifest like this
> > ```
> >         <meta-data
> >             android:name="com.facebook.sdk.ApplicationId"
> >             android:value="xxxxxxxxxx" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > add like this
> > ```
> >         <meta-data
> >             android:name="com.facebook.sdk.ApplicationId"
> >             android:value="@string/facebook_app_id" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > create **strings.xml** file in **android/app/src/main/res/values/** and put id here
> > ```
> > <?xml version="1.0" encoding="utf-8"?>
> > <resources>
> >     <string name="facebook_app_id">xxxxxxxxxx</string>
> > </resources>
> > ```
> 
> Not working for me

I have the same problem.

**Comment by Ahmedklai** [comment]
So the solution was basically to put the : 
`			<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
   	   <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`
   	   
in the right spot , they need to be under the **<application> Tag** , in the first range so not under <application> and then <activity> tag just under the <application> tah in the androidManifest just as in the pic below ! 
![Screenshot 2022-07-10 at 11 56 43](https://user-images.githubusercontent.com/60032213/178141971-539d90f6-b8bb-42b2-a9c3-57772991da6f.png)
.

**Comment by Ahmedklai** [comment]
So the solution was basically to put the :
`<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/> <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`

in the right spot , they need to be under the application  Tag , in the first range so not under appliction and then activity  tag just under the **application tag** in the androidManifest just as in the pic below !

**Comment by Ahmedklai** [comment]
So the solution was basically to put the :
`<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/> <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`

in the right spot , they need to be under the application Tag , in the first range so not under appliction and then activity tag just under the **application tag** in the androidManifest just as in the pic below !
![Screenshot 2022-07-10 at 11 58 44](https://user-images.githubusercontent.com/60032213/178142044-8afb1ca2-aeb3-46ee-88da-895842384700.png)
