### ISSUE TITLE
[Bug]: [connection] nw_resolver_start_query_timer_block_invoke [C35.1] Query fired: did not receive all answers in time for graph.facebook.com:443

### ISSUE THREAD

**Issue by acorcfromacart** [oddbit/flutter_facebook_app_events#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I start to run my app I'm always receiving this error: 

`[connection] nw_resolver_start_query_timer_block_invoke [C46.1] Query fired: did not receive all answers in time for graph.facebook.com:443
`

It's working perfectly on Android, but not on iOS. 

### Expected Behavior

It should send events.

### Steps To Reproduce

1. Just run the app on iOS

### Flutter Doctor

```shell
Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale pt-BR)
    • Flutter version 2.8.1 at /Users/antoniowanderley/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/antoniowanderley/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/antoniowanderley/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/antoniowanderley/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Users/antoniowanderley/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone de Antonio (mobile) • 00008030-001509663613402E • ios            • iOS 15.2.1 19C63
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 97.0.4692.71
```

**Comment by kevinzDzul** [comment]
this maybe help you [recommendation](https://github.com/oddbit/flutter_facebook_app_events/issues/203#issuecomment-1025221137).
maybe you need to enable tracking in facebook app. in iOS setting (iOS settings > Facebook > Allow Tracking).

**Comment by kevinzDzul** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> When I start to run my app I'm always receiving this error:
> 
> `[connection] nw_resolver_start_query_timer_block_invoke [C46.1] Query fired: did not receive all answers in time for graph.facebook.com:443 `
> 
> It's working perfectly on Android, but not on iOS.
> 
> ### Expected Behavior
> It should send events.
> 
> ### Steps To Reproduce
> 1. Just run the app on iOS
> 
> ### Platform
> _No response_
> 
> ### Flutter Doctor
> ```shell
> Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale pt-BR)
>     • Flutter version 2.8.1 at /Users/antoniowanderley/FlutterDev/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
>     • Engine revision 890a5fca2e
>     • Dart version 2.15.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/antoniowanderley/Library/Android/sdk
>     • Platform android-31, build-tools 31.0.0
>     • Java binary at: /Users/antoniowanderley/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Users/antoniowanderley/Downloads/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [✓] VS Code (version 1.62.3)
>     • VS Code at /Users/antoniowanderley/Downloads/Visual Studio Code.app/Contents
>     • Flutter extension version 3.29.0
> 
> [✓] Connected device (2 available)
>     • iPhone de Antonio (mobile) • 00008030-001509663613402E • ios            • iOS 15.2.1 19C63
>     • Chrome (web)               • chrome                    • web-javascript • Google Chrome 97.0.4692.71
> ```

this maybe help you [recommendation](https://github.com/oddbit/flutter_facebook_app_events/issues/203#issuecomment-1025221137).
maybe you need to enable tracking in facebook app. in iOS setting (iOS settings > Facebook > Allow Tracking).

**Comment by ferysyukur** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Current Behavior
> > When I start to run my app I'm always receiving this error:
> > `[connection] nw_resolver_start_query_timer_block_invoke [C46.1] Query fired: did not receive all answers in time for graph.facebook.com:443 `
> > It's working perfectly on Android, but not on iOS.
> > ### Expected Behavior
> > It should send events.
> > ### Steps To Reproduce
> > 
> > 1. Just run the app on iOS
> > 
> > ### Platform
> > _No response_
> > ### Flutter Doctor
> > ```shell
> > Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale pt-BR)
> >     • Flutter version 2.8.1 at /Users/antoniowanderley/FlutterDev/flutter
> >     • Upstream repository https://github.com/flutter/flutter.git
> >     • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
> >     • Engine revision 890a5fca2e
> >     • Dart version 2.15.1
> > 
> > [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> >     • Android SDK at /Users/antoniowanderley/Library/Android/sdk
> >     • Platform android-31, build-tools 31.0.0
> >     • Java binary at: /Users/antoniowanderley/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
> >     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> >     • All Android licenses accepted.
> > 
> > [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
> >     • Xcode at /Applications/Xcode.app/Contents/Developer
> >     • CocoaPods version 1.11.2
> > 
> > [✓] Chrome - develop for the web
> >     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> > 
> > [✓] Android Studio (version 2020.3)
> >     • Android Studio at /Applications/Android Studio.app/Contents
> >     • Flutter plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> >     • Dart plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> >     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> > 
> > [✓] Android Studio (version 2020.3)
> >     • Android Studio at /Users/antoniowanderley/Downloads/Android Studio.app/Contents
> >     • Flutter plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> >     • Dart plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> >     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> > 
> > [✓] VS Code (version 1.62.3)
> >     • VS Code at /Users/antoniowanderley/Downloads/Visual Studio Code.app/Contents
> >     • Flutter extension version 3.29.0
> > 
> > [✓] Connected device (2 available)
> >     • iPhone de Antonio (mobile) • 00008030-001509663613402E • ios            • iOS 15.2.1 19C63
> >     • Chrome (web)               • chrome                    • web-javascript • Google Chrome 97.0.4692.71
> > ```
> 
> this maybe help you [recommendation](https://github.com/oddbit/flutter_facebook_app_events/issues/203#issuecomment-1025221137). maybe you need to enable tracking in facebook app. in iOS setting (iOS settings > Facebook > Allow Tracking).

Hi @acorcfromacart , did you try the solution ?
Let me know if you still have issue like this.

**Comment by DennisAlund** [comment]
Please consolidate questions and suggested solutions regarding iOS14 and failure to log events in this thread: #122
