### ISSUE TITLE
Custom user property

### ISSUE THREAD

**Issue by rserro** [oddbit/flutter_facebook_app_events#21]
The `setUserData` method only allows to set pre-defined Facebook user properties. It would be very helpful to be able to set custom properties  as well. https://developers.facebook.com/docs/analytics/send_data/user_properties/

Maybe something like `setUserData({...current args..., Map<String, dinamic> custom})` or having another method like  `setCustomUserData(Map<String, dynamic> data)`.

**Comment by DennisAlund** [comment]
The `setUserData()` method that takes a parameter of arbitrary attributes has been *deprecated* ([please see documentation](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html/#setuserdata-bundle-))

We have implemented the method that is superseding that: [`setUserData`](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html/#setuserdata-javalangstring-javalangstring-javalangstring-javalangstring-javalangstring-javalangstring-javalangstring-javalangstring-javalangstring-javalangstring-)

Please check [`updateUserProperties`](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html/#updateuserproperties-bundle-javalangstring-comfacebookgraphrequestcallback-) documentation in case that's something you were looking for.
