### ISSUE TITLE
[Bug]: Autolog Purchase Events are not Working on Android with Deepwall SDK

### ISSUE THREAD

**Issue by sezai-yuksel** [oddbit/flutter_facebook_app_events#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Autolog purchase events are working on iOS Side. But on android side they are not working.

### Expected Behavior

Purchase and start trial events must be send to facebook on android side with Deepwall SDK (https://www.deepwall.com/).

### Platform

Android

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.3.1 21E258 darwin-arm, locale en-TR)
    • Flutter version 2.10.0 at /Users/sezaiyuksel/fvm/versions/2.10.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (10 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/sezaiyuksel/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • Trusted Network (mobile) • 00008030-001804822E47802E • ios            • iOS 15.3.1 19D52
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by samatzhusup** [comment]
Any solution?

**Comment by DennisAlund** [comment]
Thank you for reporting this issue. Could you elaborate on this a bit to describe what part of it is a technical issue of the plugin, with separation from expectational difference of the SDK or otherwise.

Please elaborate on the issue with steps to reproduce and links to documentation that states the expected behavior on both platforms so that we can follow it to implement the correct behavior.

Thank you

**Comment by DennisAlund** [comment]
> Purchase and start trial events must be send to facebook on android side with Deepwall SDK (https://www.deepwall.com/).

What do you mean by this? Is this what you want to accomplish or is it your workaround?

Furthermore, can you provide more information on the context of works on iOS and not on android. What have you configured, how have you troubleshoot it and what documentation supports your expectations?

**Comment by sezai-yuksel** [comment]
Hello,

We are using Deepwall SDK to show paywalls.

https://www.deepwall.com/

Steps to reproduce:
- Implement Deepwall to flutter project.
- Then run the project.
- The plugin or Facebook SDK can't track the purchase events from paywalls.

Thanks.

**Comment by sezai-yuksel** [comment]
I thought about of this. Deepwall SDK Android is showing offer screens on android side like as another project. So Facebook SDK can't detect it. I think it is not your problem so i'm closing this issue for now.
