### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jovanovski** [oddbit/flutter_facebook_app_events#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After running the latest (0.16.0) version, while compiling for iOS, the compilation fails with the error `No such module 'FBSDKCoreKit'`. If I downgrade to the previous 0.15.0 version, the compilation works as expected.

### Expected Behavior

Compilation to happen with no issues.

### Steps To Reproduce

1. Set pod and deployment targets to 11.0 iOS
2. Download 0.16.0 pod version
3. Compile

### Platform

iOS

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm (Rosetta), locale en-MK)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by seceba** [comment]
I was in the same situation. When i was facing this problem my osx version is big sur 11.0.1 and xcode version 12.3 and Swift version 5.3.

So today i updated my OSX 12.3.1 Monterey and xcode 13.3.1 and swift 5.6 this problem solved.

This issue is probably happening because of the old version so you can try update your swift 5.6 and xcode 13.3.1.

**Comment by DennisAlund** [comment]
Please elaborate if you did delete your pod cache and re-run install?

**Comment by jovanovski** [comment]
> Please elaborate if you did delete your pod cache and re-run install?

I did yes

**Comment by hiteshsurani** [comment]
For me too it's same!!!

**Comment by IMHitesh** [comment]
Same issue for me!!!

**Comment by armandojimenez** [comment]
Is there any fix for this?

**Comment by gysipos** [comment]
Hy, the latest 0.16.0 makes my iOS app crash immediatley.
Exception Type: EXC_CRASH (SIGABRT)

**Comment by ofnewman** [comment]
@gysipos 

Try adding this alongside the other keys to your info.plist:

`	<key>FacebookClientToken</key>
	<string>...</string>`

You can find your FacebookClientToken on the FB App Dashboard under Settings > Advanced > Client Token.

**Comment by gysipos** [comment]
Thank you @ofnewman, this seems like it solved my issue with the latest version

**Comment by gysipos** [comment]
at 0.17.0 the issue persist, even with all the new setup steps done.

**Comment by bhautikkeraliya** [comment]
Thank you @ofnewman your solution works for me.

**Comment by IMHitesh** [comment]
Any update for this Still I am facing the same issue.

**Comment by DennisAlund** [comment]
@IMHitesh did you try the solution in https://github.com/oddbit/flutter_facebook_app_events/issues/230#issuecomment-1210423124 as suggested by @ofnewman

**Comment by hiteshsurani** [comment]
Yes, I was able to fix the issue by adding `FacebookClientToken` to the plist. Thanks!!
