### ISSUE TITLE
[Bug]: id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleGetAnonymousId

### ISSUE THREAD

**Issue by Rodrigossff91** [oddbit/flutter_facebook_app_events#231]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

0

I install the package facebook_app_events version 0.13.5 that includes the latest facebook sdk. The problem is that when I try to log an event or get an anonymous Id it throws a kotlin exception. I upgrade my kotlin version to 1.5.31 also I try with flutter clean.

This is my code, I initialize FacebookAppEvent at the top of my widget like the code example.

facebookAppEvents.logEvent(
  name: 'button_clicked',
  parameters: {
    'button_id': 'registe_buttonr',
   },
);
This is the error:

E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052): kotlin.UninitializedPropertyAccessException: lateinit property anonymousId has not been initialized
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleGetAnonymousId(FacebookAppEventsPlugin.kt:82)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:55)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.app.ActivityThread.main(ActivityThread.java:8595)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at com.android.int

### Expected Behavior

0

I install the package facebook_app_events version 0.13.5 that includes the latest facebook sdk. The problem is that when I try to log an event or get an anonymous Id it throws a kotlin exception. I upgrade my kotlin version to 1.5.31 also I try with flutter clean.

This is my code, I initialize FacebookAppEvent at the top of my widget like the code example.

facebookAppEvents.logEvent(
  name: 'button_clicked',
  parameters: {
    'button_id': 'registe_buttonr',
   },
);
This is the error:

E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052): kotlin.UninitializedPropertyAccessException: lateinit property anonymousId has not been initialized
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleGetAnonymousId(FacebookAppEventsPlugin.kt:82)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:55)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.app.ActivityThread.main(ActivityThread.java:8595)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at com.android.int

### Flutter Doctor

```shell
0


I install the package facebook_app_events version 0.13.5 that includes the latest facebook sdk. The problem is that when I try to log an event or get an anonymous Id it throws a kotlin exception. I upgrade my kotlin version to 1.5.31 also I try with flutter clean.

This is my code, I initialize FacebookAppEvent at the top of my widget like the code example.

facebookAppEvents.logEvent(
  name: 'button_clicked',
  parameters: {
    'button_id': 'registe_buttonr',
   },
);
This is the error:

E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052): kotlin.UninitializedPropertyAccessException: lateinit property anonymousId has not been initialized
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleGetAnonymousId(FacebookAppEventsPlugin.kt:82)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:55)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at android.app.ActivityThread.main(ActivityThread.java:8595)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16052):   at com.android.int
```

**Comment by DennisAlund** [comment]
It's a bit difficult to read the description. Can you confirm that you have tried the example app and compared results?

**Comment by Rodrigossff91** [comment]
It's buggy, there are some logs here
![image](https://user-images.githubusercontent.com/43223244/170767037-a4b74f9d-7ca5-4297-b96e-48098f766c48.png)

**Comment by DennisAlund** [comment]
Could you help clarifying which of the methods described in related issues that you have tried and confirmed not being solution to your problem?

https://github.com/oddbit/flutter_facebook_app_events/search?q=appEventsLogger+has+not+been+initialized&type=issues

For example

 * https://github.com/oddbit/flutter_facebook_app_events/issues/186
 * https://github.com/oddbit/flutter_facebook_app_events/issues/199

**Comment by DennisAlund** [comment]
Closed due to inactivity and possibly duplicate
