### ISSUE TITLE
[Bug]:  GraphRequest can't be used when Facebook SDK isn't fully initialized

### ISSUE THREAD

**Issue by Collins-01** [oddbit/flutter_facebook_app_events#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have completely followed the setup from the facebook developer's website. I get this error anytime i try to log an event.

" GraphRequest can't be used when Facebook SDK isn't fully initialized"

I can print out the app ID, and the the anon ID,  but can not log anyevent.

### Expected Behavior

I wanted to log events, but unfortunately doe not not work

### Steps To Reproduce

Just Install and try to log an Event

### Platform

Android

### Flutter Doctor

```shell
No issues found!
```

**Comment by a15056478** [comment]
I am also facing same issue

**Comment by DennisAlund** [comment]
Try the example app. 

https://github.com/oddbit/flutter_facebook_app_events/tree/develop/example
