### ISSUE TITLE
[Bug]: 0.16.0 The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() 

### ISSUE THREAD

**Issue by developer-caleb** [oddbit/flutter_facebook_app_events#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I do input metadata right way. But I occurred error. I downgrade version. I fixed.

E/GeneratedPluginRegistrant( 4189): Error registering plugin facebook_app_events, id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin
E/GeneratedPluginRegistrant( 4189): The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
E/GeneratedPluginRegistrant( 4189): 	at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
E/GeneratedPluginRegistrant( 4189): 	at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.kt:642)
E/GeneratedPluginRegistrant( 4189): 	at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.kt:82)
E/GeneratedPluginRegistrant( 4189): 	at com.facebook.appevents.AppEventsLogger.<init>(AppEventsLogger.kt:118)
E/GeneratedPluginRegistrant( 4189): 	at com.facebook.appevents.AppEventsLogger.<init>(Unknown Source:0)
E/GeneratedPluginRegistrant( 4189): 	at com.facebook.appevents.AppEventsLogger$Companion.newLogger(AppEventsLogger.kt:369)
E/GeneratedPluginRegistrant( 4189): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onAttachedToEngine(FacebookAppEventsPlugin.kt:34)
E/GeneratedPluginRegistrant( 4189): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
E/GeneratedPluginRegistrant( 4189): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
E/GeneratedPluginRegistrant( 4189): 	at java.lang.reflect.Method.invoke(Native Method)
E/GeneratedPluginRegistrant( 4189): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/GeneratedPluginRegistrant( 4189): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:355)
E/GeneratedPluginRegistrant( 4189): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:263)
E/GeneratedPluginRegistrant( 4189): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:243)
E/GeneratedPluginRegistrant( 4189): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:163)
E/GeneratedPluginRegistrant( 4189): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.lambda$startBackgroundIsolate$0$io-flutter-plugins-firebase-messaging-FlutterFirebaseMessagingBackgroundExecutor(FlutterFirebaseMessagingBackgroundExecutor.java:167)
E/GeneratedPluginRegistrant( 4189): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor$$ExternalSyntheticLambda1.run(Unknown Source:8)
E/GeneratedPluginRegistrant( 4189): 	at android.os.Handler.handleCallback(Handler.java:883)
E/GeneratedPluginRegistrant( 4189): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/GeneratedPluginRegistrant( 4189): 	at android.os.Looper.loop(Looper.java:237)
E/GeneratedPluginRegistrant( 4189): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/GeneratedPluginRegistrant( 4189): 	at java.lang.reflect.Method.invoke(Native Method)
E/GeneratedPluginRegistrant( 4189): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/GeneratedPluginRegistrant( 4189): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

### Expected Behavior

I expected no error logs. 

### Steps To Reproduce

I read issues in GitHub. But there is no open issue regarding this problem. 
So I downgrade facebook_app_events: 0.16.0 ->  acebook_app_events: 0.14.8
It works for me.

### Platform

Android

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] VS Code (version 1.67.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

**Comment by Jihadik** [comment]
We are experiencing the same problem

**Comment by vanlooverenkoen** [comment]
We are having the same problem as well

**Comment by pedrofneves** [comment]
You need to configure the Facebook SDK in your app project, adding de client token. Follow the steps described in the documentation: https://developers.facebook.com/docs/android/getting-started/

**Comment by DennisAlund** [comment]
Could you please let me know which of the previous, related issues that you have tried and confirmed not being the same problem as you're having?

https://github.com/oddbit/flutter_facebook_app_events/search?q=The+SDK+has+not+been+initialized&type=issues

**Comment by esentis** [comment]
#186 solved it for me

**Comment by DennisAlund** [comment]
Closed due to lack of searching for existing issues that already described and solved the issue
