### ISSUE TITLE
[Bug]: Conflict in FBSDKCoreKit

### ISSUE THREAD

**Issue by NadineMuhamad** [oddbit/flutter_facebook_app_events#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The pod install won't work with the flutter login Facebook.
 CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 13.1.0)

    flutter_login_facebook (from `.symlinks/plugins/flutter_login_facebook/ios`) was resolved to 1.5.0, which depends on
      FBSDKLoginKit (= 14.0.0) was resolved to 14.0.0, which depends on
        FBSDKCoreKit (= 14.0.0)

### Expected Behavior

Expect to work with Facebook app events and flutter Facebook login

### Flutter Doctor

```shell
Flutter (Channel stable, 2.10.3, on macOS 12.4 21F79 darwin-x64, locale en-EG)
    • Flutter version 2.10.3 at /Users/nouh/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
 Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3
```

**Comment by DennisAlund** [comment]
We are not collaborating with other flutter Facebook plugins, but we do try as much as we can to keep the plugin up to date with the most recent FBSDK and hoping that other plugin maintainers do the same 🙏
