### ISSUE TITLE
The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.

### ISSUE THREAD

**Issue by tim-teacher** [oddbit/flutter_facebook_app_events#25]
I receive  The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first for version ^0.5.2.

I am looking to the example and as I understand the initialisation is done in 
static final facebookAppEvents = FacebookAppEvents(); but it is not work.

**Comment by tim-teacher** [comment]
Is this lib still supported?

**Comment by chhota89** [comment]
@tim-teacher Same error here. How you have solved this issue?

**Comment by obrunsmann** [comment]
Any solutions? 😬

**Comment by raviganwal** [comment]
I had the same issue because, I declared `facebook_app_id` like this,
```
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="8*9*7*5**1*5***" />
```
but but will have to delcare `facebook_app_id` inside `string.xml` and then declare it in manifest.xml like this,
```
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />
```
