### ISSUE TITLE
[Bug]: Upgrade for FBSDKCoreKit 15.0.0

### ISSUE THREAD

**Issue by socialglass** [oddbit/flutter_facebook_app_events#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the podspec on this is mapped to FBSDKCoreKit 14.1.0. Facebook says this is old now and is pushing us to use v15.0.0 for reasons specific to ads & events setup. 

Is there a plan to upgrade this package to FBSDKCoreKit 15.0.0

### Expected Behavior

Want to use FBSDKCoreKit v15.0.0, since Facebook is forcing us for ads + events managements. However, this package is still using FBSDKCoreKit 14.1.0

### Platform

iOS

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by wwnOddbit** [comment]
facebook_app_events: ^0.18.0 was freshly upgraded to FBSDKCoreKit 15.0.0. Thanks for raising the issue @socialglass.

Closing this issue for now.
