### ISSUE TITLE
ViewContent Event Issues

### ISSUE THREAD

**Issue by asaave** [oddbit/flutter_facebook_app_events#27]
I'm getting the following error when trying to log ViewContent standard event on Facebook:

FBSDKLog: The values in the parameters dictionary must be NSStrings or NSNumbers.

Through Android, the event is not being logged as well.

It is applying to the parameter content in ViewContent. Seems that the Map<String, Dynamic> is sending the dynamic value as anything different than String and cannot be forced.

Example to replicate the issue:

final String pageID = '123';

 final String pageType = 'Type';

facebookAppEvents.logViewContent(
content: {'name': 'Test'},
id: pageID,
type: pageType
);

**Comment by DennisAlund** [comment]
Sorry for a late follow up and thank you for the heads up. I will try to investigate.

**Comment by DennisAlund** [comment]
Can you confirm that this is still an issue?

**Comment by ganeshrvel** [comment]
@DennisAlund I can confirm that the event is not being logged, on Facebook dashboard, for android devices

**Comment by DennisAlund** [comment]
Possibly fixed in 5b76d5a9 feel free to open a new issue with the provided issue template and full context if you are still experiencing problems 🙏
