### ISSUE TITLE
[Bug]: CocoaPods could not find compatible versions for pod "FBSDKCoreKit"

### ISSUE THREAD

**Issue by techwithsam** [oddbit/flutter_facebook_app_events#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In snapshot (Podfile.lock):
    FBSDKCoreKit (= 9.1.0, ~> 9.1.0)

  In Podfile:
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 15.0.0)

You have either:
 * changed the constraints of dependency `FBSDKCoreKit` inside your development pod `facebook_app_events`.
   You should run `pod update FBSDKCoreKit` to apply changes you've made.

### Expected Behavior

pod install should install normally

### Platform

iOS

### Flutter Doctor

```shell
samuel@Samuels-MacBook-Pro one_app % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0.1 22A400 darwin-arm, locale en-NG)
    • Flutter version 3.3.7 on channel stable at /Users/samuel/Documents/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (3 weeks ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/samuel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 8176A69C-323C-4AA6-AD33-C20EACD70E7A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by ernest0vm** [comment]
just delete your `Podifile.lock` then reinstall all pods

```console
cd ios && rm -rf Podfile.lock && pod install
```

other way

```console
pod install --repo-update
```

**Comment by techwithsam** [comment]
I'm still getting this error 
```
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 15.0.0)

Specs satisfying the `FBSDKCoreKit (~> 15.0.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by ernest0vm** [comment]
> I'm still getting this error @ernest0vm
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
>   In Podfile:
>     facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
>       FBSDKCoreKit (~> 15.0.0)
> 
> Specs satisfying the `FBSDKCoreKit (~> 15.0.0)` dependency were found, but they required a higher minimum deployment target.
> ```

ok, your problem is this 

> required a higher minimum deployment target.

this package requires that your minimum deployment target must be iOS 11 or above

[https://github.com/oddbit/flutter_facebook_app_events/blob/b6d3abf19866140b9f0ec90c751d8f0147ead239/ios/facebook_app_events.podspec#L17](https://github.com/oddbit/flutter_facebook_app_events/blob/b6d3abf19866140b9f0ec90c751d8f0147ead239/ios/facebook_app_events.podspec#L17)

**Comment by techwithsam** [comment]
Yeah but my minimum deployment target is 11

**Comment by ernest0vm** [comment]
> Yeah but my minimum deployment target is 11

review this line in your podfile

```ruby
platform :ios, '12.4'
```

in my case i use iOS 12.4 such as minimum deployment target, if you has this line commented, uncomment, add your target then save and run `pod install` again, try `clean build folder` within Xcode too

**Comment by techwithsam** [comment]
> > Yeah but my minimum deployment target is 11
> 
> review this line in your podfile
> 
> ```ruby
> platform :ios, '12.4'
> ```
> 
> in my case i use iOS 12.4 such as minimum deployment target, if you has this line commented, uncomment, add your target then save and run `pod install` again, try `clean build folder` within Xcode too

Okay, I will try it out thanks

**Comment by DennisAlund** [comment]
Seems like it is a local issue of project configuration. Please re-open the issue if the problem persists in a way that should be fixed on this repo.
