### ISSUE TITLE
[Bug]: Error sending decimal price in logAddToCart

### ISSUE THREAD

**Issue by aflopezbec** [oddbit/flutter_facebook_app_events#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try send the logAddToCart event but the price has decimals the currency value no show in facebook

`_facebookAppEvents.logAddToCart(
      id: product.slug,
      type: "product",
      price: product.price,
      currency: 'MXN',
      content: {
        '1': {'name': product.name},
        '2': {'slug': product.slug},
        '3': {'price': product.price},
        '4': {'sku': product.sku},
        '5': {'upc': product.upc},
      },
    );`

<img width="298" alt="Captura de pantalla 2022-11-30 a la(s) 6 48 45 p m" src="https://user-images.githubusercontent.com/15723139/204932437-3635ef0a-3497-4dae-806c-4ff5acb26a3a.png">

<img width="854" alt="Captura de pantalla 2022-11-30 a la(s) 6 47 58 p m" src="https://user-images.githubusercontent.com/15723139/204932337-501ec106-c949-4bb1-ac8f-024d067f6fa5.png">

    
    

### Expected Behavior

Show price correctly in facebook dev platform

### Steps To Reproduce

1. Configure event
2. Send
3. Check in facebook event manager

### Platform

Android

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.3, on macOS 13.0.1 22A400 darwin-arm, locale es-419)
    • Flutter version 3.3.3 on channel stable at /Users/andres/fvm/versions/3.3.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (9 weeks ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/andres/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.0)
    • VS Code at /Users/andres/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by DennisAlund** [comment]
Thanks for the report @aflopezbec could you please let us know if this is happening on Android, iOS or both?

Do you have more information on how it shows up in your Facebook console?

**Comment by DennisAlund** [comment]
Hey, @aflopezbec thanks for the report. Can you please elaborate on your expectations. We have followed the documentation of Facebook App Events, and the price is submitted to `valueToSum` to provide information on "average" etc

Please see documentation: https://developers.facebook.com/docs/reference/android/current/class/AppEventsConstants/

Let me know if you can find a documentation that defines it differently. Otherwise, you can also implement custom events for your own needs where you provide any parameters you need 🙏

**Comment by wwnOddbit** [comment]
This could be related as well:
https://developers.facebook.com/docs/unity/reference/current/FB.LogAppEvent

<img width="828" alt="image" src="https://user-images.githubusercontent.com/91527455/205562962-b3b8dd09-2c74-4e5b-a3a2-e2a1e4803db3.png">

> The user has added an item to their cart. The valueToSum passed should be the item's price.
