### ISSUE TITLE
Automatically logged events

### ISSUE THREAD

**Issue by zhitnyakov** [oddbit/flutter_facebook_app_events#28]
Does it log default events like `app installs`? Which described here - [https://developers.facebook.com/docs/app-events/getting-started-app-events-android#step-4--add-app-events](https://developers.facebook.com/docs/app-events/getting-started-app-events-android#step-4--add-app-events)

**Comment by DennisAlund** [comment]
Yes, I should do that.

**Comment by noobiek** [comment]
@zhitnyakov 
Hi, were you able to get app install attribution working in Facebook Ads with this plugin? Android/iOS?

Thanks!

**Comment by zhitnyakov** [comment]
> @zhitnyakov
> Hi, were you able to get app install attribution working in Facebook Ads with this plugin? Android/iOS?
> 
> Thanks!

Hi! I did not try yet.

**Comment by zhitnyakov** [comment]
> Yes, I should do that.

So you're goind to do that? or it's already done? =)

**Comment by noobiek** [comment]
@zhitnyakov 
Hi,
It works. We had some trouble - at first it did not work (install events were reported, but Facebook attribution to ad did not work). We've spent a week trying to figure this out. Then simply recreating Ad campaigns fixed the issue... who would have guessed....

**Comment by matte5031** [comment]
@DennisAlund @noobiek 
1: So it will automatically add in-app purchases aswell since they are part of the automatically logged events, right?

2. These automatically logged events doesn't requite any code at all or? Just simply add the plugin in pubspec.yaml and 
do the config setup. But no actual dart code needed? 

Any help or input at all is highly appreciated, thanks!!

**Comment by shredding** [comment]
I would also be interested in some more input here - the code does not automatic logging or anything.

**Comment by noobiek** [comment]
@shredding, @matte5031,
We've made a PR #50 to log purchases. After each purchase you need to send the purchase event.
And installs should be logged automatically.

**Comment by DennisAlund** [comment]
> > Yes, I should do that.
> 
> So you're going to do that? or it's already done? =)

Sorry, the reply should have said "Yes, **it** should do that."

**Comment by ys-sherzad** [comment]
@noobiek Hi there, does this mean purchase events are not automatically logged? I do notice that we don't have any logs for purchases even though it should be automatically logged. What do we have to in this regard? thank you
