### ISSUE TITLE
[Bug]: Android SDK version displayed as v0.0.0 on Facebook Dashboard

### ISSUE THREAD

**Issue by narritt** [oddbit/flutter_facebook_app_events#286]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The facebook_app_events Flutter plugin seems to be misreporting the Android SDK version on the Facebook Dashboard. The version is displayed as 0.0.0, which results in some Facebook functionality being blocked or not working as expected.

<img width="974" alt="Screenshot 2023-03-26 at 10 25 34" src="https://user-images.githubusercontent.com/3397139/227761847-029a61e5-436c-4ad3-b3c1-f8f8681334b9.png">

### Expected Behavior

The correct Android SDK version for the facebook_app_events plugin should be displayed on the Facebook Dashboard (13.0.0?)

### Steps To Reproduce

1. Integrate the facebook_app_events plugin into a Flutter project.
2. Configure the plugin with a valid Facebook App ID.
3. Build and run the Flutter app on an Android device or emulator.
4. Navigate to the [Facebook Dashboard](https://developers.facebook.com/apps/) and select the corresponding app.
5. Go to the 'Setting -> Advanced' section and check the Android SDK version.

### Platform

Android

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0 22A380 darwin-arm, locale en-IL)
    • Flutter version 3.3.10 on channel stable at /Users/lev/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lev/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/lev/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by ferysyukur** [comment]
Hi @narritt , whats version are you using ? Because I can see the version for android sdk. Please make sure your setup same like in example project or you can check in [our readme](https://github.com/oddbit/flutter_facebook_app_events#readme).

**Comment by narritt** [comment]
I'm using the last version: `facebook_app_events: ^0.18.3`.
My setup is the same as the readme and example project:
AndroidManifest.xml:
```
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
```
The strings.xml file contains `facebook_app_id`, `fb_login_protocol_scheme`, and `facebook_client_token` values.

Is it all android integration? 

Thanks for any help

**Comment by DennisAlund** [comment]
Thank you for the report @narritt have you tried asking on StackOverflow also? I think we would require complete context of your code and configuration to be able to help, and the quickest way would be to also ask the larger community as we are few people with limited time to focus on primarily technical bugs and improvements of the plugin.

Thank you for engaging to help improvements 🤗
