### ISSUE TITLE
[Bug]: Getting rate limits even without logging any events

### ISSUE THREAD

**Issue by melnychuk-yaro** [oddbit/flutter_facebook_app_events#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
Getting rate limits even without logging any events.

![image](https://user-images.githubusercontent.com/74709638/229553579-9412c506-0af5-46cc-a7a2-9fbe54b03116.png)

### Expected Behavior

How can I debug or get rid of rate limits?

### Platform

Android, iOS

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.7.9 on channel stable at /Users/yaroslavmelnychuk/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (4 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/yaroslavmelnychuk/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • 2207117BPG (mobile) • 7LKZ59DQCI8TS47P • android-arm64  • Android 12 (API 31)
    • macOS (desktop)     • macos            • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by wwnOddbit** [comment]
Can you help me with steps how to reproduce your issue? Where are you getting that screenshot about the rate limit?

**Comment by skol101** [comment]
The screen shot is from our Facebok App page  on http://developers.facebook.com

**Comment by skol101** [comment]
![Screenshot 2023-04-10 at 15 11 43](https://user-images.githubusercontent.com/53978091/230899333-7fa3a1af-58ab-417b-9da2-d414328e846d.png)

**Comment by wwnOddbit** [comment]
Thanks for the quick follow up. We probably could use 

> Getting rate limits even without logging any events.

You may want to check:

- whether you're using features in facebook sdk other than app events. It could be other plugins which also use the sdk
- dig deeper into the dashboard to see which application, endpoint, or user displays excessive usage
- check if there are any misconfigurations such as invalid access token, facebook application ID, SKAdNetwork permission, etc

https://developers.facebook.com/docs/graph-api/overview/rate-limiting/
https://web.facebook.com/business/help/670955636925518

**Comment by ericyu76** [comment]
We are facing the same rate limit issue. Is there any solution for this kind of problem to share?

According to rate limit rule  (Calls within one hour = 200 * Number of Users) , the limits should not be reached. I'm suspect the count of Users problem. Is there any config or code  need for facebook to recognize unique users?
