### ISSUE TITLE
Your SDK doesn't seem to have updated correctly. Please try again.

### ISSUE THREAD

**Issue by Xgamefactory** [oddbit/flutter_facebook_app_events#3]
We are getting error during verify at facebook event manager test

Your SDK doesn't seem to have updated correctly. Please try again.

**Comment by Xgamefactory** [comment]
sorry plugin works as expected. Thanks
problem solved after adding Analytics  https://developers.facebook.com/apps/

**Comment by Xgamefactory** [comment]
but on the last step shake verifiying getting no result
is there something we are missing ?

<img width="485" alt="Screen Shot 2019-10-28 at 15 47 30" src="https://user-images.githubusercontent.com/22529051/67676206-610c8100-f99a-11e9-9ad9-2cd87d58f140.png">

**Comment by andersonmendesdev** [comment]
There is a solution, I am stuck in this problem.
