### ISSUE TITLE
[Bug]: IOS builtin AppEvents are not sent to Facebook on deeplink

### ISSUE THREAD

**Issue by bsz0206** [oddbit/flutter_facebook_app_events#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running Facebook deeplink, developer test, it opens the app but does the events are not fire correctly and after 3 minutes we get an error

### Expected Behavior

When running Facebook deeplink, developer test, it should open the app and after 0-2 minutes should pass (when app events reach facebook)

### Steps To Reproduce

Follow Facebook DeepLink testing steps

### Platform

iOS

### Flutter Doctor

```shell
name: facebook_app_events version: 0.19.0

Flutter 3.3.10 • channel unknown • unknown source
Framework • revision 135454af32 (6 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

**Comment by arg0nath** [comment]
What's the error you get after 3 minutes ?

**Comment by antonoddbit** [comment]
Hi @bsz0206 could you help us by describe the error you get, or any crash report?

**Comment by bsz0206** [comment]
No, there is no crash report. But Facebook Meta waits for the test events for about 3 minutes and then returns an error.
Apparently if the Facebook SDK is implemented correctly, when you open the app using Facebook deeplink, it fires some standard events automatically that reaches Facebook and mark the test successful. This does not happen with this Flutter add-on.

**Comment by bsz0206** [comment]
please re-open

**Comment by antonoddbit** [comment]
@bsz0206 We will re-check the SDK implementation on opening the app using deeplink

**Comment by bsz0206** [comment]
> @bsz0206 We will re-check the SDK implementation on opening the app using deeplink

any update on this one?

**Comment by antonoddbit** [comment]
@bsz0206 still working on it

**Comment by bsz0206** [comment]
> @bsz0206 still working on it

Github is marking it as stay so I put a comment to keep it open.

**Comment by antonoddbit** [comment]
Hi @bsz0206 We have checked the code and discuss about the issue, this not covered on our framework currently.

**Comment by bsz0206** [comment]
@antonoddbit does that mean this will not be added?

**Comment by antonoddbit** [comment]
@bsz0206 yes
