### ISSUE TITLE
[Bug]: tiktokloginresult{status: tiktokloginstatus.error, authcode: null, state: null, grantedpermissions: null, errorcode: 10017, errormessage: sdk error. please contact user support.}

### ISSUE THREAD

**Issue by NadineMuhamad** [oddbit/flutter_facebook_app_events#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to login with tiktok using flutter, it works fine on ios but when running on android i get this error.

### Expected Behavior

Login using tiktok in flutter android

### Platform

Android

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.5.1 21G83 darwin-x64, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by ferysyukur** [comment]
Hi @NadineMuhamad , Do you have related error or issue for facebook app event ? Because right now I just saw you have issue for tiktok login. I'll close this issue because it's not related with our plugin.
