### ISSUE TITLE
[Enhancement] Update facebook sdk to 7.x

### ISSUE THREAD

**Issue by bkraszewski** [oddbit/flutter_facebook_app_events#31]
Hello, 
Do you consider updating library to use the newest Facebook SDK for android/ios?
Not sure yet if any breaking changes happened there.

**Comment by alectogeek** [comment]
![изображение](https://user-images.githubusercontent.com/18165303/85942343-44fa1e80-b931-11ea-8055-a632f4303baf.png)
![изображение](https://user-images.githubusercontent.com/18165303/85942345-4b889600-b931-11ea-85e0-9e70b4045f9c.png)

**Comment by alectogeek** [comment]
@DennisAlund could you check it out?

**Comment by DennisAlund** [comment]
Sorry for late follow up on this. 

Hm, something seems strange. The facebook core SDK shouldn't happen to be on `4.x` using this plugin.  It's declared to use `>= 5.0` and `< 6.0`

https://github.com/oddbit/flutter_facebook_app_events/blob/48669e246a0d46b61038cc2875b8451ac092e327/android/build.gradle#L44

https://github.com/oddbit/flutter_facebook_app_events/blob/48669e246a0d46b61038cc2875b8451ac092e327/ios/facebook_app_events.podspec#L15

Which version of the flutter package are you using and which platform (Android or iOS) did you get the error? Both?

**Comment by DennisAlund** [comment]
Sorry, I missed a detail in the header regarding upgrading to **v7.0** ... I'll try to make a test for our own projects to do that.

**Comment by alectogeek** [comment]
@DennisAlund Thank you for your involvement in the resolving of the issue!

Actually, my FBSDKCoreKit version is 5.15.1, but Facebook requires at least 5.8 and higher to use the Advanced Automatic Matching feature (and I suppose will require a higher version for other features) and the have many bug fixes in their higher versions of the SDK btw.

I use the latest available version of the flutter package (0.6.0).

<img width="410" alt="изображение" src="https://user-images.githubusercontent.com/18165303/85983209-c57f5480-b9ef-11ea-98cf-1fe61bad7533.png">

**Comment by DennisAlund** [comment]
But `5.15.1` **is** a higher version than `5.8`

**Comment by DennisAlund** [comment]
Closing for now. Feel free to re-open as a new issue with either of the two things that has been discussed, if there still are issues.
 1. Upgrading to FBSDK v7
 1. Issues with pubspec.lock version
