### ISSUE TITLE
[Bug]: Update Facebook SDK to the latest version

### ISSUE THREAD

**Issue by wh120** [oddbit/flutter_facebook_app_events#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Facebook console show update error

### Expected Behavior

Act now on iOS 14.5 changes

All publishers must use Audience Network SDK 6.2.1 or later in order to monetize with iOS 14.5 users. (We also recommend Audience Network SDK 6.2.1 for iOS 14 users.) Within this version there are two requirements:

Implement the [setAdvertiserTrackingEnabled](https://developers.facebook.com/docs/audience-network/guides/advertising-tracking-enabled) flag, irrespective of the use of mediation, to inform us whether to use the data to deliver personalized ads.
Add the suggested [SKAdNetwork IDs](https://developers.facebook.com/docs/SKAdNetwork) to the Xcode project’s Info.plist in order for advertisers to measure the success of ad campaigns.
Read more on our [Meta for Developers](https://developers.facebook.com/blog/post/2020/10/29/preparing-our-partners-ios-14-latest-guidance-on-skadnetwork/) post

### Platform

iOS

### Flutter Doctor

```shell
--
```

**Comment by Abdo-ka** [comment]
if you know how can I solve this problem just notify me please cause I have same issue on my application

![photo_2023-08-23_15-03-32](https://github.com/oddbit/flutter_facebook_app_events/assets/91334009/ea69993f-7f74-4dc6-81ad-e8d293cab6fb)

**Comment by antonoddbit** [comment]
@wh120 @Abdo-ka We will investigate this issue, previously there is no report Ads.

**Comment by Abdo-ka** [comment]
> @wh120 @Abdo-ka We will investigate this issue, previously there is no report for Ads problems.

that's error happend from nearly time and casuses some problems like above image

**Comment by IamGanesh19** [comment]
Is there an update for this issue? This is also affecting one of my app. Can we have the facebook SDK updated to latest version?

**Comment by wwnOddbit** [comment]
I'm not really sure whether this is just a reminder in Facebook Console or an actual error in the plugin. Are you experiencing any syntax or runtime error? 

- Facebook App Events plugin currently uses FBAudienceNetwork version `~> 6.12` which should've met the minimum requirement of `6.2.1`.
Refer to file: `ios/facebook_app_events.podspec`

![image](https://github.com/oddbit/flutter_facebook_app_events/assets/91527455/5a1d988d-de11-4826-8a90-ae21be18d0c5)


- `setAdvertiserTrackingEnabled` flag has also being handled
Refer to file: `ios/Classes/SwiftFacebookAppEventsPlugin.swift`
<img width="775" alt="image" src="https://github.com/oddbit/flutter_facebook_app_events/assets/91527455/e62cbaa0-6631-4dc7-853f-fe82725c3989">

**Comment by bennidietz** [comment]
I also have the following error in the facebook console when using the latest package version:

"Update your apps to the latest Facebook SDK version:
Some of your apps need to be updated to the latest version of the Facebook SDK to continue showing ads to users on iOS 14.5 devices or later."

**Comment by antonoddbit** [comment]
@wh120 @IamGanesh19 @bennidietz Hi all, 
@wwnOddbit Thanks for detailed explanation about our setting that already handling the issue

Since our config already using latest FBSDK up to next Major update, could you assist us by providing:
1. FBAudienceNetwork  inside podfile.lock
2. FBSDK version inside podfile.lock
3. Xcode version

**Comment by Vjex** [comment]
@antonoddbit Hey, I'm also Facing the same issue.

here are the details you required :

1. FBAudienceNetwork --> - facebook_app_events (0.0.1):
    - FBAudienceNetwork (~> 6.12)
    - FBSDKCoreKit (~> 16.0)
    - Flutter
    
2.   - facebook_app_events (0.0.1):
    - FBAudienceNetwork (~> 6.12)
    - FBSDKCoreKit (~> 16.0)
    - Flutter
  - FBAEMKit (16.1.3):
    - FBSDKCoreKit_Basics (= 16.1.3)
  - FBAudienceNetwork (6.14.0)
  - FBSDKCoreKit (16.1.3):
    - FBAEMKit (= 16.1.3)
    - FBSDKCoreKit_Basics (= 16.1.3)
  - FBSDKCoreKit_Basics (16.1.3)
  
3. Xcode Version. -->  14.3

**Comment by wh120** [comment]
@antonoddbit 



```
 - facebook_app_events (0.0.1):
    - FBAudienceNetwork (~> 6.12)
    - FBSDKCoreKit (~> 16.0)
    - Flutter
  - FBAEMKit (16.1.3):
    - FBSDKCoreKit_Basics (= 16.1.3)
  - FBAudienceNetwork (6.14.0)
  - FBSDKCoreKit (16.1.3):
    - FBAEMKit (= 16.1.3)
    - FBSDKCoreKit_Basics (= 16.1.3)
  - FBSDKCoreKit_Basics (16.1.3)
```

(Xcode 14.2)

**Comment by antonoddbit** [comment]
@wh120 Since the SDK version met the minimum, and the flag have no issue have you add the id to your info.plist?

Please refer to https://developers.facebook.com/docs/setting-up/platform-setup/ios/SKAdNetwork

**Comment by antonoddbit** [comment]
@viniciusmiquelao still on investigating

**Comment by HamzaMihfad** [comment]
Is there any solution? facing the same problem

**Comment by duythien0912** [comment]
Hey guys, to solve the problem, run it on a real device until you observe an event on the dashboard.

<img width="753" alt="image" src="https://github.com/oddbit/flutter_facebook_app_events/assets/20185622/a12c1614-d86d-4387-8186-27c77f48f837">



Click on the three-dot button and select "Mark as complete."

<img width="377" alt="image" src="https://github.com/oddbit/flutter_facebook_app_events/assets/20185622/7e853316-e397-4bcd-920e-2d7e4230ca6f">

After that, the Facebook SDK tab will display this.

<img width="981" alt="image" src="https://github.com/oddbit/flutter_facebook_app_events/assets/20185622/e60a9821-48ae-4e2c-8c04-1a8b2c4c7800">

**Comment by duythien0912** [comment]
@HamzaMihfad it take some time. but remember `run it on a real iphone until you observe an event on the dashboard`

**Comment by antonoddbit** [comment]
@HamzaMihfad did the error message on your console disappear by running on real iPhone?

**Comment by antonoddbit** [comment]
@viniciusmiquelao please create new issue, looks like it's a different issue.
