### ISSUE TITLE
[Bug]: I got Asset validation failed error after implement flutter_facebook_app_events

### ISSUE THREAD

**Issue by MetehanBass** [oddbit/flutter_facebook_app_events#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After implementing flutter_facebook_app_events to transfer events to Facebook, there is no problem when building and archiving, but when I distrubute to upload to testflight, I get the following error.

<img width="1444" alt="Screenshot 2023-08-31 at 15 40 06" src="https://github.com/oddbit/flutter_facebook_app_events/assets/32189650/35e8ff52-06e8-4db3-8b0d-8aebad7ec9df">

Is there any conflict with facebook_ios_sdk and flutter_facebook_app_events? What should I do?

Thanks.

### Expected Behavior

I expect to be able to upload it to Testflight and test it.

### Steps To Reproduce

Xcode version: 14.3.1

It is my build phases settings below. 

<img width="701" alt="Screenshot 2023-08-31 at 17 20 25" src="https://github.com/oddbit/flutter_facebook_app_events/assets/32189650/eedb1494-0a75-45b7-8af6-6050cf54f97c">

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-TR)
    • Flutter version 3.7.12 on channel stable at /Users/ugurcan/Desktop/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (5 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/ugurcan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by MetehanBass** [comment]
Asset validation failed -> FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics.framework
Asset validation failed -> FBAEMKit.framework/FBAEMKit
Asset validation failed -> FBSDKCoreKit.framework.framework/FBSDKCoreKit

**Comment by MetehanBass** [comment]
<img width="1440" alt="Screenshot 2023-09-01 at 11 35 37" src="https://github.com/oddbit/flutter_facebook_app_events/assets/32189650/6e943983-2037-4c9c-b2d1-b659aec50ae3">

What is wrong with facebook_app_events?

**Comment by MetehanBass** [comment]
<img width="1188" alt="Screenshot 2023-09-04 at 10 24 12" src="https://github.com/oddbit/flutter_facebook_app_events/assets/32189650/e12ff8db-ec6d-4602-95b0-9ff1c4954542">

I fixed error on facebook_app_events with manually locating the package but its still throwing error when I try to distribute to testflight

**Comment by MetehanBass** [comment]
error log 

warning: Conflicting parseable interfaces for Swift Module FBSDKCoreKit: /Users/ugurcan/Library/Developer/Xcode/DerivedData/Runner-cwlltxgcsxqiyvfovdsmetlzlkzz/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FBSDKCoreKit.framework/Modules/FBSDKCoreKit.swiftmodule/arm64-apple-ios.private.swiftinterface and /Users/ugurcan/Library/Developer/Xcode/DerivedData/Runner-cwlltxgcsxqiyvfovdsmetlzlkzz/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FBSDKCoreKit/FBSDKCoreKit.framework/Modules/FBSDKCoreKit.swiftmodule/arm64-apple-ios.private.swiftinterface
note: while processing /Users/ugurcan/Library/Developer/Xcode/DerivedData/Runner-cwlltxgcsxqiyvfovdsmetlzlkzz/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/facebook_app_events/facebook_app_events.framework/facebook_app_events(SwiftFacebookAppEventsPlugin.o)

**Comment by antonoddbit** [comment]
@MetehanBass what version of flutter_facebook_app_events used?

Conflicting parseable interfaces usually is local problem that could fixed by removing all your derived data and try clean build again.

**Comment by MetehanBass** [comment]
I removed many time my derived data and build. But after removing facebook_ios_sdk, the problem gone. Should I use facebook_ios_sdk and flutter_facebook_app_events same time? Or I do not need to use facebook_ios_sdk while I am using flutter_facebook_app_events

**Comment by antonoddbit** [comment]
@MetehanBass You only need one flutter_facebook_app_events since it including FBSDK
