### ISSUE TITLE
[Bug]: All Events are shown in event manager but Purchase Event

### ISSUE THREAD

**Issue by kishan-hit-infotech** [oddbit/flutter_facebook_app_events#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I Implemented these events:

- logViewContent
- logAddToCart
- logEvent (remove_from_cart)
- logViewContent
- logViewCart
- logInitiatedCheckout
- logPurchase

From this, all other events other than purchase events can be seen in the events manager.

### Expected Behavior

Show purchase events in events manager.

### Steps To Reproduce

```
FacebookAppEvents().logPurchase(
  amount: cart.total.toDouble(),
  currency: AppState.currency!.code,
  parameters: {
    'lines': cart.lines.map((line) {
      return {
        'quantity': line.quantity,
        'item_id': '${line.product.id}',
        'item_name': line.product.name,
        'item_brand': line.product.vendor?.name,
        'price': line.product.includingTax,
        'currency': AppState.currency!.code,
      };
    }).toList()
  },
),
```

### Platform

Android, iOS

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.13.3, on macOS 12.6.8 21G725 darwin-x64, locale en-IN)
    • Flutter version 3.13.3 on channel stable at /Users/os/Developer/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (6 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/os/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/os/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/os/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.8 21G725 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by seceba** [comment]
regards, love, hello; 

Hi I don't know if it's the same problem. I didn't want to open another issue for now.

It automatically tracks app installations. However, it cannot track payments on the Android side, it only shows Ios.
I have activated the automatic in app purchase tracking option in the console.

I don't use logPurchase(), **shouldn't it automatically track in-app-purchase?**

**Comment by seceba** [comment]
At the same time, some errors appear in the console, could it be related to this? As I said, I expect it to receive Purchase events automatically, I do not send any manual log. And everything is as it should be on the Ios side, but there are no purchase events for android.

![Ekran Resmi 2023-09-12 14 04 19](https://github.com/oddbit/flutter_facebook_app_events/assets/20662454/5a0f2872-eee9-4b52-b7db-5b4039afb78d)

**Comment by kishan-hit-infotech** [comment]
@seceba  Regarding In-App Purchase this could be some other issue. In my case, I have an E-commerce app, and I disabled auto logging and added `logPurchase()` after successful payment. So it should log the event but it doesn't.

For another issue of yours, I have the same issue where it says missing Currency parameter even though I am passing currency and amount in all events that need those two. Also, this Says "No longer detected" and every time I see the last detected date, it is always the current date.

<img width="2095" alt="image" src="https://github.com/oddbit/flutter_facebook_app_events/assets/114082175/524b3ad0-9cfa-4a12-ae0d-827ac6d3b3f8">

**Comment by seceba** [comment]
Ok then, to summarise, we are getting Missing fb_mobile_purchase error in diagnostics regardless of whether the purchase events are received automatically or sent manually.

On my side (automatic side) IOS purchase events can be received while Androids are not visible, and on your side (manual side) none of them are visible, right? @kishan-hit-infotech

**Comment by kishan-hit-infotech** [comment]
Yes, that's sums it up.

**Comment by antonoddbit** [comment]
@seceba @kishan-hit-infotech we will investigate about purchasing event. Thanks for detailed explanation

**Comment by kishan-hit-infotech** [comment]
## Update

When I first implemented this I did not disable auto logging and I manually logged my events mentioned in the original issue post.

After I faced the issue I disabled auto logging and I also changed `logPurchase` event with my custom event called `custom_purchase_event`. After that, I tested by ordering products 7-8 times from both iOS and Android. It has been more than 24 hours and I also do not see this custom event as well. The recorded events are as below screenshot.

<img width="2078" alt="image" src="https://github.com/oddbit/flutter_facebook_app_events/assets/114082175/f28159d3-05d9-4103-a3ef-96c90a247342">


### Also, I am logging into Firebase analytics from the same function there I can see all my events.


<details>
  <summary><h4>This is my code for logging events</h4></summary>
```dart

import 'package:app_tracking_transparency/app_tracking_transparency.dart';
import 'package:facebook_app_events/facebook_app_events.dart';
import 'package:firebase_analytics/firebase_analytics.dart';

import '../models/product/cart/cart.dart';
import '../models/product/product.dart';
import '../shared/app_state.dart';

class LogEventService {
  static late final FacebookAppEvents _facebook;
  static late final FirebaseAnalytics _google;

  static Future<void> init() async {
    if (AppState.flavor.isNotLive) return;
    _facebook = FacebookAppEvents();
    final status = await AppTrackingTransparency.requestTrackingAuthorization();
    _facebook.setAdvertiserTracking(enabled: status == TrackingStatus.authorized);
    if (!AppState.isHuaweiDevice) _google = FirebaseAnalytics.instance;
  }

  static Future<void> logViewProduct({required Product product}) async {
    if (AppState.flavor.isNotLive) return;
    await Future.wait([
      _facebook.logViewContent(
        type: 'product',
        currency: AppState.currency!.code,
        price: product.includingTax.toDouble(),
        content: {
          'item_id': '${product.id}',
          'item_name': product.name,
          'item_brand': product.vendor?.name,
        },
      ),
      if (!AppState.isHuaweiDevice) ...[
        _google.logViewItem(items: [
          AnalyticsEventItem(
            itemId: '${product.id}',
            itemName: product.name,
            currency: AppState.currency!.code,
            price: product.includingTax,
            itemBrand: product.vendor?.name,
          )
        ]),
      ],
    ]);
  }

  static Future<void> addToCart({
    required String id,
    required String name,
    required num price,
    required int quantity,
  }) async {
    if (AppState.flavor.isNotLive) return;
    await Future.wait([
      _facebook.logAddToCart(
        id: id,
        type: 'product',
        currency: AppState.currency!.code,
        price: price.toDouble(),
        content: {
          'item_name': name,
          'quantity': quantity,
        },
      ),
      if (!AppState.isHuaweiDevice) ...[
        _google.logAddToCart(
          currency: AppState.currency!.code,
          value: price.toDouble(),
          items: [
            AnalyticsEventItem(
              itemId: id,
              itemName: name,
              quantity: quantity,
            )
          ],
        ),
      ],
    ]);
  }

  static Future<void> removeFromCart({
    required String id,
    required String name,
    required num price,
    required int quantity,
  }) async {
    if (AppState.flavor.isNotLive) return;
    await Future.wait([
      _facebook.logEvent(
        name: 'remove_from_cart',
        parameters: {
          'currency': AppState.currency!.code,
          'price': price.toDouble(),
          'item_id': id,
          'item_name': name,
          'quantity': quantity,
        },
      ),
      if (!AppState.isHuaweiDevice) ...[
        _google.logRemoveFromCart(
          currency: AppState.currency!.code,
          value: price.toDouble(),
          items: [
            AnalyticsEventItem(
              itemId: id,
              itemName: name,
              quantity: quantity,
            )
          ],
        ),
      ],
    ]);
  }

  static Future<void> viewCart(Cart cart) async {
    if (AppState.flavor.isNotLive) return;
    await Future.wait([
      _facebook.logViewContent(
        type: 'cart',
        currency: AppState.currency!.code,
        price: cart.total.toDouble(),
        content: {
          'lines': cart.lines.map((line) {
            return {
              'quantity': line.quantity,
              'item_id': '${line.product.id}',
              'item_name': line.product.name,
              'item_brand': line.product.vendor?.name,
              'price': line.product.includingTax,
              'currency': AppState.currency!.code,
            };
          }).toList()
        },
      ),
      if (!AppState.isHuaweiDevice) ...[
        _google.logViewCart(
          currency: AppState.currency!.code,
          value: cart.total.toDouble(),
          items: cart.lines.map((line) {
            return AnalyticsEventItem(
              quantity: line.quantity,
              itemId: '${line.product.id}',
              itemName: line.product.name,
              itemBrand: line.product.vendor?.name,
              price: line.product.includingTax,
              currency: AppState.currency!.code,
            );
          }).toList(),
        ),
      ],
    ]);
  }

  static Future<void> beginCheckout(Cart cart) async {
    if (AppState.flavor.isNotLive) return;
    await Future.wait([
      _facebook.logInitiatedCheckout(
        paymentInfoAvailable: false,
        currency: AppState.currency!.code,
        totalPrice: cart.total.toDouble(),
        numItems: cart.productCount,
      ),
      if (!AppState.isHuaweiDevice) ...[
        _google.logBeginCheckout(
          currency: AppState.currency!.code,
          value: cart.total.toDouble(),
          items: cart.lines.map((line) {
            return AnalyticsEventItem(
              quantity: line.quantity,
              itemId: '${line.product.id}',
              itemName: line.product.name,
              itemBrand: line.product.vendor?.name,
              price: line.product.includingTax,
              currency: AppState.currency!.code,
            );
          }).toList(),
        ),
      ],
    ]);
  }

  static Future<void> purchase({required Cart cart}) async {
    if (AppState.flavor.isNotLive) return;
    Future.wait([
      _facebook.logEvent(
        name: 'custom_purchase_event',
        parameters: {
          'currency': AppState.currency!.code,
          'price': cart.total.toDouble(),
          'lines': cart.lines.map((line) {
            return {
              'quantity': line.quantity,
              'item_id': '${line.product.id}',
              'item_name': line.product.name,
              'item_brand': line.product.vendor?.name,
              'price': line.product.includingTax,
              'currency': AppState.currency!.code,
            };
          }).toList()
        },
      ),
      if (!AppState.isHuaweiDevice) ...[
        _google.logPurchase(
          value: cart.total.toDouble(),
          currency: AppState.currency!.code,
          items: cart.lines.map((line) {
            return AnalyticsEventItem(
              quantity: line.quantity,
              itemId: '${line.product.id}',
              itemName: line.product.name,
              itemBrand: line.product.vendor?.name,
              price: line.product.includingTax,
              currency: AppState.currency!.code,
            );
          }).toList(),
        ),
      ],
    ]);
  }
}

```
</details>

**Comment by antonoddbit** [comment]
@kishan-hit-infotech @seceba have you tried using logPurchase(), testing it on real device.
Please wait up to 20 minutes to all event start showing in the dashboard?

**Comment by Youssef-Hm** [comment]
> @kishan-hit-infotech @seceba have you tried using logPurchase(), testing it on real device. Please wait up to 20 minutes to all event start showing in the dashboard?
no i just to track only users who install app from facebook campaign 
this package will help me in that or i have to use facebook sdk

**Comment by kishan-hit-infotech** [comment]
I found that issue in real devices. Both android and iOS apps were live on playstore, appstore, and huawei App Gallery.

Even the physical device I used to test had installed the latest version of facebook.

**Comment by kishan-hit-infotech** [comment]
I will look for any issue in the source code today. I'll update here if I find something.

**Comment by kishan-hit-infotech** [comment]
I checked the code and found out that I was passing the wrong data type. In the parameter, I passed a list that is not handled by `createBundleFromMap` in Android or direct iOS Facebook SDK.

I think we should add that info as the documentation somewhere for a new developer like myself who is not very familiar with Facebook Events or Facebook SDK in general.

I successfully logged the event in facebook by just jsonEncoding my data before passing it as a parameter.

**Comment by seceba** [comment]
> @kishan-hit-infotech @seceba have you tried using logPurchase(), testing it on real device. Please wait up to 20 minutes to all event start showing in the dashboard?

Hello, we already have a live app on ios and android. I do not keep any log manually, it is set to full automatic.

All events are coming on the ios side and android side, only the purchase event is not coming on android.

**Comment by kishan-hit-infotech** [comment]
@seceba  Did you complete these steps?

[verification](https://developers.facebook.com/docs/app-events/getting-started-app-events-android/verification) 
[credentials](https://developers.facebook.com/docs/app-events/getting-started-app-events-android/credentials)

**Comment by seceba** [comment]
@kishan-hit-infotech  Yes, it's all settings, I rebuilt and updated anyway but no improvement. I don't think the missing fb_purchase_currency error is due to this.

In your scenario, is logPurchase() working now and did you get rid of the missing errors?

**Comment by kishan-hit-infotech** [comment]
About that `fb_purchase_currency` is still there but in "Previously Detected" section.

<img width="2134" alt="image" src="https://github.com/oddbit/flutter_facebook_app_events/assets/114082175/09fbffe9-7c69-431d-bb49-837247cd7ef0">

---

Although I can see `fb_currency` parameter in sampled activities data.

<img width="747" alt="image" src="https://github.com/oddbit/flutter_facebook_app_events/assets/114082175/ced0f9ec-dff1-42eb-a114-43d1b918eb86">

**Comment by seceba** [comment]
Android does not log Purchases in any way on the automatic side.

I finally solved it by doing logPurchase manually, but I really wonder why payments are not logged automatically.

**Comment by kishan-hit-infotech** [comment]
Any Update to this?

**Comment by antonoddbit** [comment]
@kishan-hit-infotech have you debug your code when calling logPurchase(), Do debugger could show AppState.currency!.code value?

**Comment by kishan-hit-infotech** [comment]
@antonoddbit  Yes, I checked in debug mode as well as in Facebook events in the Event Manager. There also I can see the currency parameter (check the screenshot above).

**Comment by antonoddbit** [comment]
Hi @kishan-hit-infotech, could you try to call the method manually and test on the console after 15 minutes

**Comment by kishan-hit-infotech** [comment]
I am already calling all events manually.

**Comment by cka29** [comment]
@kishan-hit-infotech any news on this one? I have a similar issue where my `logPurchase` events are not ALL shown. Only a few like ~20% of those I sent, will appear in the dashboard.
