### ISSUE TITLE
[Bug]: Android v0.2.0 Needs upgrade Needs upgrade The latest version is 13.0.0

### ISSUE THREAD

**Issue by HamzaMihfad** [oddbit/flutter_facebook_app_events#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The package not sending events to facebook, and I got this error on facebook:
Android v0.2.0 Needs upgrade Needs upgrade The latest version is 13.0.0

### Expected Behavior

It should log events to facebook

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5 22G74 darwin-arm64, locale en-MA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

**Comment by aladeenuthy** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> The package not sending events to facebook, and I got this error on facebook: Android v0.2.0 Needs upgrade Needs upgrade The latest version is 13.0.0
> 
> ### Expected Behavior
> It should log events to facebook
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Platform
> _No response_
> 
> ### Flutter Doctor
> ```shell
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.13.2, on macOS 13.5 22G74 darwin-arm64, locale en-MA)
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2022.2)
> [✓] VS Code (version 1.81.1)
> [✓] Connected device (4 available)
> [✓] Network resources
> 
> • No issues found!
> ```

How did you fix this issue @HamzaMihfad
