### ISSUE TITLE
[Bug]: Update flutter_facebook_app_events to Support the Latest Facebook SDK

### ISSUE THREAD

**Issue by Tsovinar2000** [oddbit/flutter_facebook_app_events#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, the flutter_facebook_app_events package is using an older version of the Facebook SDK. This version may not fully support the changes introduced in iOS 14.5 and later, specifically regarding user privacy and ad tracking. As a result, there may be issues with ad serving on devices running iOS 14.5 or later.
<img width="1011" alt="Screen Shot 2023-10-30 at 12 28 45 PM" src="https://github.com/oddbit/flutter_facebook_app_events/assets/58556060/a476e728-f78e-46ec-bce5-bb1222acc60d">

### Expected Behavior

With the recent changes to the Facebook SDK, the flutter_facebook_app_events package should be updated to support the latest version of the Facebook SDK. This update is crucial to ensure the proper functioning of the app's Facebook Ads on devices running iOS 14.5 or later.
Also I don't get testing event . But the Android works perfectly fine.

### Steps To Reproduce

Install the flutter_facebook_app_events package in a Flutter project.
Configure the package with your Facebook App ID and other necessary settings.
Create a test Flutter application that includes Facebook Ads using the flutter_facebook_app_events package.
Deploy the application to a physical device running iOS 14.5 or later.
Interact with the app, including viewing and interacting with ads.

### Platform

iOS

### Flutter Doctor

```shell
Everything is ok there.
```

**Comment by AlexFox63** [comment]
What is the approximate time of releasing the new version of the package? Because it's a meaningful change and don't want to fork the package because of that...

**Comment by Tsovinar2000** [comment]
> What is the approximate time of releasing the new version of the package? Because it's a meaningful change and don't want to fork the package because of that...

**Comment by antonoddbit** [comment]
@Tsovinar2000 this issue already mentioned in https://github.com/oddbit/flutter_facebook_app_events/issues/311

**Comment by Bamschool** [comment]
@Tsovinar2000 

How could you solve it? please let me know
I really appreciate you if you help me!!
