### ISSUE TITLE
[Bug]: Error Sending AppEvents: Invalid OAuth Access Token Signature (Code 190)

### ISSUE THREAD

**Issue by Tsovinar2000** [oddbit/flutter_facebook_app_events#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to send AppEvents using the Facebook SDK, the following error is encountered:

FBSDKLog: Failed to send AppEvents: Error Domain=com.facebook.sdk.core Code=8 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Invalid OAuth access token signature., com.facebook.sdk:FBSDKGraphRequestErrorParsedJSONResponseKey={
    body =     {
        error =         {
            code = 190;
            "fbtrace_id" = "AoGfVrpbmYeSWZMQ_AdQAwa";
            message = "Invalid OAuth access token signature.";
            type = OAuthException;
        };
    };
    code = 400;
}, com.facebook.sdk:FBSDKGraphRequestErrorHTTPStatusCodeKey=400, com.facebook.sdk:FBSDKGraphRequestErrorKey=0, com.facebook.sdk:FBSDKGraphRequestErrorGraphErrorCodeKey=190}

### Expected Behavior

AppEvents should be sent to Facebook without any errors.

### Steps To Reproduce

In iOS env. Run the application that uses the Facebook SDK for sending AppEvents.
Attempt to send AppEvents to Facebook using the SDK.

### Platform

iOS

### Flutter Doctor

```shell
Everything is ok here
```

**Comment by antonoddbit** [comment]
Have you tried different connection? Please re-check also your facebook id in info.plist

**Comment by Tsovinar2000** [comment]
> Have you tried different connection? Please re-check also your facebook id in info.plist

Yes, on Android it works fine , and I get realtime events in facebook. 
But for iOS it doesn't work. Id is correct.

**Comment by Tsovinar2000** [comment]
@antonoddbit Hi. Any news form this issue ?

**Comment by antonoddbit** [comment]
@Tsovinar2000 Currently we cannot reproduce this issue
