### ISSUE TITLE
[Bug]: onAttachedToEngine not called

### ISSUE THREAD

**Issue by miroirstudiosrl** [oddbit/flutter_facebook_app_events#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The method `onAttachedToEngine` inside `FacebookAppEventsPlugin.kt` is not getting called.
This is causing the error `kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized` to be thrown when I try to call the `logEvent` method.

### Expected Behavior

`appEventsLogger` should be correctly initialized.

### Steps To Reproduce

I've tried to insert a log `Log.d(logTag, "onAttachedToEngine called")` inside the `onAttachedToEngine` method and I get not output.
The plugin is correctly installed inside `pubspec.yml`  (`facebook_app_events: ^0.19.0`) and I tried to run `flutter clean` and rerun the app multiple times.

### Platform

Android

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Versione 10.0.22631.2715], locale it-IT)
    • Flutter version 3.16.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (7 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Miroirstudio\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[...]
```

**Comment by ferysyukur** [comment]
Hi @miroirstudiosrl , sorry for late response. I'll check this bug today. 😊

**Comment by miroirstudiosrl** [comment]
> Hi @miroirstudiosrl , sorry for late response. I'll check this bug today. 😊

Hello @ferysyukur. Any news?

**Comment by ferysyukur** [comment]
Hi @miroirstudiosrl , I had test our example and I couldn't reproduce this issue. I could get error when I haven't added facebook_client_token on AndroidManifest. Did you test and check our example project first and please see our documentation ?
Please check our closed issue. [Here](https://github.com/oddbit/flutter_facebook_app_events/issues?q=is%3Aissue+is%3Aclosed+appEventsLogger)
