### ISSUE TITLE
[Bug]: An error appears when reinstalling pods (FBAudienceNetwork.xcframework/Info.plist)

### ISSUE THREAD

**Issue by ivangalkindeveloper** [oddbit/flutter_facebook_app_events#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When reinstalling pods

`pod setup && pod install --repo-update && pod cache clean --all && pod update`

an error appears:

```
[!] The plist file at path `/Users/.../<project>/ios/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.xcframework/Info.plist` doesn't exist.
```

### Expected Behavior

This error has never happened before when reinstalling pods.

### Steps To Reproduce

1. `cd ios && rm -rf Pods && rm -rf Podfile.lock && rm -rf Flutter/Flutter.podspec`
2. `cd ios && pod deintegrate && sudo gem uninstall cocoapods && sudo gem uninstall cocoapods-core && sudo gem uninstall cocoapods-downloader && sudo gem install cocoapods`
3. `ios && pod setup && pod install --repo-update && pod cache clean --all && pod update`

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale
    ru-RU)
    • Flutter version 3.16.9 on channel stable at
      /Users/ivangalkin/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (12 дней назад), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ivangalkin/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • 21EB6181-6B89-4945-931A-55C68378896A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by ArkeshGKalathiya** [comment]
For anyone experiencing this issue, following steps fixed issue on my end

I downloaded matching version of the pod from the 

https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/add-sdk/

and then copied /DownloadFolder/FBAudienceNetwork/Static/FBAudienceNetwork.xcframework/info.plist to $HOME/Library/Caches/CocoaPods/Pods/Release/FBAudienceNetwork/<YOUR_VERSION>/Static/FBAudienceNetwork.xcframework

**Comment by ivangalkindeveloper** [comment]
I checked now, everything is fine
The original package has apparently been corrected
Сlosing the bug

**Comment by ArkeshGKalathiya** [comment]
@ivangalkindeveloper 

I believe issue was related to CocoaPods, I tried this evening and issue was still there, so I fixed it by copying info.plist file, but then I started running into other issues, and when I checked cocoapods cache, some folders were empty and seemed like files were not downloaded. and then I had to remove cocoapods and re-install it. And everything worked fine.
