### ISSUE TITLE
[Request]: Support App Privacy manifest

### ISSUE THREAD

**Issue by Samo8** [oddbit/flutter_facebook_app_events#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As flutter_facebook_app_events is using FBSDKCoreKit dependency on iOS side, which is library that needs to include Privacy manifest (https://developer.apple.com/support/third-party-SDK-requirements/). Currently version of FBSDKCoreKit in flutter_facebook_app_events does not include Privacy manifest.

### Expected Behavior

Please see the issue on FBSDKCoreKit (https://github.com/facebook/facebook-ios-sdk/issues/2264) and update to according that will include Privacy manifest version when released.

Thank you.

### Platform

iOS

### Flutter Doctor

```shell
no need of flutter doctor output
```

**Comment by stuartmorgan** [comment]
`FBAudienceNetwork` also has Required Reason API usage that requires a privacy manifest, and that was added in 6.15 according to [the changelog](https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/changelog/), which this plugin isn't using.

Apps that use this plugin will be subject to rejection from the App Store starting May 1st without a solution for privacy manifests.

**Comment by taufiq-husain** [comment]
We need this package to be up-to-date. Anybody else have alternatives?

**Comment by antonoddbit** [comment]
@taufiq-husain just bump another issue, will check on this.
@stuartmorgan we should be releasing another version before that date

**Comment by antonoddbit** [comment]
@Samo8 FBSDK just add the Privacy Manifest on version 17.0.0 need some bumping to this version
