### ISSUE TITLE
[Bug]: looking for FBSDKCoreKit 16.3.1, currently set to 16.2.1

### ISSUE THREAD

**Issue by klivin** [oddbit/flutter_facebook_app_events#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot install via `pod install` after updating pubs as there's a newer Core Kit:

[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 16.2.1)

    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 6.0.4, which depends on
      FBSDKLoginKit (~> 16.3.1) was resolved to 16.3.1, which depends on
        FBSDKCoreKit (= 16.3.1)

### Expected Behavior

Should support latest Facebook sdk

### Steps To Reproduce

updating 
the pod spec to  
```
 s.dependency 'FBSDKCoreKit', '~> 16.3.1'
```
fixes the issue for me

### Platform

iOS

### Flutter Doctor

```shell
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.87.2)
[✓] Connected device (4 available)            
    ! Error: Browsing on the local area network for 12 Brain. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

**Comment by antonoddbit** [comment]
Hi @klivin currently no issues, but we already have some PR for that change.
Will check on it immediately

**Comment by VasilisPH** [comment]
I am also experiencing issues with exporting .ipa files and building my app in the simulator due to this bug.

**Comment by aggeloskoutanis** [comment]
Same here. Would be nice if this is merged soon.

**Comment by antonoddbit** [comment]
Update library to 17.0 in newest version

**Comment by antonengelhardt** [comment]
@antonoddbit Can you also please create a new release?
