### ISSUE TITLE
[Bug]: Apple gives ITMS-91053: Missing API declaration

### ISSUE THREAD

**Issue by taufiq-husain** [oddbit/flutter_facebook_app_events#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We recently submitted our Flutter app (iOS) to the AppStore and received the following email:

> Hello,
> 
> We noticed one or more issues with a recent submission for App Store review for the following app:
> 
> 
> APPNAME
> Version 0.2.3
> Build 26
> Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the “Runner” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the “Runner” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the “Runner” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategorySystemBootTime. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> Apple Developer Relations

I raised the issue with Flutter team and they deduced it to be a problem with this package only (at least for my project). One of the Flutter team members commented on another issue on this package referencing it and you suggested I raise it as a separate issue so here it is.

### Expected Behavior

We shouldn't be getting these warnings from Apple.

Note: You'll need to update your package with the fixes asap. Otherwise this package won't be usable in our projects or any other project that supports iOS after May 24th, 2024.

### Steps To Reproduce

1. Just add this package to any flutter app.
2. Submit the app to the Apple App Store.
3. Apple will email you the same warnings.

### Platform

iOS

### Flutter Doctor

```shell
N/A. Everything is working as usual otherwise.
```

**Comment by taufiq-husain** [comment]
References:

https://github.com/flutter/flutter/issues/145269

**Comment by antonoddbit** [comment]
Hi @taufiq-husain, We already checking about this on #342

**Comment by JayDropOn** [comment]
I am getting the same warning from apple after releasing new build.

**Comment by antonoddbit** [comment]
@taufiq-husain FBSDK just add the Privacy Manifest on version 17.0.0 need some bumping to this version

**Comment by antonoddbit** [comment]
We released v0.19.2 that using FBSDCKCoreKit that already adding Privacy Manifest, please try it.

**Comment by deepak-agendaboa** [comment]
@taufiq-husain Did you try the latest version 0.19.2?
