### ISSUE TITLE
Unable to build for ios

### ISSUE THREAD

**Issue by lohithkumar95** [oddbit/flutter_facebook_app_events#35]
Hi ,
After adding the `flutter_facebook_app_events` package in my flutter project, i am unable to build for ios.
i get the below error.

> [!] The following Swift pods cannot yet be integrated as static libraries:
> 
>     The Swift pod `facebook_app_events` depends upon `FBSDKCoreKit`, which does not define modules. To opt into those targets generating module maps (which
>     is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify
>     `:modular_headers => true` for particular dependencies.

Can someone help me on this?
i am stuck for long. thanks in advance.

## Your Environment
* Output from `flutter doctor`

> [✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.1 19B88, locale en-GB)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.1)
> [✓] Android Studio (version 3.6)
> [✓] VS Code (version 1.45.1)
> [✓] Connected device (1 available)

• No issues found!

**Comment by dchumpitaz** [comment]
Same issue here:

flutter doctor
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G2022, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

Compiling:
The Swift pod `facebook_app_events` depends upon `FBSDKCoreKit`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by DennisAlund** [comment]
Thank you for that answer @dchumpitaz. Did that solve your issue @lohithkumar95 ?

**Comment by lohithkumar95** [comment]
@DennisAlund in my case i added `use_frameworks!` in the podfile. And it solved the issue.

**Comment by DennisAlund** [comment]
Thank you for following up with your findings and providing that information for future reference ❤️
