### ISSUE TITLE
[Bug]: Privacy manifest file for iOS is missing

### ISSUE THREAD

**Issue by oremlawi** [oddbit/flutter_facebook_app_events#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App being rejected by AppStore connect as long as `PrivacyInfo.xcprivacy`is missing.

### Expected Behavior

Kindly consider adding a privacy manifest to your library following the new apple policy by adding `PrivacyInfo.xcprivacy` file to your project.

For more information, please check [Apple's documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).

### Platform

iOS

### Flutter Doctor

```shell
[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
```

**Comment by oremlawi** [comment]
Honestly my app wan't rejected, but my request was just a reminder to avoid app rejection for the future releases.

And currently we still build using 0.18.3 as building on 0.19.1 is causing crash on iOS.

**Comment by antonoddbit** [comment]
@oremlawi could you share what crash on newest version, we just release 0.19.2 that using newest FBSDK that support privacy manifest.

**Comment by oremlawi** [comment]
Yes sure, but please note that in my case I had to edit locally the SwiftFacebookAppEventsPlugin.swift in version 0.18.3 file and add the if #availble condition to bypass another bug:

**Bug for all versions:**
Swift Compiler Error (Xcode): 'setAdvertiserTrackingEnabled' is only available in iOS 12.0 or newer

**Proposed solution:**
```
    private func handleSetAdvertiserTracking(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        let arguments = call.arguments as? [String: Any] ?? [String: Any]()
        let enabled = arguments["enabled"] as! Bool
        let collectId = arguments["collectId"] as! Bool
        if #available(iOS 12.0, *) {
            FBAdSettings.setAdvertiserTrackingEnabled(enabled)
            Settings.shared.isAdvertiserTrackingEnabled = enabled
            Settings.shared.isAdvertiserIDCollectionEnabled = collectId
        } else {
            // Fallback on earlier versions
        }

        result(nil)
    }
```



**Bug in version 0.19.1+**
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In snapshot (Podfile.lock):
    FBSDKCoreKit (= 15.1.0, ~> 15.1)

  In Podfile:
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 17.0)


Looks like it is incompatibility issue, so I had to rollback to 0.18.3 and correction the first bug locally.

**Comment by antonoddbit** [comment]
Hi @oremlawi have you fix the incompatibility issue and try newest version?

**Comment by antonoddbit** [comment]
Hi @aquinoartur thanks for updating, could you provide me the screenshoots? So I could check deeper about the issue

**Comment by gianlucaschoefer** [comment]
@antonoddbit we also got warnings from appstore connect on our release last week. We are getting worried that the next release will be rejected. Here the messages we received. We are on v19.2.0

![Screenshot_20240502-120555](https://github.com/oddbit/flutter_facebook_app_events/assets/22167380/3b8b1540-9350-47ff-afe3-666b1c1599df)
![Screenshot_20240502-120544](https://github.com/oddbit/flutter_facebook_app_events/assets/22167380/ecce3719-0a02-426e-acac-6287beb1a755)

**Comment by antonoddbit** [comment]
Hi @gianlucaschoefer have you generate the privacy file on your project for these API Declaration.
Here documentation about the privacy manifest: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
Here WWDC link about privacy manifest:
https://developer.apple.com/videos/play/wwdc2023/10060/?time=88

**Comment by gianlucaschoefer** [comment]
This was a bug related to how flutter created iOS-Apps were being reviewed. This has been resolved and our app was successfully approved. Thank you, nevertheless!

**Comment by shahmirzali49** [comment]
@gianlucaschoefer how to did you solve this issue?

**Comment by gianlucaschoefer** [comment]
@shahmirzali49 as I said above, this was an issue with how the iOS review processes dealt with Flutter-SDK [which was resolved on their side](https://github.com/flutter/flutter/issues/145269#issuecomment-2082940791). Since then we haven't had any issues. I assume the manifest file is correctly provided by the facebook-SDK.
