### ISSUE TITLE
[Bug]: I am not able to add parameter, but event name is created

### ISSUE THREAD

**Issue by rp131318** [oddbit/flutter_facebook_app_events#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am adding event name and parameter in meta pixel but only event name is showing in meta console parameter is not showing.

### Expected Behavior

Event and parameter both should show in the meta console

### Platform

Android

### Flutter Doctor

```shell
Event and parameter both should show in the meta console
```

**Comment by antonoddbit** [comment]
@rp131318 Could you elaborate more about this? 
Showing line of code for when adding name and parameter, screen shot of you checking the event name in meta console could help.
