### ISSUE TITLE
[Request]: adding activateApp for manual tracking

### ISSUE THREAD

**Issue by Matthew-simmsy** [oddbit/flutter_facebook_app_events#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to integrate RevenueCat events with Facebook ads. In the [docs](https://www.revenuecat.com/docs/integrations/attribution/facebook-ads#track-install-and-usage-events) we see that activateApp() will need to be called as all client side tracking needs to be turned off. I cannot see this event in this package? Could we get this added or is there another solution that I'm missing?

### Expected Behavior

Ability to track installs manually when turning off automatic tracking

### Flutter Doctor

```shell
-
```

**Comment by davidgalarza** [comment]
any update?
