### ISSUE TITLE
[Feature]: external_id

### ISSUE THREAD

**Issue by makinghappen** [oddbit/flutter_facebook_app_events#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Library does not support passing external_id used for [advanced matching](https://developers.facebook.com/docs/meta-pixel/advanced/advanced-matching)
Can it be implemented?

### Expected Behavior

support of external_id

### Platform

Android, iOS

### Flutter Doctor

```shell
not needed, looked-up latest development branch source
```

**Comment by antonoddbit** [comment]
We need to check about the current code and Meta Pixel @makinghappen

**Comment by makinghappen** [comment]
as I see [facebook android sdk](https://github.com/facebook/facebook-android-sdk/issues/1239) does not support it either, while [IOS sdk does ](https://github.com/facebook/facebook-ios-sdk/issues/1496)

**Comment by antonoddbit** [comment]
Yes, there is 2 attributes for android, and 2 attributes for iOS.
Will check the implementation later after checking privacy update. @makinghappen do you get privacy warning?

**Comment by makinghappen** [comment]
@antonoddbit when does it shown?

**Comment by makinghappen** [comment]
BUMP
