### ISSUE TITLE
[Bug]: ios pod  error

### ISSUE THREAD

**Issue by tudosxxx** [oddbit/flutter_facebook_app_events#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error: The pod "FBAudienceNetwork" required by the plugin"facebook app events" requires a higher minimum iOS deploymentversion than the plugin's reported minimum version.To build, remove the plugin "facebook app events", or contact theplugin's developers for assistance.

### Expected Behavior

Error: The pod "FBAudienceNetwork" required by the plugin"facebook app events" requires a higher minimum iOS deploymentversion than the plugin's reported minimum version.To build, remove the plugin "facebook app events", or contact theplugin's developers for assistance.

### Platform

iOS

### Flutter Doctor

```shell
Error: The pod "FBAudienceNetwork" required by the plugin"facebook app events" requires a higher minimum iOS deploymentversion than the plugin's reported minimum version.To build, remove the plugin "facebook app events", or contact theplugin's developers for assistance.
```

**Comment by antonoddbit** [comment]
Hi @tudosxxx which version of flutter app do you use?
