### ISSUE TITLE
[Bug]: App didn't Initialize AudienceNetworkAds

### ISSUE THREAD

**Issue by yelkamel** [oddbit/flutter_facebook_app_events#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I need anonymous tracking with the Audience Network SDK. 
This requires initializing AudienceNetworkAds with the following:

```
AudienceNetworkAds.initialize(context);
```

However, your package does not perform this initialization.

### Expected Behavior

The app should be able to track events without requiring ATT to be enabled.

### Platform

Android

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.90.0)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!
```

**Comment by antonoddbit** [comment]
Hi @yelkamel, please follow Meta documentation about adding the Audience network Helper class
https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/android/initialize-sdk
Please call the helper on your MainActivity.

App event is wrapper for basic call on events in flutter, you could modify or call extra call by accessing the SDK directly on native components
