### ISSUE TITLE
[Feature request]: Update Android Facebook plugin to major version 17

### ISSUE THREAD

**Issue by Danyalo** [oddbit/flutter_facebook_app_events#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Facebook has released a new major version of Android SDK
https://central.sonatype.com/artifact/com.facebook.android/facebook-android-sdk/versions

### Expected Behavior

I suggest upgrading this plugin's Android dependency to the latest major version.
Simply specifying the `implementation 'com.facebook.android:facebook-android-sdk:[17.0,18.0)'` works in my local testing.
However I'd like to request the people who have experience with updating major versions to give this a look and see if there are more involved modifications needed to support 17.0.0 plugin.

### Platform

Android

### Flutter Doctor

```shell
Not really needed
```

**Comment by antonoddbit** [comment]
Thanks for suggestion and solution, we will check about this

**Comment by antonoddbit** [comment]
on progress PR #371
