### ISSUE TITLE
[Bug]: Undefined symbols: __swift_FORCE_LOAD_$_swiftXPC in FBAudienceNetwork

### ISSUE THREAD

**Issue by ramankanabi** [oddbit/flutter_facebook_app_events#368]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When trying to build my project with the FBAudienceNetwork package, I encounter a build error related to undefined symbols. The error message is as follows:

Undefined symbols:
 __swift_FORCE_LOAD_$_swiftXPC, referenced from:
   __swift_FORCE_LOAD_$_swiftXPC_$_FBAudienceNetwork in FBAudienceNetwork[270](FBAudienceNetwork.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Expected Behavior

The project should build successfully without any errors related to undefined symbols. changing the Audience Network iOS SDK to version 6.14 should resolve the problem.

### Platform

iOS

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-x64, locale en-IQ)
    • Flutter version 3.22.3 on channel stable at /Users/ibazzar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ibazzar/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • AE973585-FBBF-44DC-BCC1-F7495BC23F75 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 126.0.6478.183
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Barez’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by absc** [comment]
i had same issues

**Comment by shivkumarordrio** [comment]
Similar issue coming for me

Could not find or use auto-linked library 'swiftXPC': library 'swiftXPC' not found
Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
Undefined symbols:
Linker command failed with exit code 1 (use -v to see invocation)

**Comment by ramankanabi** [comment]
Temporary solution :
delete podfile.lock and pods
run flutter clean && flutter pub get  
add this in podfile.   pod 'FBAudienceNetwork', '6.14'
set FBAudienceNetwork version  6.14 in ios/.symlinks/plugins/facebook_app_events/ios/facebook_app_events.podspec 
run pod install

**Comment by ramankanabi** [comment]
> Similar issue coming for me
> 
> Could not find or use auto-linked library 'swiftXPC': library 'swiftXPC' not found Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found Undefined symbols: Linker command failed with exit code 1 (use -v to see invocation)

Temporary solution :
delete podfile.lock and pods
run flutter clean && flutter pub get
add this in podfile. pod 'FBAudienceNetwork', '6.14'
set FBAudienceNetwork version 6.14 in ios/.symlinks/plugins/facebook_app_events/ios/facebook_app_events.podspec
run pod install

**Comment by UlasAkgun** [comment]
+1

**Comment by JurassicRegz** [comment]
+1

**Comment by antonoddbit** [comment]
@ramankanabi looks like the issue is similar with #361

**Comment by antonoddbit** [comment]
hi @ramankanabi Audience network is having newer version 6.15.1 that should fix static library pointer issue. Maybe you want to try it.

**Comment by oxygen** [comment]
> hi [@ramankanabi](https://github.com/ramankanabi) Audience network is having newer version 6.15.1 that should fix static library pointer issue. Maybe you want to try it.

6.16.0 brings back those errors. I've been banging my head all day. Thanks to you I tried 6.15.2 and aside from some missing Apple app tracking framework (easily added) I've gone past the FORCE_LOAD swift stuff.

Why would Facebook release a broken SDK so often?
