### ISSUE TITLE
issue with shared_preferences

### ISSUE THREAD

**Issue by danchank** [oddbit/flutter_facebook_app_events#37]
issue with shared_preferences

[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

## Steps to Reproduce (for bugs)
1. have shared_preferences: ^0.5.7+3 using getInstance() in the main.dart
2. added facebook_app_events: ^0.6.0 into the pubsec.yaml
3. run flutter put get
4. Run the app in Android simulator in verbose mode
5. Got error: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

Flutter Doctor:
[✓] Flutter (Channel master, 1.20.0-3.0.pre.114, on Mac OS X 10.15.3 19D2064, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by sotisoti** [comment]
Similar issue here when using local_notifications + flutter_facebook_app_events

{code}
Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter/local_notifications)
{code}

**Comment by DennisAlund** [comment]
This sounds very strange to me. 

Can you please put your reproduction steps as follows and confirm

 1. Add `shared_preferences` plugin
 1. Run `flutter pub get`
 1. Run app (confirm it works)
 1. **Stop the app**
 1. Add `facebook_app_events`
 1. Run `flutter pub get`
 1. Run app (confirm if it works)

**Comment by danchank** [comment]
Dennis, I am closing it. After further evaluation and isolation of the issue I realized was not shared_preferences, but it was the FlutterWebviewPlugin. Thanks!
