### ISSUE TITLE
Error (Xcode): Undefined symbols:  Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Roni27Patel** [oddbit/flutter_facebook_app_events#372]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_FBAudienceNetwork in FBAudienceNetwork[270]

### Expected Behavior

Not Building Build file for IOS or run project

### Platform

iOS

### Flutter Doctor

```shell
swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_FBAudienceNetwork in FBAudienceNetwork[270]
```

**Comment by antonoddbit** [comment]
@Roni27Patel please see for the temporary fix in #368.
There is some issue with latest Audience network in some project, we are still checking the newest AudienceNetwork version.
For deeper discussion you can see #361.
