### ISSUE TITLE
[Bug]: Purchase events stopped sending after September 3, 2024

### ISSUE THREAD

**Issue by PetrKubes97** [oddbit/flutter_facebook_app_events#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In two separate projects, that are both using this sdk, the facebook events for "purchase" stopped sending. All other events work as expected. 

I'm updating the SDK from 1.9.2 -> 1.9.3 as the first attempt of fixing this. 

### Expected Behavior

Purchase events keep sending.

### Steps To Reproduce

-

### Flutter Doctor

```shell
-
```

**Comment by antonoddbit** [comment]
Hi @PetrKubes97 do you have more information about this bug on your setup?

**Comment by PetrKubes97** [comment]
Hi, probably not much interesting. I've created the issue in case someone else was experiencing the same issue. At the end, I don't think it is a bug with the library, more likely some backend changes on facebook's side. :(

**Comment by hamishjohnson** [comment]
I think this is of interest to you

https://www.linkedin.com/posts/olesansky_ads-meta-facebooksdk-activity-7237428023392702466-cIZM?utm_source=share&utm_medium=member_desktop

So it's not a bug - fb changed their behaviour, subscriptions now route to subscription event not purchase
