### ISSUE TITLE
It doesn't work to iOS

### ISSUE THREAD

**Issue by RicardoRB** [oddbit/flutter_facebook_app_events#39]
I basically set up my app and it is working with my android but not with my iOS. I can see my app in codeless though.

## Expected Behavior
See Facebook events on iOS phones.

## Current Behavior
Nothing is showing

## Possible Solution
Something to fix? No idea.

## Steps to Reproduce (for bugs)
1. Setup the facebook_events by the library for iOS
2. See in Facebook events or something in iOS
3. Doesn't work
4.

## Your Environment
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.959], locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

* Operating System and version:
Windows 10

**Comment by DennisAlund** [comment]
Can you clarify one thing first: You are posting that you are developing with flutter on a **Windows** machine. 

How did you build and deploy the iOS app that you have tested?

**Comment by LiveRock** [comment]
Issue resolved. It was malformed manifest file. Thank you.

**Comment by RicardoRB** [comment]
My bad, I didn't configure it well by iOS
