### ISSUE TITLE
[Bug]: Update your apps to the latest Facebook SDK

### ISSUE THREAD

**Issue by shakhob22** [oddbit/flutter_facebook_app_events#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest version of the Facebook SDK supports Apple’s SKAdNetwork API, which is required to deliver ads to people using iOS 14.5 or later devices. [Learn more](https://www.facebook.com/business/help/2750680505215705/)
We'll also prompt you to send the [Advertiser Tracking Enabled](https://developers.facebook.com/docs/app-events/guides/advertising-tracking-enabled/) flag with your app events. This will allow you to share user consent status and indicate whether you want us to treat an event as opted out from tracking.
We created this task to help you reduce the negative impacts of Apple's iOS 14 changes. Visit the [Resource Center](https://www.facebook.com/events_manager2/list/app/2875093009305651/overview?act=414189258416681#) to learn more.

### Expected Behavior

The latest version of the Facebook SDK supports Apple’s SKAdNetwork API, which is required to deliver ads to people using iOS 14.5 or later devices. [Learn more](https://www.facebook.com/business/help/2750680505215705/)
We'll also prompt you to send the [Advertiser Tracking Enabled](https://developers.facebook.com/docs/app-events/guides/advertising-tracking-enabled/) flag with your app events. This will allow you to share user consent status and indicate whether you want us to treat an event as opted out from tracking.
We created this task to help you reduce the negative impacts of Apple's iOS 14 changes. Visit the [Resource Center](https://www.facebook.com/events_manager2/list/app/2875093009305651/overview?act=414189258416681#) to learn more.

### Steps To Reproduce

The latest version of the Facebook SDK supports Apple’s SKAdNetwork API, which is required to deliver ads to people using iOS 14.5 or later devices. [Learn more](https://www.facebook.com/business/help/2750680505215705/)
We'll also prompt you to send the [Advertiser Tracking Enabled](https://developers.facebook.com/docs/app-events/guides/advertising-tracking-enabled/) flag with your app events. This will allow you to share user consent status and indicate whether you want us to treat an event as opted out from tracking.
We created this task to help you reduce the negative impacts of Apple's iOS 14 changes. Visit the [Resource Center](https://www.facebook.com/events_manager2/list/app/2875093009305651/overview?act=414189258416681#) to learn more.

### Platform

iOS

### Flutter Doctor

```shell
The latest version of the Facebook SDK supports Apple’s SKAdNetwork API, which is required to deliver ads to people using iOS 14.5 or later devices. Learn more
We'll also prompt you to send the Advertiser Tracking Enabled flag with your app events. This will allow you to share user consent status and indicate whether you want us to treat an event as opted out from tracking.
We created this task to help you reduce the negative impacts of Apple's iOS 14 changes. Visit the Resource Center to learn more.
```

**Comment by antonoddbit** [comment]
Hi @shakhob22 This plugin using latest FBSDK, please kindly check your project setup
