### ISSUE TITLE
[Bug]: Custom events don't show up 

### ISSUE THREAD

**Issue by Yusufkulcu** [oddbit/flutter_facebook_app_events#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The ready-made events in the package are visible, but the custom events are not visible. 

### Expected Behavior

Appearance of all events 

### Platform

Android, iOS

### Flutter Doctor

```shell
Everything is smooth
```

**Comment by antonoddbit** [comment]
Hi @Yusufkulcu could you explain more about the custom events? is there is some removed parameter on newest FacebookSDK or FBAudienceNetwork?

**Comment by Yusufkulcu** [comment]
@antonoddbit Please can you help

**Comment by antonoddbit** [comment]
@Yusufkulcu We are investigating about it

**Comment by antonoddbit** [comment]
@Yusufkulcu do you call the app event function when calling the custom event?

**Comment by emrszr** [comment]
same issue, any progress?
