### ISSUE TITLE
I'm not understanding how make this work

### ISSUE THREAD

**Issue by astrO1** [oddbit/flutter_facebook_app_events#43]
I already create the APP.

**Read through the "Getting Started with App Events for Android"** tutorial and in particular, follow step 2 by adding the following into /app/res/values/strings.xml (or into respective debug or release build flavor)

When I go to Facebook developer page, he aske me this :

Platform - Scroll to the bottom of the Settings panel to add the Android Platform. Add the follow details of your app:
Google Play Package Name
Class Name
Development and Release Key Hashes

I need to make this to work on my app? He says "Class Name" what is the class name if I'm using Flutter. Can you guys help me?

**Comment by DennisAlund** [comment]
Please use issue template, proper screenshots, log output etc. 

Use Github issues for **technical errors**. Use StackOverflow for discussions and help with usage.
