### ISSUE TITLE
Issues with FBSDK v5

### ISSUE THREAD

**Issue by algirdasmac** [oddbit/flutter_facebook_app_events#47]
This plugin uses FBSDK v5 and Apple is deprecating UIWebView (which v5 uses). So if we want our apps in AppStore - we need to move to a newer version - v7.

In my case, I use flutter_login_facebook 0.2.1 (which uses v7). When I add both of the plugins I get version compatibility errors:
```
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 5.0)

    flutter_login_facebook (from `.symlinks/plugins/flutter_login_facebook/ios`) was resolved to 0.1.0, which depends on
      FBSDKLoginKit (~> 7.0) was resolved to 7.0.0, which depends on
        FBSDKLoginKit/Login (= 7.0.0) was resolved to 7.0.0, which depends on
          FBSDKCoreKit (~> 7.0.0)
```

## Expected Behavior
Plugin should use FBSDK v7.

## Current Behavior
Right now plugin uses FBSDK v5.

## Steps to Reproduce (for bugs)
1. add facebook_app_events plugin to your project
2. add flutter_login_facebook plugin to your project
3. try to build for iOS

Related issues: #24 , #31 , #42

**Comment by DennisAlund** [comment]
Expected behavior is implemented in #44
