### ISSUE TITLE
getApplicationId not returning String

### ISSUE THREAD

**Issue by fstof** [oddbit/flutter_facebook_app_events#48]
Getting the application id is not correctly exposed in 'FacebookAppEvents'. It should probably return a `String` value.

https://github.com/oddbit/flutter_facebook_app_events/blob/48669e246a0d46b61038cc2875b8451ac092e327/lib/facebook_app_events.dart#L52

Will see if I can put in a PR for this when I get a chance.

**Comment by DennisAlund** [comment]
Fixed in PR #49 and released in version `0.7.0`
