### ISSUE TITLE
How to unification of the two platforms  iOS and Android Api

### ISSUE THREAD

**Issue by lessthanno** [oddbit/flutter_facebook_app_events#5]

**Comment by DennisAlund** [comment]
I am not sure I understand what the question is. 

Please provide a description of what problem that you encountered. Sufficient context and code from your project setup for me to be able to reproduce and troubleshoot.

**Comment by lessthanno** [comment]
I don't know.
how to pass the value is correct.

Eg. iOS FB API.

func logAddToWishlistEvent(contentData : String, contentId : String, contentType : String, currency : String, price : Double) {
    let params : AppEvent.ParametersDictionary = [
      .content : contentData,
      .contentId : contentId,
      .contentType : contentType,
      .currency : currency
      ]
    let event = AppEvent(name: .addedToWishlist, parameters: params, valueToSum: price)
    AppEventsLogger.log(event)
}

Eg. Android
/**
 * This function assumes logger is an instance of AppEventsLogger and has been
 * created using AppEventsLogger.newLogger() call.
 */
public void logAddToWishlistEvent (String contentData, String contentId, String contentType, String currency, double price) {
    Bundle params = new Bundle();
    params.putString(AppEventsConstants.EVENT_PARAM_CONTENT, contentData);
    params.putString(AppEventsConstants.EVENT_PARAM_CONTENT_ID, contentId);
    params.putString(AppEventsConstants.EVENT_PARAM_CONTENT_TYPE, contentType);
    params.putString(AppEventsConstants.EVENT_PARAM_CURRENCY, currency);
    logger.logEvent(AppEventsConstants.EVENT_NAME_ADDED_TO_WISHLIST, price, params);
}

The FB API names of the two platforms are different.
 
Q. Then how should I pass in flutter_app_event?
