### ISSUE TITLE
Adding facebook_app_events dependency causes fatal problems with other plugins' MethodChannels on Android

### ISSUE THREAD

**Issue by chris-rutkowski** [oddbit/flutter_facebook_app_events#52]
Hello,

Please do something as simple as this

1. new Flutter project
2. pubspec.yaml, add to dependencies (without specyfing version, but it is 0.7.0):
```
path_provider:
facebook_app_events:
```
3. main.dart, at the beginning of build method
```
print(getTemporaryDirectory());
```

Result:

```
I/flutter (  881): Instance of 'Future<Directory>'
E/flutter (  881): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter (  881): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (  881): <asynchronous suspension>
E/flutter (  881): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (  881): #2      MethodChannelPathProvider.getTemporaryPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:34:26)
E/flutter (  881): #3      getTemporaryDirectory (package:path_provider/path_provider.dart:60:39)
E/flutter (  881): #4      _MyHomePageState.build (package:fbattempt/main.dart:69:11)
E/flutter (  881): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
E/flutter (  881): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
E/flutter (  881): #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter (  881): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (  881): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (  881): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
E/flutter (  881): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (  881): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (  881): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (  881): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (  881): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (  881): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (  881): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (  881): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (  881): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (  881): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (  881): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (  881): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (  881): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (  881): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (  881): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (  881): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (  881): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (  881): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (  881): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (  881): #30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter (  881): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (  881): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (  881): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
E/flutter (  881): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (  881): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (  881): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (  881): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (  881): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (  881): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (  881): #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (  881): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (  881): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (  881): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (  881): #44 
```

This is not the problem with path provider. Every plugin using method channel starts failing after adding `facebook_app_events` - `flutter_statusbarcolor`, `sqflite`, `shared_preferences`...

This affect Android only, iOS works flawlessly. I know that I haven't configured the AndroidManifest etc in order to make the plugin work - but in the correctly configured project (I assume) I have exactly the same problem.

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (2 weeks ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```

**Comment by chris-rutkowski** [comment]
by any chance, have you been already able to replicate the issue?

**Comment by DennisAlund** [comment]
Thanks for getting involved

> I've checked your sample code and perhaps I've found the root cause, but still would like to clarify it. Why facebook_app_events is in dev_dependencies and not in dependencies

Thank you for pointing that out. It doesn't represent the real way of installing the plugin. Please follow the regular installation instructions that are in the "Installing tab" https://pub.dev/packages/facebook_app_events/install

Moving on to the initial part of your issue report. I don't really understand the issue that you are reporting.

To be more specific, I don't understand the purpose of printing the value of a `Future` in the build method as a way to replicate a bug in the plugin. 

Can you explain how that action is causing some issues with the plugin. I'm more than happy to help if I can understand what you want to accomplish and how this plugin is causing problems with that.

**Comment by chris-rutkowski** [comment]
Hello, the print is just an example.
Real life scenario: set the status bar colour, get shared preferences, do any db/file operations (needs path provider)... 

When your plugin is added the method channels of other plugins simply stop working.

**Comment by DennisAlund** [comment]
Okay, so you're saying that it works well until you try to call `getTemporaryDirectory()` ? 

Is there a minimum set of actions that can replicate the bug? 

e.g. if you completely remove `facebook_app_events` and all its configuration, it works well. But after adding the plugin and all required configuration it crashes (even if you don't call any method in the plugin).

Secondly have you been able to install and use the plugin in isolation to confirm that you can also make it work.

It's important that you both can make it work in isolation in one project (to confirm that you configure it correctly) and also make it crash with the same, correct configuration.

Because the plugin does work for most cases, so it's not completely broken. So help me find the minimum configuration/operations that makes it go from working to breaking.

**Comment by horechek** [comment]
I have same problem with facebook_app_events. After installing facebook_app_events another plugins like  firebase_analytics, smartlook and shared_preferences was crashed with problem `Unhandled Exception: MissingPluginException(No implementation found for method`

**Comment by horechek** [comment]
In my case - I am added `<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" /> not in `<application></application>` in AndroidManifest.xml, but in `<application><activity></activity></application>`. 

All problems have gone after moving tag `<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" /> into `<application></application>` directly.

**Comment by shredding** [comment]
@horechek that is missing the relevant information. You did move from where to where?

**Comment by horechek** [comment]
@shredding This is how it was in my case:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.trads">
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Trads"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <!-- I placed code here -->
            <meta-data
                android:name="com.facebook.sdk.ApplicationId"
                android:value="@string/facebook_app_id" />

        </activity>
       
    </application>
</manifest>
```

And this is how i fix my problem:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.trads">
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Trads"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
        </activity>

        <!-- fix a mistake -->
        <meta-data
                android:name="com.facebook.sdk.ApplicationId"
                android:value="@string/facebook_app_id" />

    </application>
</manifest>
```

**Comment by DennisAlund** [comment]
Thank you for sharing your learnings. This works as a good reference issue 🙏

**Comment by EffyCoder** [comment]
Hi @DennisAlund , 
I have similar issue and I have confirmed meta-tag is placed at appropriate place and also after removing your plugin from pubspec this error disappears. 

> uuid: 2.2.0
> #  facebook_app_events: ^0.7.1
>   collection: 1.15.0-nullsafety.3
>   share: ">=0.6.4+5 < 2.0.0"
>   package_info: ">=0.4.1<2.0.0"
>   catcher: ^0.3.20
>   location: ^3.0.0
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter

flutter doctor output:

> [√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1082], locale en-IN)
>     • Flutter version 1.22.1 at D:\flutter_windows_1.20.2-stable\flutter
>     • Framework revision f30b7f4db9 (10 days ago), 2020-10-08 10:06:30 -0700
>     • Engine revision 75bef9f6c8
>     • Dart version 2.10.1
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at D:\AndroidWork\sdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_HOME = D:\AndroidWork\sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 50.0.1
>     • Dart plugin version 193.7547
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code, 64-bit edition (version 1.50.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.15.1
> 
> [√] Connected device (1 available)
>     • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
> 
> • No issues found!
> 

If you need more information, I'll provide it. Thanks

**Comment by PrashhhPanchal** [comment]
Hi,


I also have this issue.
When add this plugin, multiple other plugin's "No implementation found for method getAll on channel plugins.flutter.io/package_info" error occurs.


if i remove this plugin than everything works fine.
Please help.!

**Comment by alectogeek** [comment]
Same here, cannot work with firebase package
`Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)`
