### ISSUE TITLE
Custom and standard analytics events are not logged in the Facebook dashboard.

### ISSUE THREAD

**Issue by ganeshrvel** [oddbit/flutter_facebook_app_events#53]
I have configured the app exactly as described in the ReadMe section of the package. But unfortunately the custom and standard analytics events are not getting logged in the Facebook's "Test Events" dashboard screen. Although the events like "Activate app", "fb_mobile_deactivate_app", "fb_mobile_request_deferred_deep_link" can be seen on the dashboard.

## Expected Behavior
Custom and standard analytics events should appear on the Facebook analytics dashboard.

## Current Behavior
The custom and standard analytics events are not getting logged on the Facebook dashboard

## Steps to Reproduce (for bugs)
1. Run the app
2. Dispatch an event to FB.
3.
4.

## Context
We are trying to capture events from the app.

## Your Environment
[✓] Flutter (Channel unknown, v1.17.4, on Mac OS X 10.15.6 19G73, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

**Comment by reesz** [comment]
@ganeshrvel you closed this issue yourself, what did you find/change to make it work? Experiencing the same and currently a little clue less what I could be missing.
