### ISSUE TITLE
Feature request - logInitiateCheckout

### ISSUE THREAD

**Issue by ganeshrvel** [oddbit/flutter_facebook_app_events#55]
Could you look into supporting the 'InitiateCheckout' standard event? 

https://developers.facebook.com/docs/facebook-pixel/reference

**Comment by DennisAlund** [comment]
Happy to receive pull request if you are working on some code. Just make sure that you are using "Facebook App Events" as a reference documentation and not "Facebook Pixel"

https://developers.facebook.com/docs/app-events/getting-started-app-events-android#log-manually
