### ISSUE TITLE
Cocoapods install issue on iOS when using with firebase

### ISSUE THREAD

**Issue by Theunodb** [oddbit/flutter_facebook_app_events#58]
When updating to the latest version i get the error below. Downgrading to 0.6.0 works fine.

`
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    facebook_app_events (from `.symlinks/plugins/facebook_app_events/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 7.1.0)

    flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 5.5)

CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.0-2, which depends on
      Firebase/CoreOnly (~> 6.26.0) was resolved to 6.26.0, which depends on
        FirebaseCore (= 6.7.2)

    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.0-2, which depends on
      Firebase/Firestore (~> 6.26.0) was resolved to 6.26.0, which depends on
        FirebaseFirestore (~> 1.15.0) was resolved to 1.15.0, which depends on
          FirebaseCore (~> 6.2)

    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 6.0.0, which depends on
      Firebase/Analytics (~> 6.26.0) was resolved to 6.26.0, which depends on
        Firebase/Core (= 6.26.0) was resolved to 6.26.0, which depends on
          FirebaseAnalytics (= 6.6.0) was resolved to 6.6.0, which depends on
            FirebaseCore (~> 6.7)

    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 7.0.0, which depends on
      Firebase/Messaging (~> 6.26.0) was resolved to 6.26.0, which depends on
        FirebaseMessaging (~> 4.4.1) was resolved to 4.4.1, which depends on
          FirebaseCore (~> 6.6)

`

**Comment by DennisAlund** [comment]
Please use the issue report template to provide full context.

**Comment by chamartt** [comment]
Same for me, did you fix it ?

Thank you !

**Comment by DennisAlund** [comment]
@Theunodb and @chamartt please provide full context according to the template so that we can try to troubleshoot together.

**Comment by kawoon-app** [comment]
The conflict is between **facebook_app_events** and **flutter_facebook_login**. There is nothing to do with firebase.

**Comment by MagTuxGit** [comment]
The conflict is between **facebook_app_events** and **flutter_facebook_login**. There is nothing to do with Firebase.

**Comment by MagTuxGit** [comment]
Duplicated
https://github.com/oddbit/flutter_facebook_app_events/issues/56

**Comment by DennisAlund** [comment]
Thank you for pointing the issue discussion in the right direction @MagTuxGit
