### ISSUE TITLE
FBSDKCoreKit to 8.1.0

### ISSUE THREAD

**Issue by lukasloh** [oddbit/flutter_facebook_app_events#61]
Any plans on upgrading the FBSDKCoreKit to 8.1.0 in the near future? Thanks!

**Comment by DennisAlund** [comment]
Hey, thanks for the suggestion. I haven't had any time to look into it yet. Please send questions to opensource@oddbit.id as we'll try to not use github issues as discussion boards.

https://github.com/oddbit/flutter_facebook_app_events#getting-involved

Feel free to make a pull request after testing and confirming compatibility if you have an urgent need 🙏 😃

**Comment by DennisAlund** [comment]
Fixed in 38740a63 and released in version [`0.8.0`](https://github.com/oddbit/flutter_facebook_app_events/blob/master/CHANGELOG.md#080)

**Comment by lukasloh** [comment]
@DennisAlund okay, thank you!
