### ISSUE TITLE
Feature Request - get anonymousID

### ISSUE THREAD

**Issue by chandrashan** [oddbit/flutter_facebook_app_events#62]
It would be great to have a method of retrieving the facebook anonymousID from the FBSDK via this package (https://developers.facebook.com/docs/reference/iossdk/7.1.1/FBSDKCoreKit/classes/fbsdkappevents.html/  -->  see "anonymousID")

Use case:
I use RevenueCat for subscription management in my flutter app, and they have an integration with facebook ads.  this package is doing a great job of sending the data to facebook - but the problem is that subscription information is much more accurate coming directly from revenue cat (eg people can unsubscribe, cancel trials and not open app etc).

RevenueCat sends on any events to facebook, and I have got it currently doing so using the idfa/gaid etc, but for users with LAT enabled on iOS I don't get the IDFA, and the only way to connect those people is to use the anonymousID.  What I would like to do is to get the fb anonymousID, and pass that onto revenue cat as well - but to do that I need to retrieve the anonymousID.  I'm sure there are other platforms which might use this as well.

I noticed ont he react-native-fbsdk they have enabled support for it and this seems to be the relevant iOS file - https://github.com/facebook/react-native-fbsdk/blob/master/ios/RCTFBSDK/core/RCTFBSDKAppEvents.m

Is there any chance of getting access to this property via this package as well?  I would try to make a pull request but not too confident doing any iOS coding...

**Comment by DennisAlund** [comment]
Fixed in https://github.com/oddbit/flutter_facebook_app_events/commit/b6756e8ce91279abbcb5ef50d7a5fb5064e948ad and released in version [`0.8.0`](https://github.com/oddbit/flutter_facebook_app_events/blob/master/CHANGELOG.md#080)

**Comment by chandrashan** [comment]
thank you so much for adding this!

**Comment by saarikivit** [comment]
@chandrashan I have a really hard time understanding how the anonymousID could track from an AD -> IN APP PURCHASE.

Could you help me understand?

I would like to track my profitability for facebook ads. I'm trying to add the facebook SDK. I have a kid's app, so I may not collect the IDFA & IDFV values, though.

Thanks for your help :)

**Comment by chandrashan** [comment]
@saarikivit - I use RevenueCat for subscription management.  From what I gather they trigger a web hook to Facebook whenever there is a purchase event together with the idfa/anonymousID (if idfa not available) and Facebook does something or another to try and re-match.

https://docs.revenuecat.com/docs/facebook-ads

**Comment by saarikivit** [comment]
@chandrashan thanks for the reply.

I use revenue cat also. The docs state idfa etc is required. 🤷

Not sure what to think of this xD

**Comment by chandrashan** [comment]
I think with the Apple IDFA changes, and move to SKAdnetwork etc there'll be some changes coming soon
