### ISSUE TITLE
AddtoCart event standard  

### ISSUE THREAD

**Issue by AbeerMagdyHanafy** [oddbit/flutter_facebook_app_events#76]
I added event AddtoCart by custom event (facebook AppEvents.logEvent(name: 'AddtoCart');) 
but i need (facebook AppEvents.logPurchase) event as standard to add it on my tracknig events, could you support me please..

**Comment by DennisAlund** [comment]
Sorry for not fully understanding your question. Do you need `logPurchase`? It's already implemented

https://github.com/oddbit/flutter_facebook_app_events/blob/af491253560ff18256c5e40cdc838e2d73e93d59/lib/facebook_app_events.dart#L230-L241

For further reference, use the issue template when you report as I don't know which plugin version you have been using or any context of your environment
![image](https://user-images.githubusercontent.com/2051607/107303079-5acfe480-6ab9-11eb-9012-c62b4a6a323b.png)

**Comment by AbeerMagdyHanafy** [comment]
No, I need logAddToCart standard event
![IMG_20210209_093118](https://user-images.githubusercontent.com/13411220/107329955-9b2f6280-6ab9-11eb-8084-84e3bf5f7977.jpg)

**Comment by AbeerMagdyHanafy** [comment]
No, I need logAddToCart and logcontentview standard events @DennisAlund 
![IMG_20210209_093303](https://user-images.githubusercontent.com/13411220/107330124-d598ff80-6ab9-11eb-9d28-3b991558aa17.jpg)
