### ISSUE TITLE
The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize()

### ISSUE THREAD

**Issue by pvinothit** [oddbit/flutter_facebook_app_events#78]
## Expected Behavior
It shouldn't crash

## Current Behavior

It's Crashing 

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mysoftware.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
E/AndroidRuntime(21125): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
E/AndroidRuntime(21125): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(21125): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(21125): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(21125): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(21125): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(21125): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21125): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(21125): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(21125): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21125): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(21125): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(21125): Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
E/AndroidRuntime(21125): 	at com.facebook.internal.Validate.sdkInitialized(Validate.java:135)
E/AndroidRuntime(21125): 	at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.java:487)
E/AndroidRuntime(21125): 	at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.java:483)
E/AndroidRuntime(21125): 	at com.facebook.appevents.AppEventsLogger.<init>(AppEventsLogger.java:256)
E/AndroidRuntime(21125): 	at com.facebook.appevents.AppEventsLogger.newLogger(AppEventsLogger.java:210)
E/AndroidRuntime(21125): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onAttachedToEngine(FacebookAppEventsPlugin.kt:34)
E/AndroidRuntime(21125): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java:133)
E/AndroidRuntime(21125): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:20)
E/AndroidRuntime(21125): 	at com.mysoftware.MainActivity.configureFlutterEngine(MainActivity.kt:11)
E/AndroidRuntime(21125): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:181)
E/AndroidRuntime(21125): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
E/AndroidRuntime(21125): 	at android.app.Activity.performCreate(Activity.java:8000)
E/AndroidRuntime(21125): 	at android.app.Activity.performCreate(Activity.java:7984)
E/AndroidRuntime(21125): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(21125): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime(21125): 	... 11 more
Error connecting to the service protocol: failed to connect to http://127.0.0.1:51477/NZZ4auTvx7E=/
`

## Steps to Reproduce (for bugs)

1. Change the Kotlin Main activity like this 
`import android.os.Bundle
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}`

## Context
I can't use the library at all in Android.

## Your Environment
*  Output from `flutter doctor`
    `Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.52.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (3 available)
`
   
* Operating System and version: MacOS BigSur

**Comment by DennisAlund** [comment]
Have you searched issues?

- #10
- #22 
- #25
