### ISSUE TITLE
cannot compile in xcode

### ISSUE THREAD

**Issue by basnetjiten** [oddbit/flutter_facebook_app_events#79]
import FBSDKCoreKitCompiling for iOS 8.0, but module 'FBSDKCoreKit' has a minimum deployment target of iOS 9.0: /Users/payneppvtltd/Library/Developer/Xcode/DerivedData/Runner-grxwssmjuqjqxidanurymkoortdy/Build/Products/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.framework/Modules/FBSDKCoreKit.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Comment by flutterwtf** [comment]
The same is for me. Any fixes?

**Comment by DennisAlund** [comment]
1. Please search existing issues
2. Use issue template
3. It's a duplicate
