### ISSUE TITLE
App Id Not Found

### ISSUE THREAD

**Issue by BrunoJurkovic** [oddbit/flutter_facebook_app_events#8]
## Expected Behavior
I followed all of the instructions from your and facebook's docs, everything is supposed to build normally. 

## Current Behavior
I get thrown this error:

> > [  +45 ms] FAILURE: Build failed with an exception.
> > [   +1 ms] * What went wrong:
> > [        ] Execution failed for task ':facebook_app_events:verifyReleaseResources'.
> > [        ] > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
> > [        ]   Output:
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\aapt_friendly_merged_manifests\release\processReleaseManifest\aapt\AndroidManifest.xml:10: error: resource string/facebook_app_id (aka id.oddbit.flutter.facebook_app_events:string/facebook_app_id) not found.
> > [        ]   error: failed processing manifest.
> > [        ]   Command:
> > C:\Users\bruno\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\63134955e3d640caddcb147528e119a9\aapt2-3.2.1-4818971-windows\aapt2.exe link
> > -I\
> > [        ]           C:\Users\bruno\AppData\Local\Android\sdk\platforms\android-28\android.jar\
> > [        ]           --manifest\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\aapt_friendly_merged_manifests\release\processReleaseManifest\aapt\AndroidManifest.xml\
> > [        ]           -o\
> > [        ]           C:\Users\bruno\AppData\Local\Temp\aapt-2228850768721564865-out\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_low_normal.9.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_low_pressed.9.png.flat\
> > [   +1 ms]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_normal.9.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-hdpi-v4_notification_bg_normal_pressed.9.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-hdpi-v4_notify_panel_notification_icon_bg.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_low_normal.9.png.flat\
> > [   +1 ms]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_low_pressed.9.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_normal.9.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-mdpi-v4_notification_bg_normal_pressed.9.png.flat\
> > [   +1 ms]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-mdpi-v4_notify_panel_notification_icon_bg.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-v21_notification_action_background.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_low_normal.9.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_low_pressed.9.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_normal.9.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-xhdpi-v4_notification_bg_normal_pressed.9.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable-xhdpi-v4_notify_panel_notification_icon_bg.png.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable_notification_bg.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable_notification_bg_low.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable_notification_icon_background.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\drawable_notification_tile_bg.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout-v16_notification_template_custom_big.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout-v21_notification_action.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout-v21_notification_action_tombstone.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout-v21_notification_template_custom_big.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout-v21_notification_template_icon_group.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout_notification_action.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout_notification_action_tombstone.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout_notification_template_icon_group.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout_notification_template_part_chronometer.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\layout_notification_template_part_time.xml.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-af_values-af.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-am_values-am.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ar_values-ar.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-as_values-as.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-az_values-az.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-b+sr+Latn_values-b+sr+Latn.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-be_values-be.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-bg_values-bg.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-bn_values-bn.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-bs_values-bs.arsc.flat\
> > [        ]           -R\
> > [   +1 ms] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ca_values-ca.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-cs_values-cs.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-da_values-da.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-de_values-de.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-el_values-el.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-en-rAU_values-en-rAU.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-en-rCA_values-en-rCA.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-en-rGB_values-en-rGB.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-en-rIN_values-en-rIN.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-en-rXC_values-en-rXC.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-es-rUS_values-es-rUS.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-es_values-es.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-et_values-et.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-eu_values-eu.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-fa_values-fa.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-fi_values-fi.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-fr-rCA_values-fr-rCA.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-fr_values-fr.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-gl_values-gl.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-gu_values-gu.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-hi_values-hi.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-hr_values-hr.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-hu_values-hu.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-hy_values-hy.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-in_values-in.arsc.flat\
> > [  +12 ms]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-is_values-is.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-it_values-it.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-iw_values-iw.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ja_values-ja.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ka_values-ka.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-kk_values-kk.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-km_values-km.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-kn_values-kn.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ko_values-ko.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ky_values-ky.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-lo_values-lo.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-lt_values-lt.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-lv_values-lv.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-mk_values-mk.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ml_values-ml.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-mn_values-mn.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-mr_values-mr.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ms_values-ms.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-my_values-my.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-nb_values-nb.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ne_values-ne.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-nl_values-nl.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-or_values-or.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-pa_values-pa.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-pl_values-pl.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-pt-rBR_values-pt-rBR.arsc.flat\
> > [        ]           -R\
> > [   +1 ms] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-pt-rPT_values-pt-rPT.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-pt_values-pt.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ro_values-ro.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ru_values-ru.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-si_values-si.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-sk_values-sk.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-sl_values-sl.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-sq_values-sq.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-sr_values-sr.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-sv_values-sv.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-sw_values-sw.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ta_values-ta.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-te_values-te.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-th_values-th.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-tl_values-tl.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-tr_values-tr.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-uk_values-uk.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-ur_values-ur.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-uz_values-uz.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-v16_values-v16.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-v21_values-v21.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-vi_values-vi.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-zh-rCN_values-zh-rCN.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-zh-rHK_values-zh-rHK.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-zh-rTW_values-zh-rTW.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values-zu_values-zu.arsc.flat\
> > [        ]           -R\
> > [        ] 
> > C:\Users\bruno\Documents\development\fortbuddy\fortbuddy\build\facebook_app_events\intermediates\res\compiled\release\values_values.arsc.flat\
> > [        ]           --auto-add-overlay\
> > [        ]           --non-final-ids\
> > [   +6 ms]           -0\
> > [   +1 ms]           apk\
> > [        ]           --no-version-vectors
> > [        ]   Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
> > [   +1 ms] * Try:
> > [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > [        ] * Get more help at https://help.gradle.org
> > [        ] BUILD FAILED in 1m 23s
> > [ +323 ms] Running Gradle task 'assembleRelease'... (completed in 84.0s)
> > [        ] *******************************************************************************************
> > [        ] The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
> > [        ] See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> > [        ] *******************************************************************************************
> > [   +3 ms] "flutter apk" took 95,042ms.
> > Gradle task assembleRelease failed with exit code 1
> > 
> > #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
> > #1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
> > #2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
> > #3      _rootRunUnary (dart:async/zone.dart:1132:38)
> > #4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> > #5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
> > #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
> > #7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
> > #8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
> > #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
> > #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
> > #11     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
> > #12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
> > #13     _rootRunUnary (dart:async/zone.dart:1132:38)
> > #14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> > #15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
> > #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
> > #17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
> > #18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
> > #19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
> > #20     _rootRun (dart:async/zone.dart:1124:13)
> > #21     _CustomZone.run (dart:async/zone.dart:1021:19)
> > #22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> > #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> > #24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> > #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> > #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
> > #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
> 

## Steps to Reproduce (for bugs)
Build the app.

## Context
I am just trying to build the app in release mode.

## Your Environment
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.805], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by BrunoJurkovic** [comment]
Here is my AndroidManifest.xml file

> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.remade.fortbuddy">

    
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="FortBuddy"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="com.facebook.sdk.ApplicationId"
                android:value="@string/facebook_app_id"/>
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>

**Comment by BrunoJurkovic** [comment]
And my string.xml file:
`<?xml version="1.0" encoding="utf-8"?>
<resources>
        <string name="facebook_app_id">1785901631541822</string>
        <string name="fb_login_protocol_scheme">fb1785901631541822</string>
</resources>`

**Comment by DennisAlund** [comment]
I've got this same feedback in a couple of issues that never got followed up to conclusion of what the issue was and how it was resolved in the end. (#2, #4)

Perhaps we can find out here. Where is the location of the string.xml file in your project structure?

**Comment by BrunoJurkovic** [comment]
Thanks for responding Dennis, this is my relative path to the `strings.xml` file.
`android\app\src\main\res\values\strings.xml`

**Comment by BrunoJurkovic** [comment]
Hello? Could I get a response please? :)

**Comment by DennisAlund** [comment]
Hi @BrunoJurkovic thanks for being active in helping to improve this plugin. But I am not on 24 hour support for this. It is an open source project and I am maintaining it on my spare time. I will look into it as soon as I get a chance. You can try to hack it to work and help me to find the issue and submit a pull request if you find that it is a bug in the plugin.

**Comment by DennisAlund** [comment]
I will look into it as soon as possible. In the meantime you it can be very helpful to try to find a configuration that makes it work for you. For us to identify if it is a bug or just setup issue.

**Comment by DennisAlund** [comment]
Fixed in version 0.5.0
