### ISSUE TITLE
iOS 14 - support setAdvertiserTrackingEnabled flag

### ISSUE THREAD

**Issue by juliavi** [oddbit/flutter_facebook_app_events#80]
## Expected Behavior

Starting with iOS 14, you will need to set the setAdvertiserTrackingEnabled flag. 
This allows you to inform Facebook whether to use the data to deliver personalized ads in line with your own legal obligations, platform terms, and commitments you’ve made to your users. If the flag is set to false we will not be able to deliver personalized ads.

## Current Behavior

Right now the flutter package does not work for iOS 14 users, because it does not set setAdvertiserTrackingEnabled.  

## Possible Solution

Implement setAdvertiserTrackingEnabled as part of the flutter package.

## Context

https://developers.facebook.com/docs/audience-network/guides/advertising-tracking-enabled/

## Your Environment
iOS 14

**Comment by DennisAlund** [comment]
Documentation for App Events: https://developers.facebook.com/docs/app-events/getting-started-app-events-ios/#get-device-consent

**Comment by ibrahimdevs** [comment]
@DennisAlund what is the last status of iOS 14 support? Do you plan to publish an udate soon?
@ TheHappyDev thanks for fix.

**Comment by DennisAlund** [comment]
Sorry for late follow up. I've made some comments on the PR. In general it looks good! Let's make it happen! 😃

**Comment by ibrahimdevs** [comment]
Thanks for your efforts and this package @DennisAlund  👍  Waiting for update on pub.dev now..

**Comment by DennisAlund** [comment]
Fixed in PR #82
