### ISSUE TITLE
issue with shared_preferences on Android

### ISSUE THREAD

**Issue by ian-ng** [oddbit/flutter_facebook_app_events#84]
In Android devices, when using facebook_app_events, probably there are some conflicts with shared_preferences.

When adding facebook_app_events and run the app, the below exception comes out.
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

## Steps to Reproduce (for bugs)

1. Add `shared_preferences` plugin
2. Run `flutter pub get`
3. change `main() { ... runApp(MyApp); }` to `Future<void> main() async { ... runApp(MyApp); }` on **main.dart**.
4. Import `shared_preferences` and add `SharedPreferences prefs = await SharedPreferences.getInstance();` before `runApp(MyApp)` on **main.dart**.
5. Run app (It works)
6. Stop the app
7. Add `facebook_app_events`
8. Run `flutter pub get`
9. Run app (Exception caught)

## Context

I want to track the Facebook app events on both iOS and Android devices. It works on iOS, but on Android, this exception stops me and cannot track the app events correctly.

## Your Environment
* Output from `flutter doctor`
* Operating System and version:
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-MO)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.43.1)
[✓] Connected device (3 available)

## Plugin Versions
dependencies:
  shared_preferences: ^0.5.12+4
  facebook_app_events: ^0.9.0

**Comment by DennisAlund** [comment]
Does this help you? https://github.com/oddbit/flutter_facebook_app_events/issues/37#issuecomment-655780133

Please search the issues for `shared_preferences` and see if you find solution among the issues that were closed due to project configuration error: https://github.com/oddbit/flutter_facebook_app_events/issues?q=is%3Aissue+is%3Aclosed+shared_preferences+

Reopen if this is not related to any of those. 

Thank you.

**Comment by ian-ng** [comment]
> Does this help you? [#37 (comment)](https://github.com/oddbit/flutter_facebook_app_events/issues/37#issuecomment-655780133)
> 
> Please search the issues for `shared_preferences` and see if you find solution among the issues that were closed due to project configuration error: https://github.com/oddbit/flutter_facebook_app_events/issues?q=is%3Aissue+is%3Aclosed+shared_preferences+
> 
> Reopen if this is not related to any of those.
> 
> Thank you.

Hello Dennis, 

I have seen [#37 (comment)](https://github.com/oddbit/flutter_facebook_app_events/issues/37#issuecomment-655780133) and some other related issues. However, it seems not exactly the same problem and cannot solve my problem. 

I have created a new project to isolate only `shared_preferences` and it seems to work fine. Then, I just added `facebook_app_events`, `flutter pub get` and run it, the exception comes out. I have not use `FlutterWebviewPlugin` that mentioned by [#37 (comment)](https://github.com/oddbit/flutter_facebook_app_events/issues/37#issuecomment-655780133).

Hope you can try it and see if it could be reproduced. 

Thanks.

**Comment by ian-ng** [comment]
Finally fixed by [#52 (comment)](https://github.com/oddbit/flutter_facebook_app_events/issues/52#issuecomment-690984118).

Thanks.
