### ISSUE TITLE
Deep link support (fetchDeferredAppLink)

### ISSUE THREAD

**Issue by furaiev** [oddbit/flutter_facebook_app_events#9]
Hi,
Could you please add a deep links support (https://developers.facebook.com/docs/reference/ios/current/class/FBSDKAppLinkUtility/#fetchDeferredAppLink)?

**Comment by DennisAlund** [comment]
The current scope of the plugin is only for [AppEvents](https://developers.facebook.com/docs/reference/ios/current/class/FBSDKAppEvents/) ... but it would definitely be a great idea to have more plugins or perhaps a well developed plugin that implements all of the SDK features.

**Comment by alectogeek** [comment]
Are there any good packages to work both with app events and deep links? 
I was surprised not being able to find any which would not be abandoned...
