### ISSUE TITLE
Null Safety 

### ISSUE THREAD

**Issue by dospringer** [oddbit/flutter_facebook_app_events#92]
It would be really cool if the package migrates to null safety :)  Is there a plan to do this in the next time?

**Comment by jaumard** [comment]
There is an open PR, would be nice to have it reviewed and merged please https://github.com/oddbit/flutter_facebook_app_events/pull/90

**Comment by dospringer** [comment]
Nice, thanks for you work @jaumard ! I hope it will merged 👍

**Comment by yanivshaked** [comment]
Hi guys @paramadharmika @gedenata @MrAlek,

How soon can this be merged to a new release?

Thanks!

**Comment by DennisAlund** [comment]
Released in [`v0.12.0`](https://pub.dev/packages/facebook_app_events/changelog#0120) thank you for your contributions!!! 🚀
